// Generated by Framer (c563d2c)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  Link,
  RichText,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/Dxx31XKDjQ4HhYYwPJEY/LSPBzJYmIBt7y7avVHNq/pFXRpm75X.js";
const enabledGestures = { D90RBg49P: { hover: true } };
const cycleOrder = ["D90RBg49P", "Kpd0EiCi0"];
const serializationHash = "framer-Rq3Pv";
const variantClassNames = {
  D90RBg49P: "framer-v-76oe1d",
  Kpd0EiCi0: "framer-v-8ibbxv",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Tablet-Phone": "Kpd0EiCi0",
  Desktop: "D90RBg49P",
};
const getProps = ({ click, height, id, link, text, width, ...props }) => {
  return {
    ...props,
    EqY7rffBl: link ?? props.EqY7rffBl,
    uXKPRM18a: click ?? props.uXKPRM18a,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "D90RBg49P",
    XG5lVNUrp: text ?? props.XG5lVNUrp ?? "Home",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const {
    style,
    className,
    layoutId,
    variant,
    EqY7rffBl,
    XG5lVNUrp,
    uXKPRM18a,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "D90RBg49P",
    enabledGestures,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTapzptq81 = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (uXKPRM18a) {
      const res = await uXKPRM18a(...args);
      if (res === false) return false;
    }
  });
  const sharedStyleClassNames = [sharedStyle.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const ref1 = React.useRef(null);
  const isDisplayed = () => {
    if (baseVariant === "Kpd0EiCi0") return false;
    return true;
  };
  const defaultLayoutId = React.useId();
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: EqY7rffBl,
          nodeId: "D90RBg49P",
          children: /*#__PURE__*/ _jsxs(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(
              scopingClassNames,
              "framer-76oe1d",
              className,
              classNames
            )} framer-146nb98`,
            "data-framer-name": "Desktop",
            "data-highlight": true,
            layoutDependency: layoutDependency,
            layoutId: "D90RBg49P",
            onTap: onTapzptq81,
            ref: ref ?? ref1,
            style: { ...style },
            ...addPropertyOverrides(
              {
                "D90RBg49P-hover": { "data-framer-name": undefined },
                Kpd0EiCi0: { "data-framer-name": "Tablet-Phone" },
              },
              baseVariant,
              gestureVariant
            ),
            children: [
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-10ygvy8",
                    "data-styles-preset": "pFXRpm75X",
                    children: "Home",
                  }),
                }),
                className: "framer-1vowgdm",
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "SW7wODC9u",
                style: { "--framer-paragraph-spacing": "0px" },
                text: XG5lVNUrp,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
              isDisplayed() &&
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      className: "framer-styles-preset-10ygvy8",
                      "data-styles-preset": "pFXRpm75X",
                      children: "Home",
                    }),
                  }),
                  className: "framer-7xhv9u",
                  fonts: ["Inter"],
                  layoutDependency: layoutDependency,
                  layoutId: "u6dPZHnKV",
                  style: { "--framer-paragraph-spacing": "0px" },
                  text: XG5lVNUrp,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-Rq3Pv.framer-146nb98, .framer-Rq3Pv .framer-146nb98 { display: block; }",
  ".framer-Rq3Pv.framer-76oe1d { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
  ".framer-Rq3Pv .framer-1vowgdm { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-Rq3Pv .framer-7xhv9u { flex: none; height: auto; left: 0px; position: absolute; top: -38px; white-space: pre; width: auto; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Rq3Pv.framer-76oe1d { gap: 0px; } .framer-Rq3Pv.framer-76oe1d > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-Rq3Pv.framer-76oe1d > :first-child { margin-top: 0px; } .framer-Rq3Pv.framer-76oe1d > :last-child { margin-bottom: 0px; } }",
  ".framer-Rq3Pv.framer-v-8ibbxv.framer-76oe1d { overflow: visible; }",
  ".framer-Rq3Pv.framer-v-76oe1d.hover .framer-1vowgdm { bottom: -38px; left: 0px; position: absolute; }",
  ".framer-Rq3Pv.framer-v-76oe1d.hover .framer-7xhv9u { left: unset; position: relative; top: unset; }",
  ...sharedStyle.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 39
 * @framerIntrinsicWidth 79
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"Kpd0EiCi0":{"layout":["auto","auto"]},"YJOtoT9ax":{"layout":["auto","auto"]}}}
 * @framerVariables {"EqY7rffBl":"link","XG5lVNUrp":"text","uXKPRM18a":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerKuRiKOMvD = withCSS(Component, css, "framer-Rq3Pv");
export default FramerKuRiKOMvD;
FramerKuRiKOMvD.displayName = "Header / Nav link";
FramerKuRiKOMvD.defaultProps = { height: 39, width: 79 };
addPropertyControls(FramerKuRiKOMvD, {
  variant: {
    options: ["D90RBg49P", "Kpd0EiCi0"],
    optionTitles: ["Desktop", "Tablet-Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  EqY7rffBl: { title: "Link", type: ControlType.Link },
  XG5lVNUrp: {
    defaultValue: "Home",
    displayTextArea: false,
    title: "Text",
    type: ControlType.String,
  },
  uXKPRM18a: { title: "Click", type: ControlType.EventHandler },
});
addFonts(
  FramerKuRiKOMvD,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerKuRiKOMvD",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerVariables:
          '{"EqY7rffBl":"link","XG5lVNUrp":"text","uXKPRM18a":"click"}',
        framerIntrinsicWidth: "79",
        framerComponentViewportWidth: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"Kpd0EiCi0":{"layout":["auto","auto"]},"YJOtoT9ax":{"layout":["auto","auto"]}}}',
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "39",
        framerContractVersion: "1",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./KuRiKOMvD.map
