// Generated by Framer (915daba)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  cx,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
const enabledGestures = { yge90ZSF4: { hover: true } };
const serializationHash = "framer-wqtrJ";
const variantClassNames = { yge90ZSF4: "framer-v-swte2q" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, width, ...props }) => {
  return { ...props };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "yge90ZSF4",
    enabledGestures,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-swte2q",
            className,
            classNames
          ),
          "data-border": true,
          "data-framer-name": "Button",
          layoutDependency: layoutDependency,
          layoutId: "yge90ZSF4",
          ref: ref ?? ref1,
          style: {
            "--border-bottom-width": "1px",
            "--border-color": "rgb(217, 217, 217)",
            "--border-left-width": "1px",
            "--border-right-width": "1px",
            "--border-style": "solid",
            "--border-top-width": "1px",
            backgroundColor: "rgb(255, 255, 255)",
            borderBottomLeftRadius: 50,
            borderBottomRightRadius: 50,
            borderTopLeftRadius: 50,
            borderTopRightRadius: 50,
            ...style,
          },
          variants: {
            "yge90ZSF4-hover": {
              "--border-color": "rgba(217, 217, 217, 0)",
              backgroundColor:
                "var(--token-1662617d-fd18-4319-b3da-aa36e5415705, rgb(249, 69, 45))",
            },
          },
          ...addPropertyOverrides(
            { "yge90ZSF4-hover": { "data-framer-name": undefined } },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsx(RichText, {
            __fromCanvasComponent: true,
            children: /*#__PURE__*/ _jsx(React.Fragment, {
              children: /*#__PURE__*/ _jsx(motion.p, {
                style: {
                  "--font-selector": "SW50ZXItU2VtaUJvbGQ=",
                  "--framer-font-family":
                    '"Inter", "Inter Placeholder", sans-serif',
                  "--framer-font-size": "11px",
                  "--framer-font-weight": "600",
                  "--framer-letter-spacing": "-0.03em",
                  "--framer-line-height": "100%",
                  "--framer-text-color":
                    "var(--extracted-r6o4lv, var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12)))",
                  "--framer-text-transform": "uppercase",
                },
                children: "Read more",
              }),
            }),
            className: "framer-a1jkk",
            "data-framer-name": "Read more",
            fonts: ["Inter-SemiBold"],
            layoutDependency: layoutDependency,
            layoutId: "ohhqbJbE5",
            style: {
              "--extracted-r6o4lv":
                "var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12))",
              "--framer-paragraph-spacing": "0px",
            },
            variants: {
              "yge90ZSF4-hover": {
                "--extracted-r6o4lv":
                  "var(--token-d74d16c5-23aa-4649-a2ad-0da8c936dade, rgb(255, 255, 255))",
              },
            },
            verticalAlignment: "top",
            withExternalLayout: true,
            ...addPropertyOverrides(
              {
                "yge90ZSF4-hover": {
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      style: {
                        "--font-selector": "SW50ZXItU2VtaUJvbGQ=",
                        "--framer-font-family":
                          '"Inter", "Inter Placeholder", sans-serif',
                        "--framer-font-size": "11px",
                        "--framer-font-weight": "600",
                        "--framer-letter-spacing": "-0.03em",
                        "--framer-line-height": "100%",
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-d74d16c5-23aa-4649-a2ad-0da8c936dade, rgb(255, 255, 255)))",
                        "--framer-text-transform": "uppercase",
                      },
                      children: "Read more",
                    }),
                  }),
                },
              },
              baseVariant,
              gestureVariant
            ),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-wqtrJ.framer-15fnjz0, .framer-wqtrJ .framer-15fnjz0 { display: block; }",
  ".framer-wqtrJ.framer-swte2q { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 9px 14px 9px 14px; position: relative; width: min-content; }",
  ".framer-wqtrJ .framer-a1jkk { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-wqtrJ.framer-swte2q { gap: 0px; } .framer-wqtrJ.framer-swte2q > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-wqtrJ.framer-swte2q > :first-child { margin-left: 0px; } .framer-wqtrJ.framer-swte2q > :last-child { margin-right: 0px; } }",
  '.framer-wqtrJ[data-border="true"]::after, .framer-wqtrJ [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 29
 * @framerIntrinsicWidth 90
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"esIy59rrp":{"layout":["auto","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerdWDvsM_2w = withCSS(Component, css, "framer-wqtrJ");
export default FramerdWDvsM_2w;
FramerdWDvsM_2w.displayName = "UI / Outline button";
FramerdWDvsM_2w.defaultProps = { height: 29, width: 90 };
addFonts(
  FramerdWDvsM_2w,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/1ZFS7N918ojhhd0nQWdj3jz4w.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
          weight: "600",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerdWDvsM_2w",
      slots: [],
      annotations: {
        framerIntrinsicHeight: "29",
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"esIy59rrp":{"layout":["auto","auto"]}}}',
        framerComponentViewportWidth: "true",
        framerDisplayContentsDiv: "false",
        framerIntrinsicWidth: "90",
        framerContractVersion: "1",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./dWDvsM_2w.map
