// Generated by Framer (a2bd428)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  Image,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { Icon as Phosphor } from "https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/p8dptk4UIND8hbFWz9V7/Phosphor.js";
import * as sharedStyle1 from "https://framerusercontent.com/modules/xXzuCfPncZnDWLrYmtNO/d2zRurFeeTcEsDvokAYB/DPl1XeZ47.js";
import * as sharedStyle from "https://framerusercontent.com/modules/99CfbQ0g2aHd3wkMunJ6/y1C7t0UV7hgBOIy2DUxd/q35quwzCc.js";
import * as sharedStyle2 from "https://framerusercontent.com/modules/0JLPmaxZxenFQzSWFxwu/qJpZiXfAIi1MBZmmNkaC/sw01V2bJD.js";
import * as sharedStyle3 from "https://framerusercontent.com/modules/oMgXPBeR6YdHTzKPyOpl/EoE1kmmGpZHB3Wts7nST/xNIXLfFSf.js";
const PhosphorFonts = getFonts(Phosphor);
const MotionDivWithFX = withFX(motion.div);
const cycleOrder = ["WN0gvTTUg", "p0HhGt1NQ"];
const serializationHash = "framer-lXGbj";
const variantClassNames = {
  p0HhGt1NQ: "framer-v-7my9cv",
  WN0gvTTUg: "framer-v-1vlo0dx",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const animation = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 30,
};
const transition2 = {
  delay: 0,
  duration: 1.6,
  ease: [0.68, 0, 0, 0.99],
  type: "tween",
};
const transition3 = {
  delay: 0.2,
  duration: 1.6,
  ease: [0.68, 0, 0, 0.99],
  type: "tween",
};
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Desktop: "WN0gvTTUg", Phone: "p0HhGt1NQ" };
const getProps = ({
  _01Description,
  _01Number,
  _02Description,
  _02Number,
  avatar,
  bGColor,
  borderColor,
  height,
  id,
  name1,
  occupation,
  starColor,
  testimonial,
  textColor,
  width,
  ...props
}) => {
  return {
    ...props,
    AM46op7Lx:
      textColor ??
      props.AM46op7Lx ??
      "var(--token-d74d16c5-23aa-4649-a2ad-0da8c936dade, rgb(255, 255, 255))",
    d4lzmm0YL: _01Description ?? props.d4lzmm0YL ?? "01 description",
    DMTP3vKWw:
      bGColor ??
      props.DMTP3vKWw ??
      "var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12))",
    F9uW9JjKI: _02Number ?? props.F9uW9JjKI ?? "+00%",
    HZi8Dk5hs: _01Number ?? props.HZi8Dk5hs ?? "+00%",
    jjg85LuOE:
      starColor ??
      props.jjg85LuOE ??
      "var(--token-1662617d-fd18-4319-b3da-aa36e5415705, rgb(249, 69, 45))",
    qXDjeqRcY: name1 ?? props.qXDjeqRcY ?? "Name",
    V5EvMzZAA: occupation ?? props.V5EvMzZAA ?? "Occupation",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "WN0gvTTUg",
    VZf4KPRV3: borderColor ??
      props.VZf4KPRV3 ?? {
        borderBottomWidth: 0,
        borderColor: "rgba(255, 255, 255, 0.2)",
        borderLeftWidth: 0,
        borderRightWidth: 0,
        borderStyle: "solid",
        borderTopWidth: 1,
      },
    y8_auQFXP: avatar ?? props.y8_auQFXP,
    ysHGQbLqA: testimonial ?? props.ysHGQbLqA ?? "Testimonial",
    ZL3Q30CZC: _02Description ?? props.ZL3Q30CZC ?? "02 description",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const {
    style,
    className,
    layoutId,
    variant,
    ysHGQbLqA,
    HZi8Dk5hs,
    d4lzmm0YL,
    F9uW9JjKI,
    ZL3Q30CZC,
    y8_auQFXP,
    qXDjeqRcY,
    V5EvMzZAA,
    jjg85LuOE,
    AM46op7Lx,
    DMTP3vKWw,
    VZf4KPRV3,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "WN0gvTTUg",
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [
    sharedStyle.className,
    sharedStyle1.className,
    sharedStyle2.className,
    sharedStyle3.className,
  ];
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            serializationHash,
            ...sharedStyleClassNames,
            "framer-1vlo0dx",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "WN0gvTTUg",
          ref: ref ?? ref1,
          style: { backgroundColor: DMTP3vKWw, ...style },
          ...addPropertyOverrides(
            { p0HhGt1NQ: { "data-framer-name": "Phone" } },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsxs(MotionDivWithFX, {
              __framer__animate: { transition: transition2 },
              __framer__animateOnce: true,
              __framer__enter: animation,
              __framer__styleAppearEffectEnabled: true,
              __framer__threshold: 0.5,
              __perspectiveFX: false,
              __smartComponentFX: true,
              __targetOpacity: 1,
              className: "framer-12mumlp",
              "data-framer-name": "Top",
              layoutDependency: layoutDependency,
              layoutId: "mjI_d21mT",
              ...addPropertyOverrides(
                {
                  p0HhGt1NQ: { __framer__styleAppearEffectEnabled: undefined },
                },
                baseVariant,
                gestureVariant
              ),
              children: [
                /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-8ykqw6",
                  "data-framer-name": "Rating",
                  layoutDependency: layoutDependency,
                  layoutId: "Ey1iEvZvz",
                  children: [
                    /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      children: /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1ir5b4p-container",
                        layoutDependency: layoutDependency,
                        layoutId: "cUgbsyVkQ-container",
                        children: /*#__PURE__*/ _jsx(Phosphor, {
                          color: jjg85LuOE,
                          height: "100%",
                          iconSearch: "star",
                          iconSelection: "House",
                          id: "cUgbsyVkQ",
                          layoutId: "cUgbsyVkQ",
                          mirrored: false,
                          selectByList: false,
                          style: { height: "100%", width: "100%" },
                          weight: "fill",
                          width: "100%",
                        }),
                      }),
                    }),
                    /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      children: /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-hlbcud-container",
                        layoutDependency: layoutDependency,
                        layoutId: "WRoglEIhJ-container",
                        children: /*#__PURE__*/ _jsx(Phosphor, {
                          color: jjg85LuOE,
                          height: "100%",
                          iconSearch: "star",
                          iconSelection: "House",
                          id: "WRoglEIhJ",
                          layoutId: "WRoglEIhJ",
                          mirrored: false,
                          selectByList: false,
                          style: { height: "100%", width: "100%" },
                          weight: "fill",
                          width: "100%",
                        }),
                      }),
                    }),
                    /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      children: /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-11urm9k-container",
                        layoutDependency: layoutDependency,
                        layoutId: "m86TiQSbX-container",
                        children: /*#__PURE__*/ _jsx(Phosphor, {
                          color: jjg85LuOE,
                          height: "100%",
                          iconSearch: "star",
                          iconSelection: "House",
                          id: "m86TiQSbX",
                          layoutId: "m86TiQSbX",
                          mirrored: false,
                          selectByList: false,
                          style: { height: "100%", width: "100%" },
                          weight: "fill",
                          width: "100%",
                        }),
                      }),
                    }),
                    /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      children: /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-4c742-container",
                        layoutDependency: layoutDependency,
                        layoutId: "Z9oQMc4o4-container",
                        children: /*#__PURE__*/ _jsx(Phosphor, {
                          color: jjg85LuOE,
                          height: "100%",
                          iconSearch: "star",
                          iconSelection: "House",
                          id: "Z9oQMc4o4",
                          layoutId: "Z9oQMc4o4",
                          mirrored: false,
                          selectByList: false,
                          style: { height: "100%", width: "100%" },
                          weight: "fill",
                          width: "100%",
                        }),
                      }),
                    }),
                    /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                      children: /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-134ikfa-container",
                        layoutDependency: layoutDependency,
                        layoutId: "JGIusuIca-container",
                        children: /*#__PURE__*/ _jsx(Phosphor, {
                          color: jjg85LuOE,
                          height: "100%",
                          iconSearch: "star",
                          iconSelection: "House",
                          id: "JGIusuIca",
                          layoutId: "JGIusuIca",
                          mirrored: false,
                          selectByList: false,
                          style: { height: "100%", width: "100%" },
                          weight: "fill",
                          width: "100%",
                        }),
                      }),
                    }),
                  ],
                }),
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      className: "framer-styles-preset-1dmjd5e",
                      "data-styles-preset": "q35quwzCc",
                      style: {
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--variable-reference-AM46op7Lx-jFWuJpyza))",
                      },
                      children: "Testimonial",
                    }),
                  }),
                  className: "framer-zayyxm",
                  "data-framer-name":
                    "They helped us shape our brand identity from scratch, giving us a website that perfectly reflects our values.",
                  fonts: ["Inter"],
                  layoutDependency: layoutDependency,
                  layoutId: "S7EEAb6IP",
                  style: {
                    "--extracted-r6o4lv":
                      "var(--variable-reference-AM46op7Lx-jFWuJpyza)",
                    "--framer-paragraph-spacing": "0px",
                    "--variable-reference-AM46op7Lx-jFWuJpyza": AM46op7Lx,
                  },
                  text: ysHGQbLqA,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                }),
              ],
            }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-1jzmwku",
              "data-framer-name": "filler",
              layoutDependency: layoutDependency,
              layoutId: "fbCYn2aeL",
            }),
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-s21afs",
              "data-framer-name": "Bottom",
              layoutDependency: layoutDependency,
              layoutId: "HY2E_q649",
              children: [
                /*#__PURE__*/ _jsxs(MotionDivWithFX, {
                  __framer__animate: { transition: transition3 },
                  __framer__animateOnce: true,
                  __framer__enter: animation,
                  __framer__styleAppearEffectEnabled: true,
                  __framer__threshold: 0.5,
                  __perspectiveFX: false,
                  __smartComponentFX: true,
                  __targetOpacity: 1,
                  className: "framer-1pxa9se",
                  "data-framer-name": "Numbers",
                  layoutDependency: layoutDependency,
                  layoutId: "zVK_oqsoo",
                  children: [
                    /*#__PURE__*/ _jsxs(motion.div, {
                      className: "framer-9umr1m",
                      "data-framer-name": "1",
                      layoutDependency: layoutDependency,
                      layoutId: "dP3Kb0gwr",
                      children: [
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-5jibgy",
                              "data-styles-preset": "DPl1XeZ47",
                              style: {
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--variable-reference-AM46op7Lx-jFWuJpyza))",
                              },
                              children: "+00%",
                            }),
                          }),
                          className: "framer-1cukkzp",
                          "data-framer-name": "+28%",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "VC4CuEL2y",
                          style: {
                            "--extracted-r6o4lv":
                              "var(--variable-reference-AM46op7Lx-jFWuJpyza)",
                            "--framer-paragraph-spacing": "0px",
                            "--variable-reference-AM46op7Lx-jFWuJpyza":
                              AM46op7Lx,
                          },
                          text: HZi8Dk5hs,
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-1hahlh8",
                              "data-styles-preset": "sw01V2bJD",
                              style: {
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--variable-reference-AM46op7Lx-jFWuJpyza))",
                              },
                              children: "01 description",
                            }),
                          }),
                          className: "framer-1x4w3rw",
                          "data-framer-name": "Customer retention",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "ZzPj1pnpR",
                          style: {
                            "--extracted-r6o4lv":
                              "var(--variable-reference-AM46op7Lx-jFWuJpyza)",
                            "--framer-paragraph-spacing": "0px",
                            "--variable-reference-AM46op7Lx-jFWuJpyza":
                              AM46op7Lx,
                            opacity: 0.6,
                          },
                          text: d4lzmm0YL,
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                      ],
                    }),
                    /*#__PURE__*/ _jsxs(motion.div, {
                      className: "framer-qmhx46",
                      "data-framer-name": "2",
                      layoutDependency: layoutDependency,
                      layoutId: "TPBFYWaH_",
                      children: [
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-5jibgy",
                              "data-styles-preset": "DPl1XeZ47",
                              style: {
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--variable-reference-AM46op7Lx-jFWuJpyza))",
                              },
                              children: "+00%",
                            }),
                          }),
                          className: "framer-1v6icbu",
                          "data-framer-name": "+61%",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "NrSNHJD42",
                          style: {
                            "--extracted-r6o4lv":
                              "var(--variable-reference-AM46op7Lx-jFWuJpyza)",
                            "--framer-paragraph-spacing": "0px",
                            "--variable-reference-AM46op7Lx-jFWuJpyza":
                              AM46op7Lx,
                          },
                          text: F9uW9JjKI,
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-1hahlh8",
                              "data-styles-preset": "sw01V2bJD",
                              style: {
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--variable-reference-AM46op7Lx-jFWuJpyza))",
                              },
                              children: "02 description",
                            }),
                          }),
                          className: "framer-1vxe87z",
                          "data-framer-name": "Conversion rate",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "IzKtHny8Z",
                          style: {
                            "--extracted-r6o4lv":
                              "var(--variable-reference-AM46op7Lx-jFWuJpyza)",
                            "--framer-paragraph-spacing": "0px",
                            "--variable-reference-AM46op7Lx-jFWuJpyza":
                              AM46op7Lx,
                            opacity: 0.6,
                          },
                          text: ZL3Q30CZC,
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                      ],
                    }),
                  ],
                }),
                /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-agmp4k",
                  "data-border": true,
                  "data-framer-name": "Author",
                  layoutDependency: layoutDependency,
                  layoutId: "O8SYmcIEa",
                  style: {
                    "--border-bottom-width": `${
                      VZf4KPRV3.borderBottomWidth ?? VZf4KPRV3.borderWidth
                    }px`,
                    "--border-color": VZf4KPRV3.borderColor,
                    "--border-left-width": `${
                      VZf4KPRV3.borderLeftWidth ?? VZf4KPRV3.borderWidth
                    }px`,
                    "--border-right-width": `${
                      VZf4KPRV3.borderRightWidth ?? VZf4KPRV3.borderWidth
                    }px`,
                    "--border-style": VZf4KPRV3.borderStyle,
                    "--border-top-width": `${
                      VZf4KPRV3.borderTopWidth ?? VZf4KPRV3.borderWidth
                    }px`,
                  },
                  children: [
                    /*#__PURE__*/ _jsx(Image, {
                      background: {
                        alt: "",
                        fit: "fill",
                        sizes: "44px",
                        ...toResponsiveImage(y8_auQFXP),
                        ...{ positionX: "center", positionY: "center" },
                      },
                      className: "framer-p5ewhc",
                      "data-framer-name": "image",
                      layoutDependency: layoutDependency,
                      layoutId: "IlZko4WFK",
                      style: {
                        borderBottomLeftRadius: 50,
                        borderBottomRightRadius: 50,
                        borderTopLeftRadius: 50,
                        borderTopRightRadius: 50,
                      },
                    }),
                    /*#__PURE__*/ _jsxs(motion.div, {
                      className: "framer-198z9l7",
                      "data-framer-name": "Name",
                      layoutDependency: layoutDependency,
                      layoutId: "Z17huBw_O",
                      children: [
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-jnye1g",
                              "data-styles-preset": "xNIXLfFSf",
                              style: {
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--variable-reference-AM46op7Lx-jFWuJpyza))",
                              },
                              children: "Name",
                            }),
                          }),
                          className: "framer-y3w5y6",
                          "data-framer-name": "Anna Karenina",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "BZwQtaazR",
                          style: {
                            "--extracted-r6o4lv":
                              "var(--variable-reference-AM46op7Lx-jFWuJpyza)",
                            "--framer-paragraph-spacing": "0px",
                            "--variable-reference-AM46op7Lx-jFWuJpyza":
                              AM46op7Lx,
                          },
                          text: qXDjeqRcY,
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                        /*#__PURE__*/ _jsx(RichText, {
                          __fromCanvasComponent: true,
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              className: "framer-styles-preset-1hahlh8",
                              "data-styles-preset": "sw01V2bJD",
                              style: {
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--variable-reference-AM46op7Lx-jFWuJpyza))",
                              },
                              children: "Occupation",
                            }),
                          }),
                          className: "framer-swhb0a",
                          "data-framer-name":
                            "Owner of a clothing E-commerce store",
                          fonts: ["Inter"],
                          layoutDependency: layoutDependency,
                          layoutId: "r9fOMI_KY",
                          style: {
                            "--extracted-r6o4lv":
                              "var(--variable-reference-AM46op7Lx-jFWuJpyza)",
                            "--framer-paragraph-spacing": "0px",
                            "--variable-reference-AM46op7Lx-jFWuJpyza":
                              AM46op7Lx,
                            opacity: 0.6,
                          },
                          text: V5EvMzZAA,
                          verticalAlignment: "top",
                          withExternalLayout: true,
                        }),
                      ],
                    }),
                  ],
                }),
              ],
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-lXGbj.framer-1y36xfz, .framer-lXGbj .framer-1y36xfz { display: block; }",
  ".framer-lXGbj.framer-1vlo0dx { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; height: 753px; justify-content: space-between; overflow: hidden; padding: 40px; position: relative; width: 267px; }",
  ".framer-lXGbj .framer-12mumlp { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
  ".framer-lXGbj .framer-8ykqw6 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 1px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
  ".framer-lXGbj .framer-1ir5b4p-container, .framer-lXGbj .framer-hlbcud-container, .framer-lXGbj .framer-11urm9k-container, .framer-lXGbj .framer-4c742-container, .framer-lXGbj .framer-134ikfa-container { flex: none; height: 13px; position: relative; width: 13px; }",
  ".framer-lXGbj .framer-zayyxm, .framer-lXGbj .framer-y3w5y6 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-lXGbj .framer-1jzmwku { flex: none; height: 40px; overflow: hidden; position: relative; width: 100%; }",
  ".framer-lXGbj .framer-s21afs { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-lXGbj .framer-1pxa9se { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 30px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-lXGbj .framer-9umr1m { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 30px 0px 0px; position: relative; width: min-content; }",
  ".framer-lXGbj .framer-1cukkzp, .framer-lXGbj .framer-1x4w3rw, .framer-lXGbj .framer-1v6icbu, .framer-lXGbj .framer-1vxe87z { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-lXGbj .framer-qmhx46 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-lXGbj .framer-agmp4k { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 26px 0px 0px 0px; position: relative; width: 100%; }",
  ".framer-lXGbj .framer-p5ewhc { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 44px); position: relative; width: 44px; }",
  ".framer-lXGbj .framer-198z9l7 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-lXGbj .framer-swhb0a { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-lXGbj .framer-12mumlp, .framer-lXGbj .framer-8ykqw6, .framer-lXGbj .framer-s21afs, .framer-lXGbj .framer-1pxa9se, .framer-lXGbj .framer-9umr1m, .framer-lXGbj .framer-qmhx46, .framer-lXGbj .framer-agmp4k, .framer-lXGbj .framer-198z9l7 { gap: 0px; } .framer-lXGbj .framer-12mumlp > * { margin: 0px; margin-bottom: calc(20px / 2); margin-top: calc(20px / 2); } .framer-lXGbj .framer-12mumlp > :first-child, .framer-lXGbj .framer-s21afs > :first-child, .framer-lXGbj .framer-9umr1m > :first-child, .framer-lXGbj .framer-qmhx46 > :first-child, .framer-lXGbj .framer-198z9l7 > :first-child { margin-top: 0px; } .framer-lXGbj .framer-12mumlp > :last-child, .framer-lXGbj .framer-s21afs > :last-child, .framer-lXGbj .framer-9umr1m > :last-child, .framer-lXGbj .framer-qmhx46 > :last-child, .framer-lXGbj .framer-198z9l7 > :last-child { margin-bottom: 0px; } .framer-lXGbj .framer-8ykqw6 > * { margin: 0px; margin-left: calc(1px / 2); margin-right: calc(1px / 2); } .framer-lXGbj .framer-8ykqw6 > :first-child, .framer-lXGbj .framer-1pxa9se > :first-child, .framer-lXGbj .framer-agmp4k > :first-child { margin-left: 0px; } .framer-lXGbj .framer-8ykqw6 > :last-child, .framer-lXGbj .framer-1pxa9se > :last-child, .framer-lXGbj .framer-agmp4k > :last-child { margin-right: 0px; } .framer-lXGbj .framer-s21afs > * { margin: 0px; margin-bottom: calc(40px / 2); margin-top: calc(40px / 2); } .framer-lXGbj .framer-1pxa9se > * { margin: 0px; margin-left: calc(30px / 2); margin-right: calc(30px / 2); } .framer-lXGbj .framer-9umr1m > *, .framer-lXGbj .framer-qmhx46 > * { margin: 0px; margin-bottom: calc(6px / 2); margin-top: calc(6px / 2); } .framer-lXGbj .framer-agmp4k > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } .framer-lXGbj .framer-198z9l7 > * { margin: 0px; margin-bottom: calc(4px / 2); margin-top: calc(4px / 2); } }",
  ".framer-lXGbj.framer-v-7my9cv.framer-1vlo0dx { padding: 30px; }",
  ".framer-lXGbj.framer-v-7my9cv .framer-1jzmwku { height: 130px; }",
  ".framer-lXGbj.framer-v-7my9cv .framer-s21afs { gap: 30px; }",
  ".framer-lXGbj.framer-v-7my9cv .framer-1pxa9se { gap: 20px; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-lXGbj.framer-v-7my9cv .framer-s21afs, .framer-lXGbj.framer-v-7my9cv .framer-1pxa9se { gap: 0px; } .framer-lXGbj.framer-v-7my9cv .framer-s21afs > * { margin: 0px; margin-bottom: calc(30px / 2); margin-top: calc(30px / 2); } .framer-lXGbj.framer-v-7my9cv .framer-s21afs > :first-child { margin-top: 0px; } .framer-lXGbj.framer-v-7my9cv .framer-s21afs > :last-child { margin-bottom: 0px; } .framer-lXGbj.framer-v-7my9cv .framer-1pxa9se > * { margin: 0px; margin-left: calc(20px / 2); margin-right: calc(20px / 2); } .framer-lXGbj.framer-v-7my9cv .framer-1pxa9se > :first-child { margin-left: 0px; } .framer-lXGbj.framer-v-7my9cv .framer-1pxa9se > :last-child { margin-right: 0px; } }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  ...sharedStyle2.css,
  ...sharedStyle3.css,
  '.framer-lXGbj[data-border="true"]::after, .framer-lXGbj [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 753
 * @framerIntrinsicWidth 267
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"p0HhGt1NQ":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"ysHGQbLqA":"testimonial","HZi8Dk5hs":"_01Number","d4lzmm0YL":"_01Description","F9uW9JjKI":"_02Number","ZL3Q30CZC":"_02Description","y8_auQFXP":"avatar","qXDjeqRcY":"name1","V5EvMzZAA":"occupation","jjg85LuOE":"starColor","AM46op7Lx":"textColor","DMTP3vKWw":"bGColor","VZf4KPRV3":"borderColor"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerjFWuJpyza = withCSS(Component, css, "framer-lXGbj");
export default FramerjFWuJpyza;
FramerjFWuJpyza.displayName = "Testimoials / Item";
FramerjFWuJpyza.defaultProps = { height: 753, width: 267 };
addPropertyControls(FramerjFWuJpyza, {
  variant: {
    options: ["WN0gvTTUg", "p0HhGt1NQ"],
    optionTitles: ["Desktop", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  ysHGQbLqA: {
    defaultValue: "Testimonial",
    description: "",
    displayTextArea: false,
    title: "Testimonial",
    type: ControlType.String,
  },
  HZi8Dk5hs: {
    defaultValue: "+00%",
    displayTextArea: false,
    title: "01 number",
    type: ControlType.String,
  },
  d4lzmm0YL: {
    defaultValue: "01 description",
    description: "",
    displayTextArea: false,
    title: "01 description",
    type: ControlType.String,
  },
  F9uW9JjKI: {
    defaultValue: "+00%",
    displayTextArea: false,
    title: "02 number",
    type: ControlType.String,
  },
  ZL3Q30CZC: {
    defaultValue: "02 description",
    description: "",
    displayTextArea: false,
    title: "02 description",
    type: ControlType.String,
  },
  y8_auQFXP: { title: "Avatar", type: ControlType.ResponsiveImage },
  qXDjeqRcY: {
    defaultValue: "Name",
    displayTextArea: false,
    title: "Name",
    type: ControlType.String,
  },
  V5EvMzZAA: {
    defaultValue: "Occupation",
    displayTextArea: false,
    title: "Occupation",
    type: ControlType.String,
  },
  jjg85LuOE: {
    defaultValue:
      'var(--token-1662617d-fd18-4319-b3da-aa36e5415705, rgb(249, 69, 45)) /* {"name":"Primary"} */',
    title: "Star color",
    type: ControlType.Color,
  },
  AM46op7Lx: {
    defaultValue:
      'var(--token-d74d16c5-23aa-4649-a2ad-0da8c936dade, rgb(255, 255, 255)) /* {"name":"White"} */',
    title: "Text color",
    type: ControlType.Color,
  },
  DMTP3vKWw: {
    defaultValue:
      'var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12)) /* {"name":"Black"} */',
    title: "BG color",
    type: ControlType.Color,
  },
  VZf4KPRV3: {
    defaultValue: {
      borderBottomWidth: 0,
      borderColor: "rgba(255, 255, 255, 0.2)",
      borderLeftWidth: 0,
      borderRightWidth: 0,
      borderStyle: "solid",
      borderTopWidth: 1,
    },
    title: "Border color",
    type: ControlType.Border,
  },
});
addFonts(
  FramerjFWuJpyza,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...PhosphorFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
    ...getFontsFromSharedStyle(sharedStyle2.fonts),
    ...getFontsFromSharedStyle(sharedStyle3.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerjFWuJpyza",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "267",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"p0HhGt1NQ":{"layout":["fixed","fixed"]}}}',
        framerVariables:
          '{"ysHGQbLqA":"testimonial","HZi8Dk5hs":"_01Number","d4lzmm0YL":"_01Description","F9uW9JjKI":"_02Number","ZL3Q30CZC":"_02Description","y8_auQFXP":"avatar","qXDjeqRcY":"name1","V5EvMzZAA":"occupation","jjg85LuOE":"starColor","AM46op7Lx":"textColor","DMTP3vKWw":"bGColor","VZf4KPRV3":"borderColor"}',
        framerDisplayContentsDiv: "false",
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "753",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
