// Generated by Framer (9805f18)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import Ticker from "https://framerusercontent.com/modules/B2xAlJLcN0gOnt11mSPw/plhC5PVnCMllW5QXjFK5/Ticker.js";
import CarouselItem from "https://framerusercontent.com/modules/Lp8P35k8SrervuX7pzj9/ha4DtTwv3iXo7tg3vaqD/kNP8cImIG.js";
const CarouselItemFonts = getFonts(CarouselItem);
const TickerFonts = getFonts(Ticker);
const cycleOrder = ["TyCkGq4e0", "JQZ30bDwJ"];
const serializationHash = "framer-wYLaT";
const variantClassNames = {
  JQZ30bDwJ: "framer-v-1l0olfg",
  TyCkGq4e0: "framer-v-10fhop6",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const addImageAlt = (image, alt) => {
  if (!image || typeof image !== "object") {
    return;
  }
  return { ...image, alt };
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Desktop: "TyCkGq4e0", Phone: "JQZ30bDwJ" };
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "TyCkGq4e0",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "TyCkGq4e0",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.section, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-10fhop6",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "TyCkGq4e0",
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            { JQZ30bDwJ: { "data-framer-name": "Phone" } },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
              className: "framer-10ctm3x-container",
              isAuthoredByUser: true,
              isModuleExternal: true,
              layoutDependency: layoutDependency,
              layoutId: "dc39UCPnr-container",
              nodeId: "dc39UCPnr",
              rendersWithMotion: true,
              scopeId: "fuxa0eFsG",
              children: /*#__PURE__*/ _jsx(Ticker, {
                alignment: "center",
                direction: "left",
                fadeOptions: {
                  fadeAlpha: 0,
                  fadeContent: false,
                  fadeInset: 0,
                  fadeWidth: 25,
                  overflow: false,
                },
                gap: 0,
                height: "100%",
                hoverFactor: 0.3,
                id: "dc39UCPnr",
                layoutId: "dc39UCPnr",
                padding: 0,
                paddingBottom: 0,
                paddingLeft: 0,
                paddingPerSide: false,
                paddingRight: 0,
                paddingTop: 0,
                sizingOptions: { heightType: false, widthType: true },
                slots: [
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 200,
                    width: "280px",
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-pob2ir-container",
                        inComponentSlot: true,
                        layoutDependency: layoutDependency,
                        layoutId: "CYw5IFaGt-container",
                        nodeId: "CYw5IFaGt",
                        rendersWithMotion: true,
                        scopeId: "fuxa0eFsG",
                        children: /*#__PURE__*/ _jsx(CarouselItem, {
                          height: "100%",
                          id: "CYw5IFaGt",
                          IiM01HZ0g: addImageAlt(
                            {
                              pixelHeight: 49,
                              pixelWidth: 73,
                              src: "https://framerusercontent.com/images/sTaxCLs7cqSjMGwmi2PWgDRgDWQ.svg?width=73&height=49",
                            },
                            ""
                          ),
                          layoutId: "CYw5IFaGt",
                          style: { height: "100%", width: "100%" },
                          width: "100%",
                        }),
                      }
                    ),
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 200,
                    width: "290px",
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-wxqo85-container",
                        inComponentSlot: true,
                        layoutDependency: layoutDependency,
                        layoutId: "k9wMrkBgh-container",
                        nodeId: "k9wMrkBgh",
                        rendersWithMotion: true,
                        scopeId: "fuxa0eFsG",
                        children: /*#__PURE__*/ _jsx(CarouselItem, {
                          height: "100%",
                          id: "k9wMrkBgh",
                          layoutId: "k9wMrkBgh",
                          style: { height: "100%", width: "100%" },
                          width: "100%",
                        }),
                      }
                    ),
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 200,
                    width: "290px",
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-v2b4js-container",
                        inComponentSlot: true,
                        layoutDependency: layoutDependency,
                        layoutId: "rycXxYZTD-container",
                        nodeId: "rycXxYZTD",
                        rendersWithMotion: true,
                        scopeId: "fuxa0eFsG",
                        children: /*#__PURE__*/ _jsx(CarouselItem, {
                          height: "100%",
                          id: "rycXxYZTD",
                          IiM01HZ0g: addImageAlt(
                            {
                              pixelHeight: 35,
                              pixelWidth: 132,
                              src: "https://framerusercontent.com/images/c3ZtmzD7MNgGgKP6Pt9WW2zXl0.svg?width=132&height=35",
                            },
                            ""
                          ),
                          layoutId: "rycXxYZTD",
                          style: { height: "100%", width: "100%" },
                          width: "100%",
                        }),
                      }
                    ),
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 200,
                    width: "290px",
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-1psmpno-container",
                        inComponentSlot: true,
                        layoutDependency: layoutDependency,
                        layoutId: "HjoTuRGOs-container",
                        nodeId: "HjoTuRGOs",
                        rendersWithMotion: true,
                        scopeId: "fuxa0eFsG",
                        children: /*#__PURE__*/ _jsx(CarouselItem, {
                          height: "100%",
                          id: "HjoTuRGOs",
                          IiM01HZ0g: addImageAlt(
                            {
                              pixelHeight: 35,
                              pixelWidth: 154,
                              src: "https://framerusercontent.com/images/hceoHFzb6OLlauC9G5LXKHf4fFY.svg?width=154&height=35",
                            },
                            ""
                          ),
                          layoutId: "HjoTuRGOs",
                          style: { height: "100%", width: "100%" },
                          width: "100%",
                        }),
                      }
                    ),
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 200,
                    width: "290px",
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-f7po0z-container",
                        inComponentSlot: true,
                        layoutDependency: layoutDependency,
                        layoutId: "h7vBRumze-container",
                        nodeId: "h7vBRumze",
                        rendersWithMotion: true,
                        scopeId: "fuxa0eFsG",
                        children: /*#__PURE__*/ _jsx(CarouselItem, {
                          height: "100%",
                          id: "h7vBRumze",
                          IiM01HZ0g: addImageAlt(
                            {
                              pixelHeight: 30,
                              pixelWidth: 78,
                              src: "https://framerusercontent.com/images/BjscHvGqTPWHtU57bAqZ2terODw.svg?width=78&height=30",
                            },
                            ""
                          ),
                          layoutId: "h7vBRumze",
                          style: { height: "100%", width: "100%" },
                          width: "100%",
                        }),
                      }
                    ),
                  }),
                ],
                speed: 70,
                style: { height: "100%", width: "100%" },
                width: "100%",
                ...addPropertyOverrides(
                  { JQZ30bDwJ: { speed: 80 } },
                  baseVariant,
                  gestureVariant
                ),
              }),
            }),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-wYLaT.framer-1h1rqwp, .framer-wYLaT .framer-1h1rqwp { display: block; }",
  ".framer-wYLaT.framer-10fhop6 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: 200px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1200px; }",
  ".framer-wYLaT .framer-10ctm3x-container { flex: 1 0 0px; height: 1px; position: relative; width: 100%; }",
  ".framer-wYLaT .framer-pob2ir-container { height: 200px; position: relative; width: 280px; }",
  ".framer-wYLaT .framer-wxqo85-container, .framer-wYLaT .framer-v2b4js-container, .framer-wYLaT .framer-1psmpno-container, .framer-wYLaT .framer-f7po0z-container { height: 200px; position: relative; width: 290px; }",
  ".framer-wYLaT.framer-v-1l0olfg.framer-10fhop6 { height: 160px; width: 380px; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 200
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"JQZ30bDwJ":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const Framerfuxa0eFsG = withCSS(Component, css, "framer-wYLaT");
export default Framerfuxa0eFsG;
Framerfuxa0eFsG.displayName = "Logo carousel";
Framerfuxa0eFsG.defaultProps = { height: 200, width: 1200 };
addPropertyControls(Framerfuxa0eFsG, {
  variant: {
    options: ["TyCkGq4e0", "JQZ30bDwJ"],
    optionTitles: ["Desktop", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(
  Framerfuxa0eFsG,
  [{ explicitInter: true, fonts: [] }, ...CarouselItemFonts, ...TickerFonts],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "Framerfuxa0eFsG",
      slots: [],
      annotations: {
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"JQZ30bDwJ":{"layout":["fixed","fixed"]}}}',
        framerIntrinsicWidth: "1200",
        framerIntrinsicHeight: "200",
        framerComponentViewportWidth: "true",
        framerDisplayContentsDiv: "false",
        framerImmutableVariables: "true",
        framerAutoSizeImages: "true",
        framerContractVersion: "1",
        framerColorSyntax: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./fuxa0eFsG.map
