// Generated by Framer (4ba8877)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getLoadingLazyAtYPosition,
  Image,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
const serializationHash = "framer-rM7zh";
const variantClassNames = { BbNvF7zfL: "framer-v-1udtjmn" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) => variant && Object.assign(nextOverrides, overrides[variant])
      );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition =
    value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, logo, width, ...props }) => {
  var _ref;
  return {
    ...props,
    IiM01HZ0g:
      (_ref = logo !== null && logo !== void 0 ? logo : props.IiM01HZ0g) !==
        null && _ref !== void 0
        ? _ref
        : {
            src: "https://framerusercontent.com/images/haNVbcSIbfVRCcLU0UxDtMQWaQk.svg",
          },
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, IiM01HZ0g, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "BbNvF7zfL",
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            serializationHash,
            ...sharedStyleClassNames,
            "framer-1udtjmn",
            className,
            classNames
          ),
          "data-border": true,
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "BbNvF7zfL",
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: {
            "--border-bottom-width": "1px",
            "--border-color": "rgb(224, 224, 224)",
            "--border-left-width": "1px",
            "--border-right-width": "0px",
            "--border-style": "solid",
            "--border-top-width": "1px",
            backgroundColor: "rgb(255, 255, 255)",
            ...style,
          },
          children: /*#__PURE__*/ _jsx(Image, {
            background: {
              alt: "",
              fit: "fit",
              loading: getLoadingLazyAtYPosition(
                ((componentViewport === null || componentViewport === void 0
                  ? void 0
                  : componentViewport.y) || 0) +
                  0 +
                  ((((componentViewport === null || componentViewport === void 0
                    ? void 0
                    : componentViewport.height) || 200) -
                    0 -
                    ((((componentViewport === null ||
                    componentViewport === void 0
                      ? void 0
                      : componentViewport.height) || 200) -
                      0) *
                      0.4 +
                      0)) /
                    2 +
                    0 +
                    0)
              ),
              pixelHeight: 51,
              pixelWidth: 100,
              sizes: "116px",
              ...toResponsiveImage(IiM01HZ0g),
              ...{ positionX: "center", positionY: "center" },
            },
            className: "framer-46623r",
            layoutDependency: layoutDependency,
            layoutId: "EgPSYyOAm",
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-rM7zh.framer-821ky2, .framer-rM7zh .framer-821ky2 { display: block; }",
  ".framer-rM7zh.framer-1udtjmn { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 200px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 290px; }",
  ".framer-rM7zh .framer-46623r { aspect-ratio: 1.45 / 1; flex: none; height: 40%; overflow: visible; position: relative; width: var(--framer-aspect-ratio-supported, 116px); }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-rM7zh.framer-1udtjmn { gap: 0px; } .framer-rM7zh.framer-1udtjmn > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-rM7zh.framer-1udtjmn > :first-child { margin-top: 0px; } .framer-rM7zh.framer-1udtjmn > :last-child { margin-bottom: 0px; } }",
  '.framer-rM7zh[data-border="true"]::after, .framer-rM7zh [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 200
 * @framerIntrinsicWidth 290
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"IiM01HZ0g":"logo"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerkNP8cImIG = withCSS(Component, css, "framer-rM7zh");
export default FramerkNP8cImIG;
FramerkNP8cImIG.displayName = "Carousel / Item";
FramerkNP8cImIG.defaultProps = { height: 200, width: 290 };
addPropertyControls(FramerkNP8cImIG, {
  IiM01HZ0g: {
    __defaultAssetReference:
      "data:framer/asset-reference,haNVbcSIbfVRCcLU0UxDtMQWaQk.svg?originalFilename=Logo-1.svg&preferredSize=auto",
    title: "Logo",
    type: ControlType.ResponsiveImage,
  },
});
addFonts(FramerkNP8cImIG, [{ explicitInter: true, fonts: [] }], {
  supportsExplicitInterCodegen: true,
});
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerkNP8cImIG",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerIntrinsicWidth: "290",
        framerDisplayContentsDiv: "false",
        framerImmutableVariables: "true",
        framerIntrinsicHeight: "200",
        framerVariables: '{"IiM01HZ0g":"logo"}',
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}',
        framerComponentViewportWidth: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./kNP8cImIG.map
