// Generated by Framer (51f36d1)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/99CfbQ0g2aHd3wkMunJ6/y1C7t0UV7hgBOIy2DUxd/q35quwzCc.js";
import * as sharedStyle1 from "https://framerusercontent.com/modules/oMgXPBeR6YdHTzKPyOpl/EoE1kmmGpZHB3Wts7nST/xNIXLfFSf.js";
const cycleOrder = ["CDUX1cafN", "hRqDeEG5n", "av8V5mmCT"];
const serializationHash = "framer-3A3JQ";
const variantClassNames = {
  av8V5mmCT: "framer-v-1lis3j0",
  CDUX1cafN: "framer-v-wavkwm",
  hRqDeEG5n: "framer-v-n12fgo",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) => variant && Object.assign(nextOverrides, overrides[variant])
      );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition =
    value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  Desktop: "CDUX1cafN",
  Phone: "av8V5mmCT",
  Tablet: "hRqDeEG5n",
};
const getProps = ({
  award,
  description,
  height,
  id,
  width,
  year,
  ...props
}) => {
  var _ref, _ref1, _humanReadableVariantMap_props_variant, _ref2, _ref3;
  return {
    ...props,
    bErBe5H4z:
      (_ref =
        description !== null && description !== void 0
          ? description
          : props.bErBe5H4z) !== null && _ref !== void 0
        ? _ref
        : "Description",
    MOB6dpNMz:
      (_ref1 = year !== null && year !== void 0 ? year : props.MOB6dpNMz) !==
        null && _ref1 !== void 0
        ? _ref1
        : "Year",
    variant:
      (_ref2 =
        (_humanReadableVariantMap_props_variant =
          humanReadableVariantMap[props.variant]) !== null &&
        _humanReadableVariantMap_props_variant !== void 0
          ? _humanReadableVariantMap_props_variant
          : props.variant) !== null && _ref2 !== void 0
        ? _ref2
        : "CDUX1cafN",
    zA_NBZabd:
      (_ref3 = award !== null && award !== void 0 ? award : props.zA_NBZabd) !==
        null && _ref3 !== void 0
        ? _ref3
        : "Award",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const {
    style,
    className,
    layoutId,
    variant,
    zA_NBZabd,
    bErBe5H4z,
    MOB6dpNMz,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "CDUX1cafN",
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            serializationHash,
            ...sharedStyleClassNames,
            "framer-wavkwm",
            className,
            classNames
          ),
          "data-border": true,
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "CDUX1cafN",
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: {
            "--border-bottom-width": "0px",
            "--border-color": "rgb(222, 222, 222)",
            "--border-left-width": "0px",
            "--border-right-width": "0px",
            "--border-style": "solid",
            "--border-top-width": "1px",
            ...style,
          },
          ...addPropertyOverrides(
            {
              av8V5mmCT: { "data-framer-name": "Phone" },
              hRqDeEG5n: { "data-framer-name": "Tablet" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-17ohvjt",
              "data-framer-name": "Award",
              layoutDependency: layoutDependency,
              layoutId: "QNG5eixeh",
              children: /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-1dmjd5e",
                    "data-styles-preset": "q35quwzCc",
                    style: {
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12)))",
                    },
                    children: "Award",
                  }),
                }),
                className: "framer-1g87hpv",
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "eAECb2ic9",
                style: {
                  "--extracted-r6o4lv":
                    "var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12))",
                  "--framer-paragraph-spacing": "0px",
                },
                text: zA_NBZabd,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
            }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-10ntpjo",
              "data-framer-name": "Description",
              layoutDependency: layoutDependency,
              layoutId: "jpb6A99Oz",
              children: /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-jnye1g",
                    "data-styles-preset": "xNIXLfFSf",
                    style: {
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12)))",
                    },
                    children:
                      "Recognized for excellence in web design and functionality.",
                  }),
                }),
                className: "framer-u53231",
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "S0V0oMCBp",
                style: {
                  "--extracted-r6o4lv":
                    "var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12))",
                  "--framer-paragraph-spacing": "0px",
                  opacity: 0.6,
                },
                text: bErBe5H4z,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
            }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-1w1lmsb",
              "data-framer-name": "Year",
              layoutDependency: layoutDependency,
              layoutId: "enRPEYwR1",
              children: /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    className: "framer-styles-preset-jnye1g",
                    "data-styles-preset": "xNIXLfFSf",
                    style: {
                      "--framer-text-alignment": "right",
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12)))",
                    },
                    children: "2023",
                  }),
                }),
                className: "framer-46ubzg",
                fonts: ["Inter"],
                layoutDependency: layoutDependency,
                layoutId: "Hjqj_KdiV",
                style: {
                  "--extracted-r6o4lv":
                    "var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12))",
                  "--framer-paragraph-spacing": "0px",
                },
                text: MOB6dpNMz,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-3A3JQ.framer-1t5lt7w, .framer-3A3JQ .framer-1t5lt7w { display: block; }",
  ".framer-3A3JQ.framer-wavkwm { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 30px 0px 30px 0px; position: relative; width: 841px; }",
  ".framer-3A3JQ .framer-17ohvjt { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 33%; }",
  ".framer-3A3JQ .framer-1g87hpv, .framer-3A3JQ .framer-u53231, .framer-3A3JQ .framer-46ubzg { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  ".framer-3A3JQ .framer-10ntpjo { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 40%; }",
  ".framer-3A3JQ .framer-1w1lmsb { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-3A3JQ.framer-wavkwm, .framer-3A3JQ .framer-17ohvjt, .framer-3A3JQ .framer-10ntpjo, .framer-3A3JQ .framer-1w1lmsb { gap: 0px; } .framer-3A3JQ.framer-wavkwm > *, .framer-3A3JQ .framer-17ohvjt > *, .framer-3A3JQ .framer-10ntpjo > *, .framer-3A3JQ .framer-1w1lmsb > * { margin: 0px; margin-left: calc(20px / 2); margin-right: calc(20px / 2); } .framer-3A3JQ.framer-wavkwm > :first-child, .framer-3A3JQ .framer-17ohvjt > :first-child, .framer-3A3JQ .framer-10ntpjo > :first-child, .framer-3A3JQ .framer-1w1lmsb > :first-child { margin-left: 0px; } .framer-3A3JQ.framer-wavkwm > :last-child, .framer-3A3JQ .framer-17ohvjt > :last-child, .framer-3A3JQ .framer-10ntpjo > :last-child, .framer-3A3JQ .framer-1w1lmsb > :last-child { margin-right: 0px; } }",
  ".framer-3A3JQ.framer-v-n12fgo.framer-wavkwm { padding: 26px 0px 26px 0px; width: 810px; }",
  ".framer-3A3JQ.framer-v-1lis3j0.framer-wavkwm { padding: 22px 0px 22px 0px; width: 810px; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  '.framer-3A3JQ[data-border="true"]::after, .framer-3A3JQ [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 89
 * @framerIntrinsicWidth 841
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"hRqDeEG5n":{"layout":["fixed","auto"]},"av8V5mmCT":{"layout":["fixed","auto"]}}}
 * @framerVariables {"zA_NBZabd":"award","bErBe5H4z":"description","MOB6dpNMz":"year"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerCuP3Vk0Vy = withCSS(Component, css, "framer-3A3JQ");
export default FramerCuP3Vk0Vy;
FramerCuP3Vk0Vy.displayName = "About / Award";
FramerCuP3Vk0Vy.defaultProps = { height: 89, width: 841 };
addPropertyControls(FramerCuP3Vk0Vy, {
  variant: {
    options: ["CDUX1cafN", "hRqDeEG5n", "av8V5mmCT"],
    optionTitles: ["Desktop", "Tablet", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  zA_NBZabd: {
    defaultValue: "Award",
    displayTextArea: false,
    title: "Award",
    type: ControlType.String,
  },
  bErBe5H4z: {
    defaultValue: "Description",
    displayTextArea: false,
    title: "Description",
    type: ControlType.String,
  },
  MOB6dpNMz: {
    defaultValue: "Year",
    displayTextArea: false,
    title: "Year",
    type: ControlType.String,
  },
});
addFonts(
  FramerCuP3Vk0Vy,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerCuP3Vk0Vy",
      slots: [],
      annotations: {
        framerIntrinsicWidth: "841",
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"hRqDeEG5n":{"layout":["fixed","auto"]},"av8V5mmCT":{"layout":["fixed","auto"]}}}',
        framerIntrinsicHeight: "89",
        framerContractVersion: "1",
        framerDisplayContentsDiv: "false",
        framerComponentViewportWidth: "true",
        framerVariables:
          '{"zA_NBZabd":"award","bErBe5H4z":"description","MOB6dpNMz":"year"}',
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./CuP3Vk0Vy.map
