// Generated by Framer (915daba)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { Icon as Phosphor } from "https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/p8dptk4UIND8hbFWz9V7/Phosphor.js";
const PhosphorFonts = getFonts(Phosphor);
const MotionDivWithFX = withFX(motion.div);
const enabledGestures = { N7occpFv7: { hover: true } };
const cycleOrder = ["N7occpFv7", "JMfIg1YyM", "gD6dV4Fd9"];
const serializationHash = "framer-vwGhK";
const variantClassNames = {
  gD6dV4Fd9: "framer-v-zgfi5d",
  JMfIg1YyM: "framer-v-f41qhn",
  N7occpFv7: "framer-v-cdv263",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const transition2 = {
  delay: 0,
  duration: 1,
  ease: [0, 0, 1, 1],
  type: "tween",
};
const animation = {
  opacity: 1,
  rotate: 360,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  Default: "N7occpFv7",
  Loading: "JMfIg1YyM",
  Success: "gD6dV4Fd9",
};
const getProps = ({ arrowColor, background, height, id, width, ...props }) => {
  return {
    ...props,
    bMNsf2NqD:
      background ??
      props.bMNsf2NqD ??
      "var(--token-1662617d-fd18-4319-b3da-aa36e5415705, rgb(249, 69, 45))",
    fidKvx1aA:
      arrowColor ??
      props.fidKvx1aA ??
      "var(--token-d74d16c5-23aa-4649-a2ad-0da8c936dade, rgb(255, 255, 255))",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "N7occpFv7",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const {
    style,
    className,
    layoutId,
    variant,
    bMNsf2NqD,
    fidKvx1aA,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "N7occpFv7",
    enabledGestures,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const ref1 = React.useRef(null);
  const isDisplayed = () => {
    if (baseVariant === "JMfIg1YyM") return false;
    return true;
  };
  const isDisplayed1 = () => {
    if (baseVariant === "JMfIg1YyM") return true;
    return false;
  };
  const defaultLayoutId = React.useId();
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.button, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-cdv263",
            className,
            classNames
          ),
          "data-framer-name": "Default",
          "data-reset": "button",
          layoutDependency: layoutDependency,
          layoutId: "N7occpFv7",
          ref: ref ?? ref1,
          style: {
            backgroundColor: bMNsf2NqD,
            borderBottomLeftRadius: "100%",
            borderBottomRightRadius: "100%",
            borderTopLeftRadius: "100%",
            borderTopRightRadius: "100%",
            ...style,
          },
          variants: {
            "N7occpFv7-hover": {
              backgroundColor:
                "var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12))",
            },
          },
          ...addPropertyOverrides(
            {
              "N7occpFv7-hover": { "data-framer-name": undefined },
              gD6dV4Fd9: { "data-framer-name": "Success" },
              JMfIg1YyM: { "data-framer-name": "Loading" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            isDisplayed() &&
              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                  className: "framer-1gio8xn-container",
                  isAuthoredByUser: true,
                  isModuleExternal: true,
                  layoutDependency: layoutDependency,
                  layoutId: "K3_x6aIn5-container",
                  nodeId: "K3_x6aIn5",
                  rendersWithMotion: true,
                  scopeId: "MtwLtlNi4",
                  children: /*#__PURE__*/ _jsx(Phosphor, {
                    color: fidKvx1aA,
                    height: "100%",
                    iconSearch: "arrow-right",
                    iconSelection: "House",
                    id: "K3_x6aIn5",
                    layoutId: "K3_x6aIn5",
                    mirrored: false,
                    selectByList: false,
                    style: { height: "100%", width: "100%" },
                    weight: "bold",
                    width: "100%",
                    ...addPropertyOverrides(
                      { gD6dV4Fd9: { iconSearch: "check" } },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                }),
              }),
            isDisplayed1() &&
              /*#__PURE__*/ _jsx(MotionDivWithFX, {
                __framer__loop: animation,
                __framer__loopEffectEnabled: true,
                __framer__loopRepeatDelay: 0,
                __framer__loopRepeatType: "loop",
                __framer__loopTransition: transition2,
                __perspectiveFX: false,
                __smartComponentFX: true,
                __targetOpacity: 1,
                className: "framer-1n7d58z",
                "data-framer-name": "Conic",
                layoutDependency: layoutDependency,
                layoutId: "ff8qY_FEs",
                style: {
                  background:
                    "conic-gradient(from 0deg at 50% 50%, rgba(255, 255, 255, 0) 7.208614864864882deg, rgb(255, 255, 255) 342deg)",
                  mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
                  WebkitMask:
                    "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
                },
                children: /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-1e1951r",
                  "data-framer-name": "Rounding",
                  layoutDependency: layoutDependency,
                  layoutId: "a7NOqL816",
                  style: {
                    backgroundColor: "rgb(255, 255, 255)",
                    borderBottomLeftRadius: 1,
                    borderBottomRightRadius: 1,
                    borderTopLeftRadius: 1,
                    borderTopRightRadius: 1,
                  },
                  transformTemplate: transformTemplate1,
                }),
              }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-vwGhK.framer-16fovvl, .framer-vwGhK .framer-16fovvl { display: block; }",
  ".framer-vwGhK.framer-cdv263 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: 27px; justify-content: center; padding: 0px; position: relative; width: 27px; }",
  ".framer-vwGhK .framer-1gio8xn-container { flex: none; height: 13px; position: relative; width: 15px; }",
  ".framer-vwGhK .framer-1n7d58z { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 17px); overflow: hidden; position: relative; width: 17px; }",
  ".framer-vwGhK .framer-1e1951r { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 2px); left: 50%; overflow: visible; position: absolute; top: 0px; width: 2px; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-vwGhK.framer-cdv263 { gap: 0px; } .framer-vwGhK.framer-cdv263 > * { margin: 0px; margin-left: calc(20px / 2); margin-right: calc(20px / 2); } .framer-vwGhK.framer-cdv263 > :first-child { margin-left: 0px; } .framer-vwGhK.framer-cdv263 > :last-child { margin-right: 0px; } }",
  ".framer-vwGhK.framer-v-f41qhn.framer-cdv263, .framer-vwGhK.framer-v-zgfi5d.framer-cdv263 { aspect-ratio: 1 / 1; cursor: unset; height: var(--framer-aspect-ratio-supported, 27px); }",
  ".framer-vwGhK.framer-v-cdv263.hover.framer-cdv263 { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 27px); }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 27
 * @framerIntrinsicWidth 27
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"JMfIg1YyM":{"layout":["fixed","fixed"]},"gD6dV4Fd9":{"layout":["fixed","fixed"]},"LEihD9csV":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"bMNsf2NqD":"background","fidKvx1aA":"arrowColor"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerMtwLtlNi4 = withCSS(Component, css, "framer-vwGhK");
export default FramerMtwLtlNi4;
FramerMtwLtlNi4.displayName = "Footer / Submit";
FramerMtwLtlNi4.defaultProps = { height: 27, width: 27 };
addPropertyControls(FramerMtwLtlNi4, {
  variant: {
    options: ["N7occpFv7", "JMfIg1YyM", "gD6dV4Fd9"],
    optionTitles: ["Default", "Loading", "Success"],
    title: "Variant",
    type: ControlType.Enum,
  },
  bMNsf2NqD: {
    defaultValue:
      'var(--token-1662617d-fd18-4319-b3da-aa36e5415705, rgb(249, 69, 45)) /* {"name":"Primary"} */',
    title: "Background",
    type: ControlType.Color,
  },
  fidKvx1aA: {
    defaultValue:
      'var(--token-d74d16c5-23aa-4649-a2ad-0da8c936dade, rgb(255, 255, 255)) /* {"name":"White"} */',
    title: "Arrow color",
    type: ControlType.Color,
  },
});
addFonts(
  FramerMtwLtlNi4,
  [{ explicitInter: true, fonts: [] }, ...PhosphorFonts],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerMtwLtlNi4",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerVariables: '{"bMNsf2NqD":"background","fidKvx1aA":"arrowColor"}',
        framerIntrinsicWidth: "27",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"JMfIg1YyM":{"layout":["fixed","fixed"]},"gD6dV4Fd9":{"layout":["fixed","fixed"]},"LEihD9csV":{"layout":["fixed","fixed"]}}}',
        framerComponentViewportWidth: "true",
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "27",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./MtwLtlNi4.map
