// Generated by Framer (0847096)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getLoadingLazyAtYPosition,
  Image,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
const cycleOrder = ["UMGTZZ0f6", "jMWPy6G8Y"];
const serializationHash = "framer-sT1mY";
const variantClassNames = {
  jMWPy6G8Y: "framer-v-1vpmlft",
  UMGTZZ0f6: "framer-v-t5m6nn",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) => variant && Object.assign(nextOverrides, overrides[variant])
      );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
const transformTemplate2 = (_, t) => `translate(-50%, -50%) ${t}`;
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition =
    value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Desktop: "UMGTZZ0f6", Phone: "jMWPy6G8Y" };
const getProps = ({
  amount,
  bGColor,
  border,
  height,
  id,
  image1,
  image2,
  image3,
  image4,
  width,
  ...props
}) => {
  var _ref,
    _ref1,
    _ref2,
    _ref3,
    _ref4,
    _ref5,
    _humanReadableVariantMap_props_variant,
    _ref6,
    _ref7;
  return {
    ...props,
    dGWMhyRCs:
      (_ref =
        image1 !== null && image1 !== void 0 ? image1 : props.dGWMhyRCs) !==
        null && _ref !== void 0
        ? _ref
        : {
            src: "https://framerusercontent.com/images/Qx5yBzgjmhI4ZhyOxhgNHDX4L5s.png",
          },
    fwD6acpNS:
      (_ref1 =
        image3 !== null && image3 !== void 0 ? image3 : props.fwD6acpNS) !==
        null && _ref1 !== void 0
        ? _ref1
        : {
            src: "https://framerusercontent.com/images/zfw44Zk0QT7qeSVw95UW4nDofo.png",
          },
    H0Oo1Mfv9:
      (_ref2 =
        image2 !== null && image2 !== void 0 ? image2 : props.H0Oo1Mfv9) !==
        null && _ref2 !== void 0
        ? _ref2
        : {
            src: "https://framerusercontent.com/images/GQOltmsmeeYSsbHJ9ijpOx0M.png",
          },
    IYnqoNnsD:
      (_ref3 =
        amount !== null && amount !== void 0 ? amount : props.IYnqoNnsD) !==
        null && _ref3 !== void 0
        ? _ref3
        : "20+",
    K01rPaGiO:
      (_ref4 =
        bGColor !== null && bGColor !== void 0 ? bGColor : props.K01rPaGiO) !==
        null && _ref4 !== void 0
        ? _ref4
        : "var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12))",
    RDM7oqG69:
      (_ref5 =
        border !== null && border !== void 0 ? border : props.RDM7oqG69) !==
        null && _ref5 !== void 0
        ? _ref5
        : {
            borderColor: "rgba(255, 255, 255, 1)",
            borderStyle: "solid",
            borderWidth: 3,
          },
    variant:
      (_ref6 =
        (_humanReadableVariantMap_props_variant =
          humanReadableVariantMap[props.variant]) !== null &&
        _humanReadableVariantMap_props_variant !== void 0
          ? _humanReadableVariantMap_props_variant
          : props.variant) !== null && _ref6 !== void 0
        ? _ref6
        : "UMGTZZ0f6",
    vNAo0sswR:
      (_ref7 =
        image4 !== null && image4 !== void 0 ? image4 : props.vNAo0sswR) !==
        null && _ref7 !== void 0
        ? _ref7
        : {
            src: "https://framerusercontent.com/images/tgyIqFImxk9E0TkgTI36r0dsss.png",
          },
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const {
    style,
    className,
    layoutId,
    variant,
    dGWMhyRCs,
    H0Oo1Mfv9,
    fwD6acpNS,
    vNAo0sswR,
    RDM7oqG69,
    IYnqoNnsD,
    K01rPaGiO,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "UMGTZZ0f6",
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  var _RDM7oqG69_borderBottomWidth,
    _RDM7oqG69_borderLeftWidth,
    _RDM7oqG69_borderRightWidth,
    _RDM7oqG69_borderTopWidth,
    _RDM7oqG69_borderBottomWidth1,
    _RDM7oqG69_borderLeftWidth1,
    _RDM7oqG69_borderRightWidth1,
    _RDM7oqG69_borderTopWidth1,
    _RDM7oqG69_borderBottomWidth2,
    _RDM7oqG69_borderLeftWidth2,
    _RDM7oqG69_borderRightWidth2,
    _RDM7oqG69_borderTopWidth2,
    _RDM7oqG69_borderBottomWidth3,
    _RDM7oqG69_borderLeftWidth3,
    _RDM7oqG69_borderRightWidth3,
    _RDM7oqG69_borderTopWidth3;
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            serializationHash,
            ...sharedStyleClassNames,
            "framer-t5m6nn",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "UMGTZZ0f6",
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: { ...style },
          ...addPropertyOverrides(
            { jMWPy6G8Y: { "data-framer-name": "Phone" } },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(Image, {
              background: {
                alt: "",
                fit: "stretch",
                loading: getLoadingLazyAtYPosition(
                  ((componentViewport === null || componentViewport === void 0
                    ? void 0
                    : componentViewport.y) || 0) +
                    (((componentViewport === null ||
                    componentViewport === void 0
                      ? void 0
                      : componentViewport.height) || 65) *
                      0.49230769230769256 -
                      27)
                ),
                sizes: "54px",
                ...toResponsiveImage(dGWMhyRCs),
                ...{ positionX: "center", positionY: "center" },
              },
              className: "framer-1ju8bs4",
              "data-border": true,
              "data-framer-name": "1",
              layoutDependency: layoutDependency,
              layoutId: "h_zTsEiaq",
              style: {
                "--border-bottom-width": `${
                  (_RDM7oqG69_borderBottomWidth =
                    RDM7oqG69.borderBottomWidth) !== null &&
                  _RDM7oqG69_borderBottomWidth !== void 0
                    ? _RDM7oqG69_borderBottomWidth
                    : RDM7oqG69.borderWidth
                }px`,
                "--border-color": RDM7oqG69.borderColor,
                "--border-left-width": `${
                  (_RDM7oqG69_borderLeftWidth = RDM7oqG69.borderLeftWidth) !==
                    null && _RDM7oqG69_borderLeftWidth !== void 0
                    ? _RDM7oqG69_borderLeftWidth
                    : RDM7oqG69.borderWidth
                }px`,
                "--border-right-width": `${
                  (_RDM7oqG69_borderRightWidth = RDM7oqG69.borderRightWidth) !==
                    null && _RDM7oqG69_borderRightWidth !== void 0
                    ? _RDM7oqG69_borderRightWidth
                    : RDM7oqG69.borderWidth
                }px`,
                "--border-style": RDM7oqG69.borderStyle,
                "--border-top-width": `${
                  (_RDM7oqG69_borderTopWidth = RDM7oqG69.borderTopWidth) !==
                    null && _RDM7oqG69_borderTopWidth !== void 0
                    ? _RDM7oqG69_borderTopWidth
                    : RDM7oqG69.borderWidth
                }px`,
                borderBottomLeftRadius: "100%",
                borderBottomRightRadius: "100%",
                borderTopLeftRadius: "100%",
                borderTopRightRadius: "100%",
              },
              transformTemplate: transformTemplate1,
              ...addPropertyOverrides(
                {
                  jMWPy6G8Y: {
                    background: {
                      alt: "",
                      fit: "stretch",
                      loading: getLoadingLazyAtYPosition(
                        ((componentViewport === null ||
                        componentViewport === void 0
                          ? void 0
                          : componentViewport.y) || 0) +
                          (((componentViewport === null ||
                          componentViewport === void 0
                            ? void 0
                            : componentViewport.height) || 48) *
                            0.49230769230769256 -
                            23)
                      ),
                      sizes: "46px",
                      ...toResponsiveImage(dGWMhyRCs),
                      ...{ positionX: "center", positionY: "center" },
                    },
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
            /*#__PURE__*/ _jsx(Image, {
              background: {
                alt: "",
                fit: "stretch",
                loading: getLoadingLazyAtYPosition(
                  ((componentViewport === null || componentViewport === void 0
                    ? void 0
                    : componentViewport.y) || 0) +
                    (((componentViewport === null ||
                    componentViewport === void 0
                      ? void 0
                      : componentViewport.height) || 65) *
                      0.49230769230769256 -
                      27)
                ),
                sizes: "54px",
                ...toResponsiveImage(H0Oo1Mfv9),
                ...{ positionX: "center", positionY: "center" },
              },
              className: "framer-h0yyxg",
              "data-border": true,
              "data-framer-name": "2",
              layoutDependency: layoutDependency,
              layoutId: "h3z5cl5hy",
              style: {
                "--border-bottom-width": `${
                  (_RDM7oqG69_borderBottomWidth1 =
                    RDM7oqG69.borderBottomWidth) !== null &&
                  _RDM7oqG69_borderBottomWidth1 !== void 0
                    ? _RDM7oqG69_borderBottomWidth1
                    : RDM7oqG69.borderWidth
                }px`,
                "--border-color": RDM7oqG69.borderColor,
                "--border-left-width": `${
                  (_RDM7oqG69_borderLeftWidth1 = RDM7oqG69.borderLeftWidth) !==
                    null && _RDM7oqG69_borderLeftWidth1 !== void 0
                    ? _RDM7oqG69_borderLeftWidth1
                    : RDM7oqG69.borderWidth
                }px`,
                "--border-right-width": `${
                  (_RDM7oqG69_borderRightWidth1 =
                    RDM7oqG69.borderRightWidth) !== null &&
                  _RDM7oqG69_borderRightWidth1 !== void 0
                    ? _RDM7oqG69_borderRightWidth1
                    : RDM7oqG69.borderWidth
                }px`,
                "--border-style": RDM7oqG69.borderStyle,
                "--border-top-width": `${
                  (_RDM7oqG69_borderTopWidth1 = RDM7oqG69.borderTopWidth) !==
                    null && _RDM7oqG69_borderTopWidth1 !== void 0
                    ? _RDM7oqG69_borderTopWidth1
                    : RDM7oqG69.borderWidth
                }px`,
                borderBottomLeftRadius: "100%",
                borderBottomRightRadius: "100%",
                borderTopLeftRadius: "100%",
                borderTopRightRadius: "100%",
              },
              transformTemplate: transformTemplate1,
              ...addPropertyOverrides(
                {
                  jMWPy6G8Y: {
                    background: {
                      alt: "",
                      fit: "stretch",
                      loading: getLoadingLazyAtYPosition(
                        ((componentViewport === null ||
                        componentViewport === void 0
                          ? void 0
                          : componentViewport.y) || 0) +
                          (((componentViewport === null ||
                          componentViewport === void 0
                            ? void 0
                            : componentViewport.height) || 48) *
                            0.49230769230769256 -
                            23)
                      ),
                      sizes: "46px",
                      ...toResponsiveImage(H0Oo1Mfv9),
                      ...{ positionX: "center", positionY: "center" },
                    },
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
            /*#__PURE__*/ _jsx(Image, {
              background: {
                alt: "",
                fit: "stretch",
                loading: getLoadingLazyAtYPosition(
                  ((componentViewport === null || componentViewport === void 0
                    ? void 0
                    : componentViewport.y) || 0) +
                    (((componentViewport === null ||
                    componentViewport === void 0
                      ? void 0
                      : componentViewport.height) || 65) *
                      0.49230769230769256 -
                      27)
                ),
                sizes: "54px",
                ...toResponsiveImage(fwD6acpNS),
                ...{ positionX: "center", positionY: "center" },
              },
              className: "framer-yr5zjy",
              "data-border": true,
              "data-framer-name": "3",
              layoutDependency: layoutDependency,
              layoutId: "wPzNxeigp",
              style: {
                "--border-bottom-width": `${
                  (_RDM7oqG69_borderBottomWidth2 =
                    RDM7oqG69.borderBottomWidth) !== null &&
                  _RDM7oqG69_borderBottomWidth2 !== void 0
                    ? _RDM7oqG69_borderBottomWidth2
                    : RDM7oqG69.borderWidth
                }px`,
                "--border-color": RDM7oqG69.borderColor,
                "--border-left-width": `${
                  (_RDM7oqG69_borderLeftWidth2 = RDM7oqG69.borderLeftWidth) !==
                    null && _RDM7oqG69_borderLeftWidth2 !== void 0
                    ? _RDM7oqG69_borderLeftWidth2
                    : RDM7oqG69.borderWidth
                }px`,
                "--border-right-width": `${
                  (_RDM7oqG69_borderRightWidth2 =
                    RDM7oqG69.borderRightWidth) !== null &&
                  _RDM7oqG69_borderRightWidth2 !== void 0
                    ? _RDM7oqG69_borderRightWidth2
                    : RDM7oqG69.borderWidth
                }px`,
                "--border-style": RDM7oqG69.borderStyle,
                "--border-top-width": `${
                  (_RDM7oqG69_borderTopWidth2 = RDM7oqG69.borderTopWidth) !==
                    null && _RDM7oqG69_borderTopWidth2 !== void 0
                    ? _RDM7oqG69_borderTopWidth2
                    : RDM7oqG69.borderWidth
                }px`,
                borderBottomLeftRadius: "100%",
                borderBottomRightRadius: "100%",
                borderTopLeftRadius: "100%",
                borderTopRightRadius: "100%",
              },
              transformTemplate: transformTemplate1,
              ...addPropertyOverrides(
                {
                  jMWPy6G8Y: {
                    background: {
                      alt: "",
                      fit: "stretch",
                      loading: getLoadingLazyAtYPosition(
                        ((componentViewport === null ||
                        componentViewport === void 0
                          ? void 0
                          : componentViewport.y) || 0) +
                          (((componentViewport === null ||
                          componentViewport === void 0
                            ? void 0
                            : componentViewport.height) || 48) *
                            0.49230769230769256 -
                            23)
                      ),
                      sizes: "46px",
                      ...toResponsiveImage(fwD6acpNS),
                      ...{ positionX: "center", positionY: "center" },
                    },
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
            /*#__PURE__*/ _jsx(Image, {
              background: {
                alt: "",
                fit: "stretch",
                loading: getLoadingLazyAtYPosition(
                  ((componentViewport === null || componentViewport === void 0
                    ? void 0
                    : componentViewport.y) || 0) +
                    (((componentViewport === null ||
                    componentViewport === void 0
                      ? void 0
                      : componentViewport.height) || 65) *
                      0.49230769230769256 -
                      27)
                ),
                sizes: "54px",
                ...toResponsiveImage(vNAo0sswR),
                ...{ positionX: "center", positionY: "center" },
              },
              className: "framer-rix1l1",
              "data-border": true,
              "data-framer-name": "4",
              layoutDependency: layoutDependency,
              layoutId: "S_S5ZVWiw",
              style: {
                "--border-bottom-width": `${
                  (_RDM7oqG69_borderBottomWidth3 =
                    RDM7oqG69.borderBottomWidth) !== null &&
                  _RDM7oqG69_borderBottomWidth3 !== void 0
                    ? _RDM7oqG69_borderBottomWidth3
                    : RDM7oqG69.borderWidth
                }px`,
                "--border-color": RDM7oqG69.borderColor,
                "--border-left-width": `${
                  (_RDM7oqG69_borderLeftWidth3 = RDM7oqG69.borderLeftWidth) !==
                    null && _RDM7oqG69_borderLeftWidth3 !== void 0
                    ? _RDM7oqG69_borderLeftWidth3
                    : RDM7oqG69.borderWidth
                }px`,
                "--border-right-width": `${
                  (_RDM7oqG69_borderRightWidth3 =
                    RDM7oqG69.borderRightWidth) !== null &&
                  _RDM7oqG69_borderRightWidth3 !== void 0
                    ? _RDM7oqG69_borderRightWidth3
                    : RDM7oqG69.borderWidth
                }px`,
                "--border-style": RDM7oqG69.borderStyle,
                "--border-top-width": `${
                  (_RDM7oqG69_borderTopWidth3 = RDM7oqG69.borderTopWidth) !==
                    null && _RDM7oqG69_borderTopWidth3 !== void 0
                    ? _RDM7oqG69_borderTopWidth3
                    : RDM7oqG69.borderWidth
                }px`,
                borderBottomLeftRadius: "100%",
                borderBottomRightRadius: "100%",
                borderTopLeftRadius: "100%",
                borderTopRightRadius: "100%",
              },
              transformTemplate: transformTemplate1,
              ...addPropertyOverrides(
                {
                  jMWPy6G8Y: {
                    background: {
                      alt: "",
                      fit: "stretch",
                      loading: getLoadingLazyAtYPosition(
                        ((componentViewport === null ||
                        componentViewport === void 0
                          ? void 0
                          : componentViewport.y) || 0) +
                          (((componentViewport === null ||
                          componentViewport === void 0
                            ? void 0
                            : componentViewport.height) || 48) *
                            0.49230769230769256 -
                            23)
                      ),
                      sizes: "46px",
                      ...toResponsiveImage(vNAo0sswR),
                      ...{ positionX: "center", positionY: "center" },
                    },
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-1so9i2b",
              "data-framer-name": "5",
              layoutDependency: layoutDependency,
              layoutId: "QiRd_uMkj",
              style: {
                backgroundColor: K01rPaGiO,
                borderBottomLeftRadius: "100%",
                borderBottomRightRadius: "100%",
                borderTopLeftRadius: "100%",
                borderTopRightRadius: "100%",
              },
              transformTemplate: transformTemplate1,
              children: /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    style: {
                      "--font-selector": "SW50ZXItU2VtaUJvbGQ=",
                      "--framer-font-family":
                        '"Inter", "Inter Placeholder", sans-serif',
                      "--framer-font-size": "15px",
                      "--framer-font-weight": "600",
                      "--framer-letter-spacing": "-0.04em",
                      "--framer-line-height": "100%",
                      "--framer-text-alignment": "center",
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                    },
                    children: "20+",
                  }),
                }),
                className: "framer-mhdo1b",
                "data-framer-name": "20+",
                fonts: ["Inter-SemiBold"],
                layoutDependency: layoutDependency,
                layoutId: "OygHkVJqf",
                style: {
                  "--extracted-r6o4lv": "rgb(255, 255, 255)",
                  "--framer-paragraph-spacing": "0px",
                },
                text: IYnqoNnsD,
                transformTemplate: transformTemplate2,
                verticalAlignment: "top",
                withExternalLayout: true,
                ...addPropertyOverrides(
                  {
                    jMWPy6G8Y: {
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector": "SW50ZXItU2VtaUJvbGQ=",
                            "--framer-font-family":
                              '"Inter", "Inter Placeholder", sans-serif',
                            "--framer-font-size": "12px",
                            "--framer-font-weight": "600",
                            "--framer-letter-spacing": "-0.04em",
                            "--framer-line-height": "100%",
                            "--framer-text-alignment": "center",
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                          },
                          children: "20+",
                        }),
                      }),
                    },
                  },
                  baseVariant,
                  gestureVariant
                ),
              }),
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-sT1mY.framer-3jiffd, .framer-sT1mY .framer-3jiffd { display: block; }",
  ".framer-sT1mY.framer-t5m6nn { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; min-height: 65px; overflow: visible; padding: 0px; position: relative; width: 175px; }",
  ".framer-sT1mY .framer-1ju8bs4 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 54px); left: 0px; position: absolute; top: 49%; width: 54px; z-index: 1; }",
  ".framer-sT1mY .framer-h0yyxg { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 54px); left: 30px; position: absolute; top: 49%; width: 54px; z-index: 1; }",
  ".framer-sT1mY .framer-yr5zjy { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 54px); left: 60px; position: absolute; top: 49%; width: 54px; z-index: 1; }",
  ".framer-sT1mY .framer-rix1l1 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 54px); left: 90px; position: absolute; top: 49%; width: 54px; z-index: 1; }",
  ".framer-sT1mY .framer-1so9i2b { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 54px); left: 120px; position: absolute; top: 49%; width: 54px; z-index: 1; }",
  ".framer-sT1mY .framer-mhdo1b { flex: none; height: auto; left: 50%; position: absolute; top: 50%; white-space: pre; width: auto; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-sT1mY.framer-t5m6nn { gap: 0px; } .framer-sT1mY.framer-t5m6nn > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-sT1mY.framer-t5m6nn > :first-child { margin-left: 0px; } .framer-sT1mY.framer-t5m6nn > :last-child { margin-right: 0px; } }",
  ".framer-sT1mY.framer-v-1vpmlft.framer-t5m6nn { height: 48px; min-height: unset; width: 150px; }",
  ".framer-sT1mY.framer-v-1vpmlft .framer-1ju8bs4 { height: var(--framer-aspect-ratio-supported, 46px); width: 46px; }",
  ".framer-sT1mY.framer-v-1vpmlft .framer-h0yyxg { height: var(--framer-aspect-ratio-supported, 46px); left: 26px; width: 46px; }",
  ".framer-sT1mY.framer-v-1vpmlft .framer-yr5zjy { height: var(--framer-aspect-ratio-supported, 46px); left: 52px; width: 46px; }",
  ".framer-sT1mY.framer-v-1vpmlft .framer-rix1l1 { height: var(--framer-aspect-ratio-supported, 46px); left: 78px; width: 46px; }",
  ".framer-sT1mY.framer-v-1vpmlft .framer-1so9i2b { height: var(--framer-aspect-ratio-supported, 46px); left: 104px; width: 46px; }",
  '.framer-sT1mY[data-border="true"]::after, .framer-sT1mY [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 65
 * @framerIntrinsicWidth 175
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"jMWPy6G8Y":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"dGWMhyRCs":"image1","H0Oo1Mfv9":"image2","fwD6acpNS":"image3","vNAo0sswR":"image4","RDM7oqG69":"border","IYnqoNnsD":"amount","K01rPaGiO":"bGColor"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerP9ubNxmwe = withCSS(Component, css, "framer-sT1mY");
export default FramerP9ubNxmwe;
FramerP9ubNxmwe.displayName = "Team / Avatar";
FramerP9ubNxmwe.defaultProps = { height: 65, width: 175 };
addPropertyControls(FramerP9ubNxmwe, {
  variant: {
    options: ["UMGTZZ0f6", "jMWPy6G8Y"],
    optionTitles: ["Desktop", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  dGWMhyRCs: {
    __defaultAssetReference:
      "data:framer/asset-reference,Qx5yBzgjmhI4ZhyOxhgNHDX4L5s.png?originalFilename=Ellipse+9.png&preferredSize=auto",
    title: "Image 1",
    type: ControlType.ResponsiveImage,
  },
  H0Oo1Mfv9: {
    __defaultAssetReference:
      "data:framer/asset-reference,GQOltmsmeeYSsbHJ9ijpOx0M.png?originalFilename=Ellipse+8.png&preferredSize=auto",
    title: "Image 2",
    type: ControlType.ResponsiveImage,
  },
  fwD6acpNS: {
    __defaultAssetReference:
      "data:framer/asset-reference,zfw44Zk0QT7qeSVw95UW4nDofo.png?originalFilename=Ellipse+10.png&preferredSize=auto",
    title: "Image 3",
    type: ControlType.ResponsiveImage,
  },
  vNAo0sswR: {
    __defaultAssetReference:
      "data:framer/asset-reference,tgyIqFImxk9E0TkgTI36r0dsss.png?originalFilename=Ellipse+11.png&preferredSize=auto",
    title: "Image 4",
    type: ControlType.ResponsiveImage,
  },
  RDM7oqG69: {
    defaultValue: {
      borderColor: "rgba(255, 255, 255, 1)",
      borderStyle: "solid",
      borderWidth: 3,
    },
    title: "Border",
    type: ControlType.Border,
  },
  IYnqoNnsD: {
    defaultValue: "20+",
    displayTextArea: false,
    title: "Amount",
    type: ControlType.String,
  },
  K01rPaGiO: {
    defaultValue:
      'var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12)) /* {"name":"Black"} */',
    title: "BG color",
    type: ControlType.Color,
  },
});
addFonts(
  FramerP9ubNxmwe,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/1ZFS7N918ojhhd0nQWdj3jz4w.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
          weight: "600",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerP9ubNxmwe",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerDisplayContentsDiv: "false",
        framerComponentViewportWidth: "true",
        framerVariables:
          '{"dGWMhyRCs":"image1","H0Oo1Mfv9":"image2","fwD6acpNS":"image3","vNAo0sswR":"image4","RDM7oqG69":"border","IYnqoNnsD":"amount","K01rPaGiO":"bGColor"}',
        framerIntrinsicHeight: "65",
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"jMWPy6G8Y":{"layout":["fixed","fixed"]}}}',
        framerIntrinsicWidth: "175",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./P9ubNxmwe.map
