// Generated by Framer (3e39c08)
import {
  jsx as _jsx,
  jsxs as _jsxs,
  Fragment as _Fragment,
} from "react/jsx-runtime";
import {
  addFonts,
  ChildrenCanSuspend,
  ComponentViewportProvider,
  Container,
  cx,
  forwardLoader,
  GeneratedComponentContext,
  getFonts,
  getFontsFromSharedStyle,
  Link,
  PathVariablesContext,
  PropertyOverrides,
  queryCache,
  RichText,
  useActiveVariantCallback,
  useCollectionReferenceQueryParam,
  useComponentViewport,
  useCustomCursors,
  useHydratedBreakpointVariants,
  useIsOnFramerCanvas,
  useLocaleInfo,
  useMetadata,
  useQueryData,
  useStringQueryParam,
  withCSS,
  withFX,
  withOptimizedAppearEffect,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import SmoothScroll from "https://framerusercontent.com/modules/Yppqt3Cs3Y8TZqvASnXl/PGrowqBrgWCViHduGfsA/SmoothScroll_Prod.js";
import Contact from "#framer/local/canvasComponent/McSGfJuih/McSGfJuih.js";
import HeaderHeader from "#framer/local/canvasComponent/O1fMzCErz/O1fMzCErz.js";
import Tab from "#framer/local/canvasComponent/YzJWp9yz0/YzJWp9yz0.js";
import ProjetcsProjectItemLight from "#framer/local/canvasComponent/Zn0HI2r8i/Zn0HI2r8i.js";
import Project from "#framer/local/collection/RwM1qgENQ/RwM1qgENQ.js";
import Category from "#framer/local/collection/rXPb48_DN/rXPb48_DN.js";
import * as sharedStyle1 from "#framer/local/css/hOrfMQMhw/hOrfMQMhw.js";
import * as sharedStyle from "#framer/local/css/zPBE4sevH/zPBE4sevH.js";
import metadataProvider from "#framer/local/webPageMetadata/JsWSQcZ5w/JsWSQcZ5w.js";
const HeaderHeaderFonts = getFonts(HeaderHeader);
const ContainerWithOptimizedAppearEffect = withOptimizedAppearEffect(Container);
const TabFonts = getFonts(Tab);
const ProjetcsProjectItemLightFonts = getFonts(ProjetcsProjectItemLight);
const MotionSectionWithOptimizedAppearEffect = withOptimizedAppearEffect(
  motion.section
);
const ContactFonts = getFonts(Contact);
const ContainerWithFX = withFX(Container);
const SmoothScrollFonts = getFonts(SmoothScroll);
const breakpoints = {
  f_aLVGyHi: "(min-width: 810px) and (max-width: 1199.98px)",
  lMSqs4sjM: "(max-width: 809.98px)",
  ZTFuceL1x: "(min-width: 1200px)",
};
const isBrowser = () => typeof document !== "undefined";
export const queryParamNames = ["category", "title"];
const serializationHash = "framer-IrJ3W";
const variantClassNames = {
  f_aLVGyHi: "framer-v-1699xyl",
  lMSqs4sjM: "framer-v-1egi9o",
  ZTFuceL1x: "framer-v-z384y7",
};
const TaWCKG1_9 = undefined;
const wffwBStN9 = undefined;
const idU2X7eYhMc = undefined;
const JRY3_qGYVU2X7eYhMc = undefined;
const E9FnOb4niU2X7eYhMc = undefined;
const EvxErjRB0NTslS2w3E = undefined;
const G5Mz1FFPUNTslS2w3E = undefined;
const fcLdTQRWuNTslS2w3E = undefined;
const jjZ9ReRduNTslS2w3E = undefined;
const UoGh11fYeNTslS2w3E = undefined;
const idNTslS2w3E = undefined;
const setTaWCKG1_9 = undefined;
const getRootLayoutProp = (
  hasLayoutTemplate,
  hasInheritedFlowEffect,
  fallback
) => {
  if (!hasLayoutTemplate) return fallback;
  return hasInheritedFlowEffect ? "position" : fallback;
};
const transition1 = {
  delay: 0.15,
  duration: 1,
  ease: [0.68, 0, 0.16, 0.97],
  type: "tween",
};
const animation = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: 0,
  y: 0,
};
const animation1 = {
  opacity: 0.001,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 30,
};
const matchVariant = (...args) => {
  for (const arg of args) {
    if (arg && typeof arg === "string") return arg;
  }
  return undefined;
};
const isSet = (value) => {
  if (Array.isArray(value)) return value.length > 0;
  return value !== undefined && value !== null && value !== "";
};
const convertFromBoolean = (value, activeLocale) => {
  return value ? "mhphXOnUS" : "kJCs8lIch";
};
const convertFromBoolean1 = (value, activeLocale) => {
  return value ? "Aa9nIlIIa" : "rIZkxSqwp";
};
const convertFromBoolean2 = (value, activeLocale) => {
  return value ? "af5HvgCFL" : "krCfdifha";
};
const equals = (a, b) => {
  return typeof a === "string" && typeof b === "string"
    ? a.toLowerCase() === b.toLowerCase()
    : a === b;
};
const convertFromBoolean3 = (value, activeLocale) => {
  return value ? "kJCs8lIch" : "mhphXOnUS";
};
const convertFromBoolean4 = (value, activeLocale) => {
  return value ? "rIZkxSqwp" : "Aa9nIlIIa";
};
const convertFromBoolean5 = (value, activeLocale) => {
  return value ? "krCfdifha" : "af5HvgCFL";
};
const query = () => ({
  from: { alias: "U2X7eYhMc", data: Category, type: "Collection" },
  select: [
    { collection: "U2X7eYhMc", name: "id", type: "Identifier" },
    { collection: "U2X7eYhMc", name: "JRY3_qGYV", type: "Identifier" },
    { collection: "U2X7eYhMc", name: "E9FnOb4ni", type: "Identifier" },
  ],
});
const QueryData = ({ query, pageSize, children }) => {
  const data = useQueryData(query);
  return children(data);
};
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const query1 = (TaWCKG1_9, wffwBStN9) => ({
  from: { alias: "NTslS2w3E", data: Project, type: "Collection" },
  orderBy: [
    {
      collection: "NTslS2w3E",
      direction: "desc",
      name: "xUxg0TNNr",
      type: "Identifier",
    },
  ],
  select: [
    { collection: "NTslS2w3E", name: "EvxErjRB0", type: "Identifier" },
    { collection: "NTslS2w3E", name: "G5Mz1FFPU", type: "Identifier" },
    { collection: "NTslS2w3E", name: "fcLdTQRWu", type: "Identifier" },
    { collection: "NTslS2w3E", name: "jjZ9ReRdu", type: "Identifier" },
    {
      alias: "UoGh11fYe",
      arguments: [
        {
          from: { alias: "UoGh11fYe", data: Category, type: "Collection" },
          orderBy: [
            {
              arguments: [
                {
                  collection: "NTslS2w3E",
                  name: "UoGh11fYe",
                  type: "Identifier",
                },
                { collection: "UoGh11fYe", name: "id", type: "Identifier" },
              ],
              functionName: "INDEX_OF",
              type: "FunctionCall",
            },
          ],
          select: [{ collection: "UoGh11fYe", name: "id", type: "Identifier" }],
          type: "Select",
          where: {
            left: { collection: "UoGh11fYe", name: "id", type: "Identifier" },
            operator: "in",
            right: {
              collection: "NTslS2w3E",
              name: "UoGh11fYe",
              type: "Identifier",
            },
            type: "BinaryOperation",
          },
        },
      ],
      functionName: "FLAT_ARRAY",
      type: "FunctionCall",
    },
    { collection: "NTslS2w3E", name: "id", type: "Identifier" },
  ],
  where: {
    left: {
      left: {
        left: { type: "LiteralValue", value: TaWCKG1_9 },
        operator: "==",
        right: { type: "LiteralValue", value: null },
        type: "BinaryOperation",
      },
      operator: "or",
      right: {
        left: { type: "LiteralValue", value: TaWCKG1_9 },
        operator: "in",
        right: {
          collection: "NTslS2w3E",
          name: "UoGh11fYe",
          type: "Identifier",
        },
        type: "BinaryOperation",
      },
      type: "BinaryOperation",
    },
    operator: "and",
    right: {
      left: {
        left: { type: "LiteralValue", value: wffwBStN9 },
        operator: "==",
        right: { type: "LiteralValue", value: null },
        type: "BinaryOperation",
      },
      operator: "or",
      right: {
        arguments: [
          { collection: "NTslS2w3E", name: "fcLdTQRWu", type: "Identifier" },
          { type: "LiteralValue", value: wffwBStN9 },
        ],
        functionName: "CONTAINS",
        type: "FunctionCall",
      },
      type: "BinaryOperation",
    },
    type: "BinaryOperation",
  },
});
const humanReadableVariantMap = {
  Desktop: "ZTFuceL1x",
  Phone: "lMSqs4sjM",
  Tablet: "f_aLVGyHi",
};
const HTMLStyle = ({ value }) => {
  const onCanvas = useIsOnFramerCanvas();
  if (onCanvas) return null;
  return /*#__PURE__*/ _jsx("style", {
    dangerouslySetInnerHTML: { __html: value },
    "data-framer-html-style": "",
  });
};
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "ZTFuceL1x",
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const [TaWCKG1_9, setTaWCKG1_9] = useCollectionReferenceQueryParam({
    collectionId: "rXPb48_DN",
    optional: true,
    parameterName: "category",
  });
  const [wffwBStN9] = useStringQueryParam({
    optional: true,
    parameterName: "title",
  });
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const metadata = React.useMemo(
    () => metadataProvider({}, activeLocale),
    [activeLocale]
  );
  useMetadata(metadata);
  const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(
    variant,
    breakpoints,
    false
  );
  const gestureVariant = undefined;
  const { activeVariantCallback, delay } = useActiveVariantCallback(undefined);
  const eAHGXWjyhxe1fh1 = activeVariantCallback(async (...args) => {
    setTaWCKG1_9?.();
  });
  const eAHGXWjyhh48akc = ({ arg6cyvhl }) =>
    activeVariantCallback(async (...args) => {
      setTaWCKG1_9?.(arg6cyvhl);
    });
  const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const hasLayoutTemplate = React.useContext(
    GeneratedComponentContext
  )?.isLayoutTemplate;
  const hasInheritedFlowEffect = Boolean(
    React.useContext(MotionConfigContext)?.transition?.layout
  );
  const motionLayout = getRootLayoutProp(
    hasLayoutTemplate,
    hasInheritedFlowEffect
  );
  const isDisplayed = () => {
    if (!isBrowser()) return true;
    if (baseVariant === "lMSqs4sjM") return false;
    return true;
  };
  useCustomCursors({});
  return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
    value: {
      activeVariantId: baseVariant,
      humanReadableVariantMap,
      primaryVariantId: "ZTFuceL1x",
      variantClassNames,
    },
    children: /*#__PURE__*/ _jsxs(LayoutGroup, {
      id: layoutId ?? defaultLayoutId,
      children: [
        /*#__PURE__*/ _jsx(HTMLStyle, {
          value: "html body { background: rgb(255, 255, 255); }",
        }),
        /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          className: cx(scopingClassNames, "framer-z384y7", className),
          ref: refBinding,
          style: { ...style },
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 371,
              width: componentViewport?.width || "100vw",
              y: (componentViewport?.y || 0) + 0,
              children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                breakpoint: baseVariant,
                overrides: {
                  lMSqs4sjM: {
                    animate: undefined,
                    initial: undefined,
                    optimized: undefined,
                  },
                },
                children: /*#__PURE__*/ _jsx(
                  ContainerWithOptimizedAppearEffect,
                  {
                    animate: animation,
                    className: "framer-1ossqz5-container",
                    "data-framer-appear-id": "1ossqz5",
                    initial: animation1,
                    layout: motionLayout,
                    nodeId: "s7IFOMamA",
                    optimized: true,
                    rendersWithMotion: true,
                    scopeId: "JsWSQcZ5w",
                    children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                      breakpoint: baseVariant,
                      overrides: {
                        lMSqs4sjM: { variant: matchVariant("XPCVor9Ih") },
                      },
                      children: /*#__PURE__*/ _jsx(HeaderHeader, {
                        GcgGR2ESN:
                          "var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12))",
                        height: "100%",
                        id: "s7IFOMamA",
                        layoutId: "s7IFOMamA",
                        style: { width: "100%" },
                        variant: matchVariant("LoRRTE51b"),
                        width: "100%",
                      }),
                    }),
                  }
                ),
              }),
            }),
            /*#__PURE__*/ _jsxs(motion.main, {
              className: "framer-1xy1kbf",
              "data-framer-name": "Main",
              layout: motionLayout,
              children: [
                /*#__PURE__*/ _jsx("div", {
                  className: "framer-r7ttki",
                  "data-framer-name": "Container",
                  children: /*#__PURE__*/ _jsxs(
                    MotionSectionWithOptimizedAppearEffect,
                    {
                      animate: animation,
                      className: "framer-oc9h0d",
                      "data-framer-appear-id": "oc9h0d",
                      "data-framer-name": "Projetcs / Projects filter",
                      initial: animation1,
                      optimized: true,
                      children: [
                        /*#__PURE__*/ _jsx("div", {
                          className: "framer-j566yf",
                          "data-framer-name": "Top",
                          children: /*#__PURE__*/ _jsxs("div", {
                            className: "framer-1eft4xt",
                            "data-framer-name": "Container",
                            children: [
                              /*#__PURE__*/ _jsxs("div", {
                                className: "framer-1veoqsk",
                                "data-framer-name": "Heading",
                                children: [
                                  /*#__PURE__*/ _jsx(RichText, {
                                    __fromCanvasComponent: true,
                                    children: /*#__PURE__*/ _jsx(
                                      React.Fragment,
                                      {
                                        children: /*#__PURE__*/ _jsx("h1", {
                                          className:
                                            "framer-styles-preset-lzby6w",
                                          "data-styles-preset": "zPBE4sevH",
                                          dir: "auto",
                                          style: {
                                            "--framer-text-color":
                                              "var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12))",
                                          },
                                          children: "Projects",
                                        }),
                                      }
                                    ),
                                    className: "framer-oowjr0",
                                    fonts: ["Inter"],
                                    verticalAlignment: "top",
                                    withExternalLayout: true,
                                  }),
                                  /*#__PURE__*/ _jsx("div", {
                                    className: "framer-4xny17",
                                    "data-framer-name": "Text",
                                    children: /*#__PURE__*/ _jsx(RichText, {
                                      __fromCanvasComponent: true,
                                      children: /*#__PURE__*/ _jsx(
                                        React.Fragment,
                                        {
                                          children: /*#__PURE__*/ _jsx("p", {
                                            className:
                                              "framer-styles-preset-1raml1m",
                                            "data-styles-preset": "hOrfMQMhw",
                                            dir: "auto",
                                            style: {
                                              "--framer-text-color":
                                                "rgba(12, 12, 12, 0.6)",
                                            },
                                            children:
                                              "Every project we deliver is a reflection of our commitment to quality, designed to inspire and drive success.",
                                          }),
                                        }
                                      ),
                                      className: "framer-19fnr3z",
                                      "data-framer-name":
                                        "Every project we deliver is a reflection of our commitment to quality, designed to inspire and drive success.",
                                      fonts: ["Inter"],
                                      verticalAlignment: "top",
                                      withExternalLayout: true,
                                    }),
                                  }),
                                ],
                              }),
                              /*#__PURE__*/ _jsx("div", {
                                className: "framer-1utq7j3",
                                "data-border": true,
                                children: /*#__PURE__*/ _jsx(
                                  ChildrenCanSuspend,
                                  {
                                    children: /*#__PURE__*/ _jsx(QueryData, {
                                      query: query(),
                                      children: (
                                        collection,
                                        paginationInfo,
                                        loadMore
                                      ) => {
                                        return /*#__PURE__*/ _jsxs(_Fragment, {
                                          children: [
                                            /*#__PURE__*/ _jsx(
                                              ComponentViewportProvider,
                                              {
                                                height: 45,
                                                children: /*#__PURE__*/ _jsx(
                                                  Container,
                                                  {
                                                    className:
                                                      "framer-p7cv5j-container",
                                                    nodeId: "TWFwZsG_u",
                                                    scopeId: "JsWSQcZ5w",
                                                    children:
                                                      /*#__PURE__*/ _jsx(
                                                        PropertyOverrides,
                                                        {
                                                          breakpoint:
                                                            baseVariant,
                                                          overrides: {
                                                            f_aLVGyHi: {
                                                              variant:
                                                                matchVariant(
                                                                  convertFromBoolean1(
                                                                    isSet(
                                                                      TaWCKG1_9
                                                                    ),
                                                                    activeLocale
                                                                  )
                                                                ),
                                                            },
                                                            lMSqs4sjM: {
                                                              variant:
                                                                matchVariant(
                                                                  convertFromBoolean2(
                                                                    isSet(
                                                                      TaWCKG1_9
                                                                    ),
                                                                    activeLocale
                                                                  )
                                                                ),
                                                            },
                                                          },
                                                          children:
                                                            /*#__PURE__*/ _jsx(
                                                              Tab,
                                                              {
                                                                eAHGXWjyh:
                                                                  eAHGXWjyhxe1fh1,
                                                                height: "100%",
                                                                id: "TWFwZsG_u",
                                                                layoutId:
                                                                  "TWFwZsG_u",
                                                                mXpY5N3RA:
                                                                  "All",
                                                                variant:
                                                                  matchVariant(
                                                                    convertFromBoolean(
                                                                      isSet(
                                                                        TaWCKG1_9
                                                                      ),
                                                                      activeLocale
                                                                    )
                                                                  ),
                                                                width: "100%",
                                                              }
                                                            ),
                                                        }
                                                      ),
                                                  }
                                                ),
                                              }
                                            ),
                                            collection?.map(
                                              (
                                                {
                                                  E9FnOb4ni: E9FnOb4niU2X7eYhMc,
                                                  id: idU2X7eYhMc,
                                                  JRY3_qGYV: JRY3_qGYVU2X7eYhMc,
                                                },
                                                index
                                              ) => {
                                                JRY3_qGYVU2X7eYhMc ??= "";
                                                E9FnOb4niU2X7eYhMc ??= "";
                                                return /*#__PURE__*/ _jsx(
                                                  LayoutGroup,
                                                  {
                                                    id: `U2X7eYhMc-${idU2X7eYhMc}`,
                                                    children:
                                                      /*#__PURE__*/ _jsx(
                                                        PathVariablesContext.Provider,
                                                        {
                                                          value: {
                                                            E9FnOb4ni:
                                                              E9FnOb4niU2X7eYhMc,
                                                          },
                                                          children:
                                                            /*#__PURE__*/ _jsx(
                                                              ComponentViewportProvider,
                                                              {
                                                                height: 45,
                                                                children:
                                                                  /*#__PURE__*/ _jsx(
                                                                    Container,
                                                                    {
                                                                      className:
                                                                        "framer-1ymt1cu-container",
                                                                      nodeId:
                                                                        "T9AmLFB3o",
                                                                      scopeId:
                                                                        "JsWSQcZ5w",
                                                                      children:
                                                                        /*#__PURE__*/ _jsx(
                                                                          PropertyOverrides,
                                                                          {
                                                                            breakpoint:
                                                                              baseVariant,
                                                                            overrides:
                                                                              {
                                                                                f_aLVGyHi:
                                                                                  {
                                                                                    variant:
                                                                                      matchVariant(
                                                                                        convertFromBoolean4(
                                                                                          equals(
                                                                                            TaWCKG1_9,
                                                                                            idU2X7eYhMc
                                                                                          ),
                                                                                          activeLocale
                                                                                        )
                                                                                      ),
                                                                                  },
                                                                                lMSqs4sjM:
                                                                                  {
                                                                                    variant:
                                                                                      matchVariant(
                                                                                        convertFromBoolean5(
                                                                                          equals(
                                                                                            TaWCKG1_9,
                                                                                            idU2X7eYhMc
                                                                                          ),
                                                                                          activeLocale
                                                                                        )
                                                                                      ),
                                                                                  },
                                                                              },
                                                                            children:
                                                                              /*#__PURE__*/ _jsx(
                                                                                Tab,
                                                                                {
                                                                                  eAHGXWjyh:
                                                                                    eAHGXWjyhh48akc(
                                                                                      {
                                                                                        arg6cyvhl:
                                                                                          idU2X7eYhMc,
                                                                                      }
                                                                                    ),
                                                                                  height:
                                                                                    "100%",
                                                                                  id: "T9AmLFB3o",
                                                                                  layoutId:
                                                                                    "T9AmLFB3o",
                                                                                  mXpY5N3RA:
                                                                                    JRY3_qGYVU2X7eYhMc,
                                                                                  variant:
                                                                                    matchVariant(
                                                                                      convertFromBoolean3(
                                                                                        equals(
                                                                                          TaWCKG1_9,
                                                                                          idU2X7eYhMc
                                                                                        ),
                                                                                        activeLocale
                                                                                      )
                                                                                    ),
                                                                                  width:
                                                                                    "100%",
                                                                                }
                                                                              ),
                                                                          }
                                                                        ),
                                                                    }
                                                                  ),
                                                              }
                                                            ),
                                                        }
                                                      ),
                                                  },
                                                  idU2X7eYhMc
                                                );
                                              }
                                            ),
                                          ],
                                        });
                                      },
                                    }),
                                  }
                                ),
                              }),
                            ],
                          }),
                        }),
                        /*#__PURE__*/ _jsx("div", {
                          className: "framer-1tubwjx",
                          "data-framer-name": "Items",
                          children: /*#__PURE__*/ _jsx("div", {
                            className: "framer-1h6ud6o",
                            "data-framer-name": "Portfolios All",
                            children: /*#__PURE__*/ _jsx(ChildrenCanSuspend, {
                              children: /*#__PURE__*/ _jsx(QueryData, {
                                query: query1(TaWCKG1_9, wffwBStN9),
                                children: (
                                  collection1,
                                  paginationInfo1,
                                  loadMore1
                                ) => {
                                  return /*#__PURE__*/ _jsx(_Fragment, {
                                    children: collection1?.map(
                                      (
                                        {
                                          EvxErjRB0: EvxErjRB0NTslS2w3E,
                                          fcLdTQRWu: fcLdTQRWuNTslS2w3E,
                                          G5Mz1FFPU: G5Mz1FFPUNTslS2w3E,
                                          id: idNTslS2w3E,
                                          jjZ9ReRdu: jjZ9ReRduNTslS2w3E,
                                          UoGh11fYe: UoGh11fYeNTslS2w3E,
                                        },
                                        index1
                                      ) => {
                                        EvxErjRB0NTslS2w3E ??= "";
                                        fcLdTQRWuNTslS2w3E ??= "";
                                        jjZ9ReRduNTslS2w3E ??= "";
                                        return /*#__PURE__*/ _jsx(
                                          LayoutGroup,
                                          {
                                            id: `NTslS2w3E-${idNTslS2w3E}`,
                                            children: /*#__PURE__*/ _jsx(
                                              PathVariablesContext.Provider,
                                              {
                                                value: {
                                                  EvxErjRB0: EvxErjRB0NTslS2w3E,
                                                },
                                                children: /*#__PURE__*/ _jsx(
                                                  Link,
                                                  {
                                                    href: {
                                                      pathVariables: {
                                                        EvxErjRB0:
                                                          EvxErjRB0NTslS2w3E,
                                                      },
                                                      webPageId: "v75Tpw1Yr",
                                                    },
                                                    motionChild: true,
                                                    nodeId: "Lbg4aAtZp",
                                                    scopeId: "JsWSQcZ5w",
                                                    children:
                                                      /*#__PURE__*/ _jsx(
                                                        motion.a,
                                                        {
                                                          className:
                                                            "framer-dmnnwu framer-1no7fbc",
                                                          children:
                                                            /*#__PURE__*/ _jsx(
                                                              PropertyOverrides,
                                                              {
                                                                breakpoint:
                                                                  baseVariant,
                                                                overrides: {
                                                                  f_aLVGyHi: {
                                                                    width: `max((min(max(min(max(${
                                                                      componentViewport?.width ||
                                                                      "100vw"
                                                                    }, 1px) - 64px, 1848px), 1px), 1848px) - 20px) / 2, 50px)`,
                                                                  },
                                                                  lMSqs4sjM: {
                                                                    width: `max(min(max(min(max(${
                                                                      componentViewport?.width ||
                                                                      "100vw"
                                                                    }, 1px) - 48px, 1848px), 1px), 1848px), 50px)`,
                                                                  },
                                                                },
                                                                children:
                                                                  /*#__PURE__*/ _jsx(
                                                                    ComponentViewportProvider,
                                                                    {
                                                                      height: 504,
                                                                      width: `max((min(max(min(max(${
                                                                        componentViewport?.width ||
                                                                        "100vw"
                                                                      }, 1px) - 72px, 1848px), 1px), 1848px) - 20px) / 2, 50px)`,
                                                                      children:
                                                                        /*#__PURE__*/ _jsx(
                                                                          Container,
                                                                          {
                                                                            className:
                                                                              "framer-jsdhw5-container",
                                                                            nodeId:
                                                                              "Z7vXOxxPx",
                                                                            scopeId:
                                                                              "JsWSQcZ5w",
                                                                            children:
                                                                              /*#__PURE__*/ _jsx(
                                                                                PropertyOverrides,
                                                                                {
                                                                                  breakpoint:
                                                                                    baseVariant,
                                                                                  overrides:
                                                                                    {
                                                                                      f_aLVGyHi:
                                                                                        {
                                                                                          EDyjka_tA:
                                                                                            "0px 0px 30px 0px",
                                                                                        },
                                                                                      lMSqs4sjM:
                                                                                        {
                                                                                          EDyjka_tA:
                                                                                            "0px 0px 30px 0px",
                                                                                          variant:
                                                                                            matchVariant(
                                                                                              "b1SQmw_vc"
                                                                                            ),
                                                                                        },
                                                                                    },
                                                                                  children:
                                                                                    /*#__PURE__*/ _jsx(
                                                                                      ProjetcsProjectItemLight,
                                                                                      {
                                                                                        Amt5RCa4w:
                                                                                          fcLdTQRWuNTslS2w3E,
                                                                                        EDyjka_tA:
                                                                                          "0px 0px 40px 0px",
                                                                                        Evwde5RGu:
                                                                                          UoGh11fYeNTslS2w3E,
                                                                                        height:
                                                                                          "100%",
                                                                                        id: "Z7vXOxxPx",
                                                                                        layoutId:
                                                                                          "Z7vXOxxPx",
                                                                                        style:
                                                                                          {
                                                                                            width:
                                                                                              "100%",
                                                                                          },
                                                                                        variant:
                                                                                          matchVariant(
                                                                                            "dk79TZPmR"
                                                                                          ),
                                                                                        width:
                                                                                          "100%",
                                                                                        y1k3Le1PS:
                                                                                          jjZ9ReRduNTslS2w3E,
                                                                                        zlwOopuYm:
                                                                                          toResponsiveImage(
                                                                                            G5Mz1FFPUNTslS2w3E
                                                                                          ),
                                                                                      }
                                                                                    ),
                                                                                }
                                                                              ),
                                                                          }
                                                                        ),
                                                                    }
                                                                  ),
                                                              }
                                                            ),
                                                        }
                                                      ),
                                                  }
                                                ),
                                              }
                                            ),
                                          },
                                          idNTslS2w3E
                                        );
                                      }
                                    ),
                                  });
                                },
                              }),
                            }),
                          }),
                        }),
                      ],
                    }
                  ),
                }),
                /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                  height: 950,
                  width: componentViewport?.width || "100vw",
                  children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                    breakpoint: baseVariant,
                    overrides: {
                      lMSqs4sjM: {
                        __framer__styleTransformEffectEnabled: undefined,
                      },
                    },
                    children: /*#__PURE__*/ _jsx(ContainerWithFX, {
                      __framer__styleTransformEffectEnabled: true,
                      __framer__transformTargets: [
                        {
                          target: {
                            opacity: 1,
                            rotate: 0,
                            rotateX: 0,
                            rotateY: 0,
                            scale: 1,
                            skewX: 0,
                            skewY: 0,
                            x: 0,
                            y: -170,
                          },
                        },
                        {
                          target: {
                            opacity: 1,
                            rotate: 0,
                            rotateX: 0,
                            rotateY: 0,
                            scale: 1,
                            skewX: 0,
                            skewY: 0,
                            x: 0,
                            y: 0,
                          },
                        },
                      ],
                      __framer__transformTrigger: "onInView",
                      __perspectiveFX: false,
                      __targetOpacity: 1,
                      className: "framer-g343wv-container",
                      nodeId: "XIRqT9uK3",
                      rendersWithMotion: true,
                      scopeId: "JsWSQcZ5w",
                      children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                        breakpoint: baseVariant,
                        overrides: {
                          f_aLVGyHi: { variant: matchVariant("fEKWViVLS") },
                          lMSqs4sjM: { variant: matchVariant("nqWgwdImM") },
                        },
                        children: /*#__PURE__*/ _jsx(Contact, {
                          height: "100%",
                          id: "XIRqT9uK3",
                          layoutId: "XIRqT9uK3",
                          style: { width: "100%" },
                          variant: matchVariant("Il7efBbw5"),
                          width: "100%",
                        }),
                      }),
                    }),
                  }),
                }),
              ],
            }),
            isDisplayed() &&
              /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                children: /*#__PURE__*/ _jsx(Container, {
                  className: "framer-156gql9-container hidden-1egi9o",
                  isAuthoredByUser: true,
                  isModuleExternal: true,
                  layout: motionLayout,
                  nodeId: "wM4EQAsoF",
                  scopeId: "JsWSQcZ5w",
                  children: /*#__PURE__*/ _jsx(SmoothScroll, {
                    height: "100%",
                    id: "wM4EQAsoF",
                    intensity: 10,
                    layoutId: "wM4EQAsoF",
                    width: "100%",
                  }),
                }),
              }),
          ],
        }),
        /*#__PURE__*/ _jsx("div", { id: "overlay" }),
      ],
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-IrJ3W.framer-1no7fbc, .framer-IrJ3W .framer-1no7fbc { display: block; }",
  ".framer-IrJ3W.framer-z384y7 { align-content: center; align-items: center; background-color: #ffffff; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1200px; }",
  ".framer-IrJ3W .framer-1ossqz5-container { flex: none; height: auto; left: 0px; position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-effect-override, transform); z-index: 9; }",
  ".framer-IrJ3W .framer-1xy1kbf { align-content: center; align-items: center; background-color: var(--token-d74d16c5-23aa-4649-a2ad-0da8c936dade, #ffffff); display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 240px 0px 0px 0px; position: relative; width: 100%; }",
  ".framer-IrJ3W .framer-r7ttki { align-content: center; align-items: center; background-color: var(--token-d74d16c5-23aa-4649-a2ad-0da8c936dade, #ffffff); display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 0px 120px 0px; position: relative; width: 100%; z-index: 2; }",
  ".framer-IrJ3W .framer-oc9h0d { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: flex-start; padding: 0px 36px 0px 36px; position: relative; width: 1px; will-change: var(--framer-will-change-effect-override, transform); }",
  ".framer-IrJ3W .framer-j566yf { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-IrJ3W .framer-1eft4xt { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 90px; height: min-content; justify-content: center; max-width: 1848px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-IrJ3W .framer-1veoqsk { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-IrJ3W .framer-oowjr0 { flex: 1 0 0px; height: auto; max-width: 100%; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  ".framer-IrJ3W .framer-4xny17 { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 10px 0px 0px 0px; position: relative; width: 1px; }",
  ".framer-IrJ3W .framer-19fnr3z { --framer-paragraph-spacing: 0px; flex: 1 0 0px; height: auto; max-width: 510px; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  ".framer-IrJ3W .framer-1utq7j3 { --border-bottom-width: 1px; --border-color: #d6d6d6; --border-left-width: 0px; --border-right-width: 0px; --border-style: solid; --border-top-width: 0px; align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 10px 40px; height: min-content; justify-content: flex-start; padding: 0px 0px 25px 0px; position: relative; width: 100%; }",
  ".framer-IrJ3W .framer-p7cv5j-container, .framer-IrJ3W .framer-1ymt1cu-container, .framer-IrJ3W .framer-156gql9-container { flex: none; height: auto; position: relative; width: auto; }",
  ".framer-IrJ3W .framer-1tubwjx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; max-width: 1848px; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
  ".framer-IrJ3W .framer-1h6ud6o { display: grid; flex: 1 0 0px; gap: 20px; grid-auto-rows: minmax(0, 1fr); grid-template-columns: repeat(2, minmax(50px, 1fr)); height: min-content; justify-content: center; max-width: 1848px; padding: 0px; position: relative; width: 1px; }",
  ".framer-IrJ3W .framer-dmnnwu { align-content: center; align-items: center; align-self: start; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 0px; height: min-content; justify-content: flex-start; justify-self: start; padding: 0px; position: relative; text-decoration: none; width: 100%; }",
  ".framer-IrJ3W .framer-jsdhw5-container { flex: 1 0 0px; height: auto; position: relative; width: 1px; }",
  ".framer-IrJ3W .framer-g343wv-container { flex: none; height: auto; position: relative; width: 100%; z-index: 1; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  '.framer-IrJ3W[data-border="true"]::after, .framer-IrJ3W [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
  "@media (min-width: 810px) and (max-width: 1199.98px) { .framer-IrJ3W.framer-z384y7 { width: 810px; } .framer-IrJ3W .framer-1xy1kbf { padding: 160px 0px 0px 0px; } .framer-IrJ3W .framer-r7ttki { padding: 0px 0px 90px 0px; } .framer-IrJ3W .framer-oc9h0d { gap: 50px; padding: 0px 32px 0px 32px; } .framer-IrJ3W .framer-1eft4xt { gap: 60px; } .framer-IrJ3W .framer-1veoqsk { flex-direction: column; } .framer-IrJ3W .framer-oowjr0, .framer-IrJ3W .framer-4xny17 { flex: none; width: 100%; } .framer-IrJ3W .framer-1utq7j3 { gap: 10px 31px; }}",
  "@media (max-width: 809.98px) { .framer-IrJ3W.framer-z384y7 { width: 390px; } .framer-IrJ3W .framer-1ossqz5-container { will-change: unset; } .framer-IrJ3W .framer-1xy1kbf { padding: 160px 0px 0px 0px; } .framer-IrJ3W .framer-r7ttki { padding: 0px 0px 20px 0px; } .framer-IrJ3W .framer-oc9h0d { gap: 24px; padding: 0px 24px 0px 24px; } .framer-IrJ3W .framer-1eft4xt { gap: 30px; } .framer-IrJ3W .framer-1veoqsk { flex-direction: column; gap: 16px; } .framer-IrJ3W .framer-oowjr0, .framer-IrJ3W .framer-4xny17 { flex: none; width: 100%; } .framer-IrJ3W .framer-1utq7j3 { --border-bottom-width: unset; --border-left-width: unset; --border-right-width: unset; --border-top-width: unset; gap: 1px 18px; padding: 0px 0px 6px 0px; } .framer-IrJ3W .framer-1h6ud6o { gap: 10px; grid-template-columns: repeat(1, minmax(50px, 1fr)); }}",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 4103.5
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"f_aLVGyHi":{"layout":["fixed","auto"]},"lMSqs4sjM":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerAcceptsLayoutTemplate true
 * @framerScrollSections false
 * @framerResponsiveScreen true
 * @framerLayoutTemplateFlowEffect true
 */ const FramerJsWSQcZ5w = withCSS(Component, css, "framer-IrJ3W");
export default FramerJsWSQcZ5w;
FramerJsWSQcZ5w.displayName = "Portfolio";
FramerJsWSQcZ5w.defaultProps = { height: 4103.5, width: 1200 };
addFonts(
  FramerJsWSQcZ5w,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
          weight: "400",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...HeaderHeaderFonts,
    ...TabFonts,
    ...ProjetcsProjectItemLightFonts,
    ...ContactFonts,
    ...SmoothScrollFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
FramerJsWSQcZ5w.loader = {
  load: (props, context) => {
    const locale = context.locale;
    const urlVarsPromise = (async () => {
      const TaWCKG1_91 = await (async () => {
        const slug = context.pathVariables?.["category"] ?? "";
        if (!slug) return "";
        const cache = context.collectionUtils?.get("rXPb48_DN");
        if (!cache) return "";
        return (await cache.getRecordIdBySlug(slug, locale)) ?? "";
      })();
      const wffwBStN91 = context.pathVariables?.["title"] ?? undefined;
      return { TaWCKG1_91, wffwBStN91 };
    })();
    const queryCacheEntry = queryCache.get(query(), locale);
    return Promise.allSettled([
      queryCacheEntry.preload(),
      urlVarsPromise.then(({ TaWCKG1_91, wffwBStN91 }) =>
        queryCache.get(query1(TaWCKG1_91, wffwBStN91), locale).preload()
      ),
      forwardLoader(HeaderHeader, {}, context),
      forwardLoader(Contact, {}, context),
      (async () => {
        const parentData = (await queryCacheEntry.readMaybeAsync()) ?? [];
        return Promise.allSettled(
          parentData.flatMap((item) => [
            forwardLoader(Tab, {}, context),
            forwardLoader(Tab, {}, context),
          ])
        );
      })(),
      (async () => {
        const { TaWCKG1_91, wffwBStN91 } = await urlVarsPromise;
        const parentData =
          (await queryCache
            .get(query1(TaWCKG1_91, wffwBStN91), locale)
            .readMaybeAsync()) ?? [];
        return Promise.allSettled(
          parentData.flatMap((item) =>
            forwardLoader(ProjetcsProjectItemLight, {}, context)
          )
        );
      })(),
    ]);
  },
};
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerJsWSQcZ5w",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerResponsiveScreen: "true",
        framerLayoutTemplateFlowEffect: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"f_aLVGyHi":{"layout":["fixed","auto"]},"lMSqs4sjM":{"layout":["fixed","auto"]}}}',
        framerContractVersion: "1",
        framerComponentViewportWidth: "true",
        framerAutoSizeImages: "true",
        framerDisplayContentsDiv: "false",
        framerColorSyntax: "true",
        framerIntrinsicHeight: "4103.5",
        framerAcceptsLayoutTemplate: "true",
        framerScrollSections: "false",
        framerIntrinsicWidth: "1200",
      },
    },
    queryParamNames: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
