// Generated by Framer (915daba)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/1HoGQ6QwD2LyK0GEQDFa/dIKwJomSAtcf6KAJzpfk/uQRBhygQf.js";
import * as sharedStyle1 from "https://framerusercontent.com/modules/oMgXPBeR6YdHTzKPyOpl/EoE1kmmGpZHB3Wts7nST/xNIXLfFSf.js";
const MotionDivWithFX = withFX(motion.div);
const cycleOrder = ["m9jSyhRqg", "gf_Ge1OgG"];
const serializationHash = "framer-IgBNJ";
const variantClassNames = {
  gf_Ge1OgG: "framer-v-1g7f7t6",
  m9jSyhRqg: "framer-v-1ebf3lc",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const animation = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 50,
};
const transition1 = {
  damping: 33,
  delay: 0.1,
  mass: 1,
  stiffness: 180,
  type: "spring",
};
const transition2 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const animation1 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 20,
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Desktop: "m9jSyhRqg", Phone: "gf_Ge1OgG" };
const getProps = ({
  description,
  heading,
  height,
  id,
  number,
  width,
  ...props
}) => {
  return {
    ...props,
    DeMGKHWWt: description ?? props.DeMGKHWWt ?? "Description",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "m9jSyhRqg",
    XRBqy2pAy: number ?? props.XRBqy2pAy ?? "00",
    YEVw3BM0l: heading ?? props.YEVw3BM0l ?? "Heading",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const {
    style,
    className,
    layoutId,
    variant,
    XRBqy2pAy,
    YEVw3BM0l,
    DeMGKHWWt,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "m9jSyhRqg",
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition2,
        children: /*#__PURE__*/ _jsxs(MotionDivWithFX, {
          ...restProps,
          ...gestureHandlers,
          __framer__animate: { transition: transition1 },
          __framer__animateOnce: true,
          __framer__enter: animation,
          __framer__styleAppearEffectEnabled: true,
          __framer__threshold: 0.5,
          __perspectiveFX: false,
          __smartComponentFX: true,
          __targetOpacity: 1,
          className: cx(
            scopingClassNames,
            "framer-1ebf3lc",
            className,
            classNames
          ),
          "data-border": true,
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "m9jSyhRqg",
          ref: ref ?? ref1,
          style: {
            "--border-bottom-width": "0px",
            "--border-color": "rgb(222, 222, 222)",
            "--border-left-width": "0px",
            "--border-right-width": "0px",
            "--border-style": "solid",
            "--border-top-width": "1px",
            backgroundColor:
              "var(--token-d74d16c5-23aa-4649-a2ad-0da8c936dade, rgb(255, 255, 255))",
            ...style,
          },
          ...addPropertyOverrides(
            {
              gf_Ge1OgG: {
                __framer__enter: animation1,
                "data-framer-name": "Phone",
              },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-107dl2g",
              "data-framer-name": "Content",
              layoutDependency: layoutDependency,
              layoutId: "jw2eOFN_2",
              children: [
                /*#__PURE__*/ _jsx(motion.div, {
                  className: "framer-l9eihn",
                  "data-border": true,
                  "data-framer-name": "Number",
                  layoutDependency: layoutDependency,
                  layoutId: "QeSAk7dAM",
                  style: {
                    "--border-bottom-width": "1px",
                    "--border-color": "rgb(222, 222, 222)",
                    "--border-left-width": "1px",
                    "--border-right-width": "1px",
                    "--border-style": "solid",
                    "--border-top-width": "1px",
                    backgroundColor: "rgb(255, 255, 255)",
                    borderBottomLeftRadius: 50,
                    borderBottomRightRadius: 50,
                    borderTopLeftRadius: 50,
                    borderTopRightRadius: 50,
                  },
                  children: /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "SW50ZXItU2VtaUJvbGQ=",
                          "--framer-font-family":
                            '"Inter", "Inter Placeholder", sans-serif',
                          "--framer-font-size": "14px",
                          "--framer-font-weight": "600",
                          "--framer-letter-spacing": "-0.04em",
                          "--framer-line-height": "140%",
                          "--framer-text-alignment": "center",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(11, 11, 12))",
                        },
                        children: "01",
                      }),
                    }),
                    className: "framer-1bj3j2t",
                    "data-framer-name": "01",
                    fonts: ["Inter-SemiBold"],
                    layoutDependency: layoutDependency,
                    layoutId: "saNLa9gTO",
                    style: {
                      "--extracted-r6o4lv": "rgb(11, 11, 12)",
                      "--framer-paragraph-spacing": "0px",
                    },
                    text: XRBqy2pAy,
                    verticalAlignment: "top",
                    withExternalLayout: true,
                  }),
                }),
                /*#__PURE__*/ _jsxs(motion.div, {
                  className: "framer-a670wo",
                  "data-framer-name": "Text",
                  layoutDependency: layoutDependency,
                  layoutId: "tttdhmsg0",
                  children: [
                    /*#__PURE__*/ _jsx(RichText, {
                      __fromCanvasComponent: true,
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.h3, {
                          className: "framer-styles-preset-ddjjzx",
                          "data-styles-preset": "uQRBhygQf",
                          children: "Heading",
                        }),
                      }),
                      className: "framer-ofibl1",
                      "data-framer-name": "Discovery & Strategy",
                      fonts: ["Inter"],
                      layoutDependency: layoutDependency,
                      layoutId: "g5rgaZJsZ",
                      style: { "--framer-paragraph-spacing": "0px" },
                      text: YEVw3BM0l,
                      verticalAlignment: "top",
                      withExternalLayout: true,
                    }),
                    /*#__PURE__*/ _jsx(RichText, {
                      __fromCanvasComponent: true,
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          className: "framer-styles-preset-jnye1g",
                          "data-styles-preset": "xNIXLfFSf",
                          style: {
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, rgba(12, 12, 12, 0.6))",
                          },
                          children:
                            "Choose the plan that best fits your needs. From a solid foundation to a fully optimized solution",
                        }),
                      }),
                      className: "framer-1lcu0le",
                      "data-framer-name":
                        "Choose the plan that best fits your needs. From a solid foundation to a fully optimized solution",
                      fonts: ["Inter"],
                      layoutDependency: layoutDependency,
                      layoutId: "ipp45qvjf",
                      style: {
                        "--extracted-r6o4lv": "rgba(12, 12, 12, 0.6)",
                        "--framer-paragraph-spacing": "0px",
                      },
                      text: DeMGKHWWt,
                      verticalAlignment: "top",
                      withExternalLayout: true,
                    }),
                  ],
                }),
              ],
            }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-d976dv",
              "data-border": true,
              "data-framer-name": "Corner",
              layoutDependency: layoutDependency,
              layoutId: "BIVxC14ce",
              style: {
                "--border-bottom-width": "2px",
                "--border-color":
                  "var(--token-1662617d-fd18-4319-b3da-aa36e5415705, rgb(249, 69, 45))",
                "--border-left-width": "0px",
                "--border-right-width": "2px",
                "--border-style": "solid",
                "--border-top-width": "0px",
                rotate: -90,
              },
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-IgBNJ.framer-15rae5b, .framer-IgBNJ .framer-15rae5b { display: block; }",
  ".framer-IgBNJ.framer-1ebf3lc { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 40px 0px 0px 0px; position: relative; width: 554px; }",
  ".framer-IgBNJ .framer-107dl2g { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
  ".framer-IgBNJ .framer-l9eihn { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 40px; justify-content: center; overflow: visible; padding: 10px; position: relative; width: 40px; }",
  ".framer-IgBNJ .framer-1bj3j2t { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-IgBNJ .framer-a670wo { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
  ".framer-IgBNJ .framer-ofibl1, .framer-IgBNJ .framer-1lcu0le { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-IgBNJ .framer-d976dv { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 9px); position: absolute; right: 0px; top: 30px; width: 9px; z-index: 1; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-IgBNJ.framer-1ebf3lc, .framer-IgBNJ .framer-107dl2g, .framer-IgBNJ .framer-l9eihn, .framer-IgBNJ .framer-a670wo { gap: 0px; } .framer-IgBNJ.framer-1ebf3lc > * { margin: 0px; margin-left: calc(20px / 2); margin-right: calc(20px / 2); } .framer-IgBNJ.framer-1ebf3lc > :first-child, .framer-IgBNJ .framer-107dl2g > :first-child { margin-left: 0px; } .framer-IgBNJ.framer-1ebf3lc > :last-child, .framer-IgBNJ .framer-107dl2g > :last-child { margin-right: 0px; } .framer-IgBNJ .framer-107dl2g > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } .framer-IgBNJ .framer-l9eihn > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-IgBNJ .framer-l9eihn > :first-child, .framer-IgBNJ .framer-a670wo > :first-child { margin-top: 0px; } .framer-IgBNJ .framer-l9eihn > :last-child, .framer-IgBNJ .framer-a670wo > :last-child { margin-bottom: 0px; } .framer-IgBNJ .framer-a670wo > * { margin: 0px; margin-bottom: calc(12px / 2); margin-top: calc(12px / 2); } }",
  ".framer-IgBNJ.framer-v-1g7f7t6.framer-1ebf3lc { padding: 30px 0px 0px 0px; }",
  ".framer-IgBNJ.framer-v-1g7f7t6 .framer-a670wo { gap: 8px; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-IgBNJ.framer-v-1g7f7t6 .framer-a670wo { gap: 0px; } .framer-IgBNJ.framer-v-1g7f7t6 .framer-a670wo > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } .framer-IgBNJ.framer-v-1g7f7t6 .framer-a670wo > :first-child { margin-top: 0px; } .framer-IgBNJ.framer-v-1g7f7t6 .framer-a670wo > :last-child { margin-bottom: 0px; } }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  '.framer-IgBNJ[data-border="true"]::after, .framer-IgBNJ [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 107
 * @framerIntrinsicWidth 554
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"gf_Ge1OgG":{"layout":["fixed","auto"]}}}
 * @framerVariables {"XRBqy2pAy":"number","YEVw3BM0l":"heading","DeMGKHWWt":"description"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerhvQAZuTE8 = withCSS(Component, css, "framer-IgBNJ");
export default FramerhvQAZuTE8;
FramerhvQAZuTE8.displayName = "Process / Item";
FramerhvQAZuTE8.defaultProps = { height: 107, width: 554 };
addPropertyControls(FramerhvQAZuTE8, {
  variant: {
    options: ["m9jSyhRqg", "gf_Ge1OgG"],
    optionTitles: ["Desktop", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  XRBqy2pAy: {
    defaultValue: "00",
    displayTextArea: false,
    title: "Number",
    type: ControlType.String,
  },
  YEVw3BM0l: {
    defaultValue: "Heading",
    displayTextArea: false,
    title: "Heading",
    type: ControlType.String,
  },
  DeMGKHWWt: {
    defaultValue: "Description",
    description: "",
    displayTextArea: false,
    title: "Description",
    type: ControlType.String,
  },
});
addFonts(
  FramerhvQAZuTE8,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/1ZFS7N918ojhhd0nQWdj3jz4w.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerhvQAZuTE8",
      slots: [],
      annotations: {
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"gf_Ge1OgG":{"layout":["fixed","auto"]}}}',
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "554",
        framerIntrinsicHeight: "107",
        framerDisplayContentsDiv: "false",
        framerVariables:
          '{"XRBqy2pAy":"number","YEVw3BM0l":"heading","DeMGKHWWt":"description"}',
        framerContractVersion: "1",
        framerComponentViewportWidth: "true",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./hvQAZuTE8.map
