// Generated by Framer (3e39c08)
import { jsx as _jsx } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  RichText,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const cycleOrder = [
  "mhphXOnUS",
  "kJCs8lIch",
  "Aa9nIlIIa",
  "rIZkxSqwp",
  "af5HvgCFL",
  "krCfdifha",
];
const serializationHash = "framer-gN1Ke";
const variantClassNames = {
  Aa9nIlIIa: "framer-v-16guky3",
  af5HvgCFL: "framer-v-88uftt",
  kJCs8lIch: "framer-v-1jp3995",
  krCfdifha: "framer-v-11t8sog",
  mhphXOnUS: "framer-v-fkk4lf",
  rIZkxSqwp: "framer-v-1ajn3oc",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const eAHGXWjyh = undefined;
const mXpY5N3RA = undefined;
const transition1 = { duration: 0, type: "tween" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "A phone": "krCfdifha",
  "A Tablet": "rIZkxSqwp",
  "D Phone": "af5HvgCFL",
  "D Tablet": "Aa9nIlIIa",
  Active: "kJCs8lIch",
  Default: "mhphXOnUS",
};
const Variants = motion.create(React.Fragment);
const getProps = ({ click, height, id, title, width, ...props }) => {
  return {
    ...props,
    eAHGXWjyh: click ?? props.eAHGXWjyh,
    mXpY5N3RA: title ?? props.mXpY5N3RA ?? "Category",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "mhphXOnUS",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    mXpY5N3RA,
    eAHGXWjyh,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "mhphXOnUS",
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTap1rkcrh4 = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (eAHGXWjyh) {
      const res = await eAHGXWjyh(...args);
      if (res === false) return false;
    }
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-fkk4lf",
            className,
            classNames
          ),
          "data-framer-name": "Default",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "mhphXOnUS",
          onTap: onTap1rkcrh4,
          ref: refBinding,
          style: { ...style },
          ...addPropertyOverrides(
            {
              Aa9nIlIIa: { "data-framer-name": "D Tablet" },
              af5HvgCFL: { "data-framer-name": "D Phone" },
              kJCs8lIch: { "data-framer-name": "Active" },
              krCfdifha: { "data-framer-name": "A phone" },
              rIZkxSqwp: { "data-framer-name": "A Tablet" },
            },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsx(RichText, {
            __fromCanvasComponent: true,
            children: /*#__PURE__*/ _jsx(React.Fragment, {
              children: /*#__PURE__*/ _jsx(motion.p, {
                dir: "auto",
                style: {
                  "--font-selector": "SW50ZXItU2VtaUJvbGQ=",
                  "--framer-font-size": "32px",
                  "--framer-font-weight": "600",
                  "--framer-letter-spacing": "-0.05em",
                  "--framer-line-height": "1.4em",
                  "--framer-text-color":
                    "var(--extracted-r6o4lv, rgba(12, 12, 12, 0.3))",
                },
                children: "Category",
              }),
            }),
            className: "framer-1tyau3b",
            "data-framer-name": "Title",
            fonts: ["Inter-SemiBold"],
            layoutDependency: layoutDependency,
            layoutId: "NtVBScAXe",
            style: { "--extracted-r6o4lv": "rgba(12, 12, 12, 0.3)" },
            text: mXpY5N3RA,
            variants: {
              kJCs8lIch: {
                "--extracted-r6o4lv":
                  "var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12))",
              },
              krCfdifha: {
                "--extracted-r6o4lv":
                  "var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12))",
              },
              rIZkxSqwp: {
                "--extracted-r6o4lv":
                  "var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12))",
              },
            },
            verticalAlignment: "top",
            withExternalLayout: true,
            ...addPropertyOverrides(
              {
                Aa9nIlIIa: {
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      dir: "auto",
                      style: {
                        "--font-selector": "SW50ZXItU2VtaUJvbGQ=",
                        "--framer-font-size": "28px",
                        "--framer-font-weight": "600",
                        "--framer-letter-spacing": "-0.05em",
                        "--framer-line-height": "1.4em",
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, rgba(12, 12, 12, 0.3))",
                      },
                      children: "Category",
                    }),
                  }),
                },
                af5HvgCFL: {
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      dir: "auto",
                      style: {
                        "--font-selector": "SW50ZXItU2VtaUJvbGQ=",
                        "--framer-font-size": "20px",
                        "--framer-font-weight": "600",
                        "--framer-letter-spacing": "-0.05em",
                        "--framer-line-height": "1.4em",
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, rgba(12, 12, 12, 0.3))",
                      },
                      children: "Category",
                    }),
                  }),
                },
                kJCs8lIch: {
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      dir: "auto",
                      style: {
                        "--font-selector": "SW50ZXItU2VtaUJvbGQ=",
                        "--framer-font-size": "32px",
                        "--framer-font-weight": "600",
                        "--framer-letter-spacing": "-0.05em",
                        "--framer-line-height": "1.4em",
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12)))",
                      },
                      children: "Category",
                    }),
                  }),
                },
                krCfdifha: {
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      dir: "auto",
                      style: {
                        "--font-selector": "SW50ZXItU2VtaUJvbGQ=",
                        "--framer-font-size": "20px",
                        "--framer-font-weight": "600",
                        "--framer-letter-spacing": "-0.05em",
                        "--framer-line-height": "1.4em",
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12)))",
                      },
                      children: "Category",
                    }),
                  }),
                },
                rIZkxSqwp: {
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      dir: "auto",
                      style: {
                        "--font-selector": "SW50ZXItU2VtaUJvbGQ=",
                        "--framer-font-size": "28px",
                        "--framer-font-weight": "600",
                        "--framer-letter-spacing": "-0.05em",
                        "--framer-line-height": "1.4em",
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12)))",
                      },
                      children: "Category",
                    }),
                  }),
                },
              },
              baseVariant,
              gestureVariant
            ),
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-gN1Ke.framer-13suprh, .framer-gN1Ke .framer-13suprh { display: block; }",
  ".framer-gN1Ke.framer-fkk4lf { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: min-content; }",
  ".framer-gN1Ke .framer-1tyau3b { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 45
 * @framerIntrinsicWidth 130.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"kJCs8lIch":{"layout":["auto","auto"]},"Aa9nIlIIa":{"layout":["auto","auto"]},"rIZkxSqwp":{"layout":["auto","auto"]},"af5HvgCFL":{"layout":["auto","auto"]},"krCfdifha":{"layout":["auto","auto"]}}}
 * @framerVariables {"mXpY5N3RA":"title","eAHGXWjyh":"click"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const FramerYzJWp9yz0 = withCSS(Component, css, "framer-gN1Ke");
export default FramerYzJWp9yz0;
FramerYzJWp9yz0.displayName = "Tab";
FramerYzJWp9yz0.defaultProps = { height: 45, width: 130.5 };
addPropertyControls(FramerYzJWp9yz0, {
  variant: {
    options: [
      "mhphXOnUS",
      "kJCs8lIch",
      "Aa9nIlIIa",
      "rIZkxSqwp",
      "af5HvgCFL",
      "krCfdifha",
    ],
    optionTitles: [
      "Default",
      "Active",
      "D Tablet",
      "A Tablet",
      "D Phone",
      "A phone",
    ],
    title: "Variant",
    type: ControlType.Enum,
  },
  mXpY5N3RA: {
    defaultValue: "Category",
    displayTextArea: false,
    title: "Title",
    type: ControlType.String,
  },
  onmXpY5N3RAChange: { changes: "mXpY5N3RA", type: ControlType.ChangeHandler },
  eAHGXWjyh: { title: "Click", type: ControlType.EventHandler },
});
addFonts(
  FramerYzJWp9yz0,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
          weight: "600",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
          weight: "600",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
          weight: "600",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
          weight: "600",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
          weight: "600",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/yDtI2UI8XcEg1W2je9XPN3Noo.woff2",
          weight: "600",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
          weight: "600",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerYzJWp9yz0",
      slots: [],
      annotations: {
        framerContractVersion: "1",
        framerIntrinsicWidth: "130.5",
        framerVariables: '{"mXpY5N3RA":"title","eAHGXWjyh":"click"}',
        framerImmutableVariables: "true",
        framerDisplayContentsDiv: "false",
        framerIntrinsicHeight: "45",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"kJCs8lIch":{"layout":["auto","auto"]},"Aa9nIlIIa":{"layout":["auto","auto"]},"rIZkxSqwp":{"layout":["auto","auto"]},"af5HvgCFL":{"layout":["auto","auto"]},"krCfdifha":{"layout":["auto","auto"]}}}',
        framerAutoSizeImages: "true",
        framerColorSyntax: "true",
        framerComponentViewportWidth: "true",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./YzJWp9yz0.map
