// Generated by Framer (c563d2c)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { Icon as Phosphor } from "https://framerusercontent.com/modules/tYScH7LTqUtz5KUaUAYP/p8dptk4UIND8hbFWz9V7/Phosphor.js";
const PhosphorFonts = getFonts(Phosphor);
const serializationHash = "framer-vENHC";
const variantClassNames = { HfiWj2ujF: "framer-v-1e58aod" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
  badgeBGOpacity,
  badgeIconName,
  bGColor,
  color,
  height,
  id,
  text,
  width,
  ...props
}) => {
  return {
    ...props,
    fNIfKedye: text ?? props.fNIfKedye ?? "Text",
    lbHyc7_1a: badgeIconName ?? props.lbHyc7_1a ?? "fire",
    M43wJ6KEW: bGColor ?? props.M43wJ6KEW ?? "rgb(255, 243, 241)",
    tlTcxOvUU:
      color ??
      props.tlTcxOvUU ??
      "var(--token-1662617d-fd18-4319-b3da-aa36e5415705, rgb(249, 69, 45))",
    ZK6JFFNEQ: badgeBGOpacity ?? props.ZK6JFFNEQ ?? 0.08,
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const {
    style,
    className,
    layoutId,
    variant,
    fNIfKedye,
    tlTcxOvUU,
    M43wJ6KEW,
    ZK6JFFNEQ,
    lbHyc7_1a,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "HfiWj2ujF",
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-1e58aod",
            className,
            classNames
          ),
          "data-framer-name": "Badge",
          layoutDependency: layoutDependency,
          layoutId: "HfiWj2ujF",
          ref: ref ?? ref1,
          style: {
            borderBottomLeftRadius: 50,
            borderBottomRightRadius: 50,
            borderTopLeftRadius: 50,
            borderTopRightRadius: 50,
            ...style,
          },
          children: [
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              children: /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-wepynj-container",
                layoutDependency: layoutDependency,
                layoutId: "pFOiDOJ_D-container",
                children: /*#__PURE__*/ _jsx(Phosphor, {
                  color: tlTcxOvUU,
                  height: "100%",
                  iconSearch: lbHyc7_1a,
                  iconSelection: "House",
                  id: "pFOiDOJ_D",
                  layoutId: "pFOiDOJ_D",
                  mirrored: false,
                  selectByList: false,
                  style: { height: "100%", width: "100%" },
                  weight: "regular",
                  width: "100%",
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  style: {
                    "--font-selector": "SW50ZXItU2VtaUJvbGQ=",
                    "--framer-font-family":
                      '"Inter", "Inter Placeholder", sans-serif',
                    "--framer-font-size": "12px",
                    "--framer-font-weight": "600",
                    "--framer-letter-spacing": "-0.04em",
                    "--framer-line-height": "140%",
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, var(--variable-reference-tlTcxOvUU-MAxy_g2Et))",
                  },
                  children: "Text",
                }),
              }),
              className: "framer-8mpvl0",
              "data-framer-name": "Most popular",
              fonts: ["Inter-SemiBold"],
              layoutDependency: layoutDependency,
              layoutId: "rpD7Hrvkl",
              style: {
                "--extracted-r6o4lv":
                  "var(--variable-reference-tlTcxOvUU-MAxy_g2Et)",
                "--framer-paragraph-spacing": "0px",
                "--variable-reference-tlTcxOvUU-MAxy_g2Et": tlTcxOvUU,
              },
              text: fNIfKedye,
              verticalAlignment: "top",
              withExternalLayout: true,
            }),
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-15qi64y",
              "data-framer-name": "BG",
              layoutDependency: layoutDependency,
              layoutId: "y9xe6kKwI",
              style: { backgroundColor: M43wJ6KEW, opacity: ZK6JFFNEQ },
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-vENHC.framer-b6xpjr, .framer-vENHC .framer-b6xpjr { display: block; }",
  ".framer-vENHC.framer-1e58aod { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: hidden; padding: 5px 10px 5px 10px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
  ".framer-vENHC .framer-wepynj-container { flex: none; height: 17px; position: relative; width: 17px; z-index: 1; }",
  ".framer-vENHC .framer-8mpvl0 { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 1; }",
  ".framer-vENHC .framer-15qi64y { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; z-index: 0; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-vENHC.framer-1e58aod { gap: 0px; } .framer-vENHC.framer-1e58aod > * { margin: 0px; margin-left: calc(6px / 2); margin-right: calc(6px / 2); } .framer-vENHC.framer-1e58aod > :first-child { margin-left: 0px; } .framer-vENHC.framer-1e58aod > :last-child { margin-right: 0px; } }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 27
 * @framerIntrinsicWidth 66
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}
 * @framerVariables {"fNIfKedye":"text","tlTcxOvUU":"color","M43wJ6KEW":"bGColor","ZK6JFFNEQ":"badgeBGOpacity","lbHyc7_1a":"badgeIconName"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerMAxy_g2Et = withCSS(Component, css, "framer-vENHC");
export default FramerMAxy_g2Et;
FramerMAxy_g2Et.displayName = "Pricing / Badge";
FramerMAxy_g2Et.defaultProps = { height: 27, width: 66 };
addPropertyControls(FramerMAxy_g2Et, {
  fNIfKedye: {
    defaultValue: "Text",
    description: "",
    displayTextArea: false,
    title: "Text",
    type: ControlType.String,
  },
  tlTcxOvUU: {
    defaultValue:
      "var(--token-1662617d-fd18-4319-b3da-aa36e5415705, rgb(249, 69, 45))",
    title: "Color",
    type: ControlType.Color,
  },
  M43wJ6KEW: {
    defaultValue: "rgb(255, 243, 241)",
    title: "BG color",
    type: ControlType.Color,
  },
  ZK6JFFNEQ: {
    defaultValue: 0.08,
    max: 1,
    min: 0,
    step: 0.01,
    title: "Badge BG opacity",
    type: ControlType.Number,
  },
  lbHyc7_1a: {
    defaultValue: "fire",
    description: "",
    placeholder: "",
    title: "Badge icon name",
    type: ControlType.String,
  },
});
addFonts(
  FramerMAxy_g2Et,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/1ZFS7N918ojhhd0nQWdj3jz4w.woff2",
          weight: "600",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
          weight: "600",
        },
      ],
    },
    ...PhosphorFonts,
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerMAxy_g2Et",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]}}}',
        framerContractVersion: "1",
        framerIntrinsicWidth: "66",
        framerDisplayContentsDiv: "false",
        framerComponentViewportWidth: "true",
        framerIntrinsicHeight: "27",
        framerVariables:
          '{"fNIfKedye":"text","tlTcxOvUU":"color","M43wJ6KEW":"bGColor","ZK6JFFNEQ":"badgeBGOpacity","lbHyc7_1a":"badgeIconName"}',
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./MAxy_g2Et.map
