// Generated by Framer (915daba)
import { fontStore } from "framer";
fontStore.loadFonts([]);
export const fonts = [{ explicitInter: true, fonts: [] }];
export const css = [
  ".framer-c9tmr .framer-styles-preset-bq16ho:not(.rich-text-wrapper), .framer-c9tmr .framer-styles-preset-bq16ho.rich-text-wrapper a { --framer-link-current-text-color: var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, #0c0c0c); --framer-link-current-text-decoration: none; --framer-link-hover-text-color: var(--token-1662617d-fd18-4319-b3da-aa36e5415705, #f9452d); --framer-link-hover-text-decoration: none; --framer-link-text-color: var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, #0c0c0c); --framer-link-text-decoration: none; transition: color 0.3s cubic-bezier(0.44, 0, 0.56, 1) 0s; }",
];
export const className = "framer-c9tmr";
export const __FramerMetadata__ = {
  exports: {
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
