// Generated by Framer (a72a541)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  ComponentViewportProvider,
  Container,
  cx,
  GeneratedComponentContext,
  getFonts,
  PropertyOverrides,
  RenderTarget,
  useCustomCursors,
  useHydratedBreakpointVariants,
  useIsOnFramerCanvas,
  useLocaleInfo,
  withCSS,
  withFX,
  withOptimizedAppearEffect,
} from "framer";
import { LayoutGroup, motion } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import PurchaseButton from "#framer/local/canvasComponent/KXe1SN4YX/KXe1SN4YX.js";
import Footer from "#framer/local/canvasComponent/pCkRDSIIx/pCkRDSIIx.js";
const PurchaseButtonFonts = getFonts(PurchaseButton);
const ContainerWithOptimizedAppearEffect = withOptimizedAppearEffect(Container);
const FooterFonts = getFonts(Footer);
const ContainerWithFX = withFX(Container);
const breakpoints = {
  eo4RnHE2_: "(max-width: 809.98px)",
  s4_g12Ipq: "(min-width: 1200px)",
  V1u6rnvwv: "(min-width: 810px) and (max-width: 1199.98px)",
};
const isBrowser = () => typeof document !== "undefined";
const serializationHash = "framer-ahDeY";
const variantClassNames = {
  eo4RnHE2_: "framer-v-17ruhlu",
  s4_g12Ipq: "framer-v-193bvef",
  V1u6rnvwv: "framer-v-1dc2pdl",
};
const transition1 = {
  damping: 30,
  delay: 1.8,
  mass: 1,
  stiffness: 235,
  type: "spring",
};
const animation = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: 0,
  y: 0,
};
const animation1 = {
  opacity: 0.001,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 40,
};
const addImageAlt = (image, alt) => {
  if (!image || typeof image !== "object") {
    return;
  }
  return { ...image, alt };
};
const breakpointRules = {
  eo4RnHE2_: [
    ".framer-ahDeY .framer-wbze5i-container { order: 1002; }",
    ".framer-ahDeY .framer-1a4qqw4-container { order: 1001; }",
  ],
};
const breakpointKeys = Object.keys(breakpointRules);
const selectors = { eo4RnHE2_: ".framer-17ruhlu-override" };
const rules = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-ahDeY.framer-1ehxovb, .framer-ahDeY .framer-1ehxovb { display: block; }",
  '.framer-ahDeY.framer-193bvef { --selection-background-color: var(--token-1662617d-fd18-4319-b3da-aa36e5415705, #f9452d) /* {"name":"Primary"} */; --selection-color: var(--token-d74d16c5-23aa-4649-a2ad-0da8c936dade, #ffffff) /* {"name":"White"} */; align-content: center; align-items: center; background-color: var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, #0c0c0c); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 100%; }',
  ".framer-ahDeY .framer-1d1rntb { background: transparent; flex-grow: 1; height: 0px; margin: 0px; margin-bottom: -0px; position: relative; width: 0px; }",
  ".framer-ahDeY .framer-wbze5i-container { bottom: calc(calc(100% - min(var(--framer-viewport-height, 100%), 100%)) + 60px); flex: none; height: auto; order: 1001; position: var(--framer-canvas-fixed-position, fixed); right: 20px; width: auto; will-change: var(--framer-will-change-effect-override, transform); z-index: 10; }",
  ".framer-ahDeY .framer-1a4qqw4-container { flex: none; height: auto; order: 1002; position: relative; width: 100%; }",
  '[data-layout-template="true"] > #overlay { margin-bottom: -0px; }',
  '.framer-ahDeY[data-selection="true"] * ::selection, .framer-ahDeY [data-selection="true"] * ::selection { color: var(--selection-color, none); background-color: var(--selection-background-color, none); }',
];
const mediaQueries = {
  eo4RnHE2_: "(max-width: 809.98px)",
  s4_g12Ipq: "(min-width: 1200px)",
  V1u6rnvwv: "(min-width: 810px) and (max-width: 1199.98px)",
};
const HTMLStyle = ({ value }) => {
  const onCanvas = useIsOnFramerCanvas();
  if (onCanvas) return null;
  return /*#__PURE__*/ _jsx("style", {
    dangerouslySetInnerHTML: { __html: value },
    "data-framer-html-style": "",
  });
};
const humanReadableVariantMap = {
  Desktop: "s4_g12Ipq",
  Phone: "eo4RnHE2_",
  Tablet: "V1u6rnvwv",
};
const getProps = ({ height, id, width, ...props }) => {
  return {
    ...props,
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "s4_g12Ipq",
  };
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, children, ...restProps } =
    getProps(props);
  const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(
    variant,
    breakpoints,
    false
  );
  const gestureVariant = undefined;
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  useCustomCursors({});
  return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
    value: {
      isLayoutTemplate: true,
      primaryVariantId: "s4_g12Ipq",
      variantClassNames,
    },
    children: /*#__PURE__*/ _jsxs(LayoutGroup, {
      id: layoutId ?? defaultLayoutId,
      children: [
        /*#__PURE__*/ _jsx(HTMLStyle, {
          value:
            ":root body { background: var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12)); }",
        }),
        /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          className: cx(scopingClassNames, "framer-193bvef", className),
          "data-layout-template": true,
          "data-selection": true,
          ref: refBinding,
          style: { ...style },
          children: [
            children,
            /*#__PURE__*/ _jsx("div", { className: "framer-1d1rntb" }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 46,
              y: 894,
              children: /*#__PURE__*/ _jsx(ContainerWithOptimizedAppearEffect, {
                animate: animation,
                className: "framer-wbze5i-container",
                "data-framer-appear-id": "wbze5i",
                initial: animation1,
                layoutScroll: true,
                nodeId: "hXq_h1Erl",
                optimized: true,
                rendersWithMotion: true,
                scopeId: "ht8TFGtn1",
                children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                  breakpoint: baseVariant,
                  overrides: { eo4RnHE2_: { variant: "Q1VcTeAbQ" } },
                  children: /*#__PURE__*/ _jsx(PurchaseButton, {
                    avLtJQZr4: addImageAlt(
                      {
                        pixelHeight: 98,
                        pixelWidth: 130,
                        src: "https://framerusercontent.com/images/NAc0rqyjZ860lyzTnxAxYIbsKM.jpg?width=130&height=98",
                      },
                      ""
                    ),
                    height: "100%",
                    id: "hXq_h1Erl",
                    LaRWZ1Hqy: "https://templifica.com/framer-templates/thebrandle",
                    layoutId: "hXq_h1Erl",
                    MSLk_tJaN: "$129",
                    variant: "kBKUB8MVo",
                    width: "100%",
                  }),
                }),
              }),
            }),
            /*#__PURE__*/ _jsx(ComponentViewportProvider, {
              height: 732,
              width: "100vw",
              y: 1e3,
              children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                breakpoint: baseVariant,
                overrides: {
                  eo4RnHE2_: {
                    __framer__styleTransformEffectEnabled: undefined,
                  },
                },
                children: /*#__PURE__*/ _jsx(ContainerWithFX, {
                  __framer__styleTransformEffectEnabled: true,
                  __framer__transformTargets: [
                    {
                      target: {
                        opacity: 1,
                        rotate: 0,
                        rotateX: 0,
                        rotateY: 0,
                        scale: 1,
                        skewX: 0,
                        skewY: 0,
                        x: 0,
                        y: -170,
                      },
                    },
                    {
                      target: {
                        opacity: 1,
                        rotate: 0,
                        rotateX: 0,
                        rotateY: 0,
                        scale: 1,
                        skewX: 0,
                        skewY: 0,
                        x: 0,
                        y: 0,
                      },
                    },
                  ],
                  __framer__transformTrigger: "onInView",
                  __perspectiveFX: false,
                  __targetOpacity: 1,
                  className: "framer-1a4qqw4-container",
                  nodeId: "FyU9ddyy9",
                  rendersWithMotion: true,
                  scopeId: "ht8TFGtn1",
                  children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                    breakpoint: baseVariant,
                    overrides: {
                      eo4RnHE2_: { variant: "j_Wa_NyZf" },
                      V1u6rnvwv: { variant: "Zqhe2SOK3" },
                    },
                    children: /*#__PURE__*/ _jsx(Footer, {
                      height: "100%",
                      id: "FyU9ddyy9",
                      layoutId: "FyU9ddyy9",
                      style: { width: "100%" },
                      variant: "MNs46yKnk",
                      width: "100%",
                    }),
                  }),
                }),
              }),
            }),
          ],
        }),
        /*#__PURE__*/ _jsx("div", { id: "template-overlay" }),
      ],
    }),
  });
});
const css = (target) => {
  const isStaticRenderer =
    target === RenderTarget.canvas || target === RenderTarget.export;
  if (!isStaticRenderer) {
    return [
      ...rules,
      ...breakpointKeys.map((key) => {
        const query = mediaQueries[key];
        return `@media ${query} { ${breakpointRules[key].join(" ")} }`;
      }),
    ];
  }
  return [
    ...rules,
    ...breakpointKeys.flatMap((key) => {
      const selector = selectors[key];
      return breakpointRules[key].map((rule) => `${selector} {${rule}}`);
    }),
  ];
};
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 1200
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"V1u6rnvwv":{"layout":["fixed","fixed"]},"eo4RnHE2_":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerHitTargets {"s4_g12Ipq":[".framer-wbze5i-container",".framer-1a4qqw4-container"],"V1u6rnvwv":[".framer-wbze5i-container",".framer-1a4qqw4-container"],"eo4RnHE2_":[".framer-wbze5i-container",".framer-1a4qqw4-container"]}
 * @framerBreakpoints {"s4_g12Ipq":{"min":1200,"canvasClassName":"framer-193bvef-override","minHeight":1200,"viewportHeight":1035,"name":"Desktop","width":1200,"rootFontSize":16},"V1u6rnvwv":{"min":810,"max":1199,"canvasClassName":"framer-1dc2pdl-override","minHeight":1200,"viewportHeight":1080,"name":"Tablet","width":810,"rootFontSize":16},"eo4RnHE2_":{"max":809,"canvasClassName":"framer-17ruhlu-override","minHeight":1200,"viewportHeight":844,"name":"Phone","width":390,"rootFontSize":16}}
 * @framerDefaultVariant s4_g12Ipq
 * @framerLayoutTemplate true
 */ const Framerht8TFGtn1 = withCSS(Component, css, "framer-ahDeY");
export default Framerht8TFGtn1;
Framerht8TFGtn1.displayName = "Main";
Framerht8TFGtn1.defaultProps = { height: 1200, width: 1200 };
addFonts(
  Framerht8TFGtn1,
  [{ explicitInter: true, fonts: [] }, ...PurchaseButtonFonts, ...FooterFonts],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Framerht8TFGtn1",
      slots: [],
      annotations: {
        framerBreakpoints:
          '{"s4_g12Ipq":{"min":1200,"canvasClassName":"framer-193bvef-override","minHeight":1200,"viewportHeight":1035,"name":"Desktop","width":1200,"rootFontSize":16},"V1u6rnvwv":{"min":810,"max":1199,"canvasClassName":"framer-1dc2pdl-override","minHeight":1200,"viewportHeight":1080,"name":"Tablet","width":810,"rootFontSize":16},"eo4RnHE2_":{"max":809,"canvasClassName":"framer-17ruhlu-override","minHeight":1200,"viewportHeight":844,"name":"Phone","width":390,"rootFontSize":16}}',
        framerComponentViewportWidth: "true",
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"V1u6rnvwv":{"layout":["fixed","fixed"]},"eo4RnHE2_":{"layout":["fixed","fixed"]}}}',
        framerColorSyntax: "true",
        framerHitTargets:
          '{"s4_g12Ipq":[".framer-wbze5i-container",".framer-1a4qqw4-container"],"V1u6rnvwv":[".framer-wbze5i-container",".framer-1a4qqw4-container"],"eo4RnHE2_":[".framer-wbze5i-container",".framer-1a4qqw4-container"]}',
        framerDisplayContentsDiv: "false",
        framerDefaultVariant: "s4_g12Ipq",
        framerLayoutTemplate: "true",
        framerIntrinsicWidth: "1200",
        framerAutoSizeImages: "true",
        framerContractVersion: "1",
        framerIntrinsicHeight: "1200",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
