// Generated by Framer (8e1ebfe)
import siteMetadata from "https://framerusercontent.com/modules/eyMZGqW4TboB8nelLraT/FLOxzSN8KbyLWhj5xImR/siteMetadata.js";
export default function metadata(params, activeLocale) {
  return {
    breakpoints: [
      { hash: "72rtr7", mediaQuery: "(min-width: 1200px)" },
      {
        hash: "13dhfrl",
        mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)",
      },
      { hash: "233qk8", mediaQuery: "(max-width: 809.98px)" },
    ],
    description: siteMetadata(params, activeLocale).description,
    elements: {
      dQ2OT4jvd: "work",
      S6U36AThY: "pricing",
      uhPAu4sKG: "description",
      xS34N4gbY: "benefits",
    },
    robots: "max-image-preview:large",
    serializationId: "framer-XEwcd",
    title: siteMetadata(params, activeLocale).title || "Home",
    viewport: "width=device-width",
  };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
  exports: {
    metadataVersion: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    default: { type: "function", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
