// Generated by Framer (3266cfb)
import {
  addPropertyControls as e,
  ControlType as l,
  QueryCache as t,
  QueryEngine as r,
} from "framer";
import {
  DatabaseCollection as a,
  DatabaseDictionaryIndex as m,
} from "./YIWnW45d9-0.js";
import { resolveRichText as i } from "./YIWnW45d9-1.js";
let n = {
    g1I5MiAVj: { isNullable: !0, type: l.String },
    id: { isNullable: !1, type: l.String },
    inRxvcKDG: { isNullable: !0, type: l.String },
    jkwxRloLl: { isNullable: !0, type: l.String },
    L1yFlWdpt: { isNullable: !0, type: l.ResponsiveImage },
    l79ytPVv8: { isNullable: !0, type: l.Date },
    nextItemId: { isNullable: !0, type: l.String },
    oQ8S_DTXv: { isNullable: !0, type: l.String },
    previousItemId: { isNullable: !0, type: l.String },
    QLVm9luAJ: { isNullable: !0, type: l.RichText },
    r01Ash4Ku: { isNullable: !0, type: l.ResponsiveImage },
    VtVfjuqnn: { isNullable: !0, type: l.String },
    wxze6Ee9F: { isNullable: !0, type: l.String },
    XfOMTUCoI: { isNullable: !0, type: l.String },
    Y1qjiNgfF: { isNullable: !0, type: l.ResponsiveImage },
  },
  o = ["id", "QLVm9luAJ"],
  u = { type: 1 },
  c = ["previousItemId", "QLVm9luAJ"],
  s = ["nextItemId", "QLVm9luAJ"],
  d = ["id", "g1I5MiAVj"],
  f = ["g1I5MiAVj", "id"],
  p = ["wxze6Ee9F", "QLVm9luAJ"],
  g = { type: 0 },
  I = ["VtVfjuqnn", "QLVm9luAJ"],
  y = ["g1I5MiAVj", "QLVm9luAJ"],
  h = ["l79ytPVv8", "QLVm9luAJ"],
  w = ["r01Ash4Ku", "QLVm9luAJ"],
  L = ["oQ8S_DTXv", "QLVm9luAJ"],
  V = ["XfOMTUCoI", "QLVm9luAJ"],
  W = ["L1yFlWdpt", "QLVm9luAJ"],
  S = ["jkwxRloLl", "QLVm9luAJ"],
  N = ["inRxvcKDG", "QLVm9luAJ"],
  x = ["Y1qjiNgfF", "QLVm9luAJ"],
  R = ["QLVm9luAJ", "QLVm9luAJ"],
  A = new r(),
  Y = new t(A),
  v = {
    collectionByLocaleId: {
      default: new a({
        chunks: [
          new URL(
            "./YIWnW45d9-chunk-default-0.framercms",
            "https://framerusercontent.com/modules/Rz2XBRokUigii15Sw6os/q7SwmiB0hefwPHfYnSVo/YIWnW45d9.js"
          ).href.replace("/modules/", "/cms/"),
        ],
        indexes: [
          new m({
            collation: u,
            collectionSchema: n,
            fieldNames: o,
            range: { from: 0, to: 328 },
            url: new URL(
              "./YIWnW45d9-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/Rz2XBRokUigii15Sw6os/q7SwmiB0hefwPHfYnSVo/YIWnW45d9.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new m({
            collation: u,
            collectionSchema: n,
            fieldNames: c,
            range: { from: 328, to: 655 },
            url: new URL(
              "./YIWnW45d9-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/Rz2XBRokUigii15Sw6os/q7SwmiB0hefwPHfYnSVo/YIWnW45d9.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new m({
            collation: u,
            collectionSchema: n,
            fieldNames: s,
            range: { from: 655, to: 978 },
            url: new URL(
              "./YIWnW45d9-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/Rz2XBRokUigii15Sw6os/q7SwmiB0hefwPHfYnSVo/YIWnW45d9.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new m({
            collation: u,
            collectionSchema: n,
            fieldNames: d,
            range: { from: 978, to: 1847 },
            url: new URL(
              "./YIWnW45d9-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/Rz2XBRokUigii15Sw6os/q7SwmiB0hefwPHfYnSVo/YIWnW45d9.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new m({
            collation: u,
            collectionSchema: n,
            fieldNames: f,
            range: { from: 1847, to: 2716 },
            url: new URL(
              "./YIWnW45d9-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/Rz2XBRokUigii15Sw6os/q7SwmiB0hefwPHfYnSVo/YIWnW45d9.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new m({
            collation: g,
            collectionSchema: n,
            fieldNames: p,
            range: { from: 2716, to: 3516 },
            url: new URL(
              "./YIWnW45d9-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/Rz2XBRokUigii15Sw6os/q7SwmiB0hefwPHfYnSVo/YIWnW45d9.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new m({
            collation: g,
            collectionSchema: n,
            fieldNames: I,
            range: { from: 3516, to: 4607 },
            url: new URL(
              "./YIWnW45d9-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/Rz2XBRokUigii15Sw6os/q7SwmiB0hefwPHfYnSVo/YIWnW45d9.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new m({
            collation: g,
            collectionSchema: n,
            fieldNames: y,
            range: { from: 4607, to: 5393 },
            url: new URL(
              "./YIWnW45d9-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/Rz2XBRokUigii15Sw6os/q7SwmiB0hefwPHfYnSVo/YIWnW45d9.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new m({
            collation: g,
            collectionSchema: n,
            fieldNames: h,
            range: { from: 5393, to: 5678 },
            url: new URL(
              "./YIWnW45d9-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/Rz2XBRokUigii15Sw6os/q7SwmiB0hefwPHfYnSVo/YIWnW45d9.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new m({
            collation: g,
            collectionSchema: n,
            fieldNames: w,
            range: { from: 5678, to: 9969 },
            url: new URL(
              "./YIWnW45d9-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/Rz2XBRokUigii15Sw6os/q7SwmiB0hefwPHfYnSVo/YIWnW45d9.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new m({
            collation: g,
            collectionSchema: n,
            fieldNames: L,
            range: { from: 9969, to: 10324 },
            url: new URL(
              "./YIWnW45d9-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/Rz2XBRokUigii15Sw6os/q7SwmiB0hefwPHfYnSVo/YIWnW45d9.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new m({
            collation: g,
            collectionSchema: n,
            fieldNames: V,
            range: { from: 10324, to: 10839 },
            url: new URL(
              "./YIWnW45d9-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/Rz2XBRokUigii15Sw6os/q7SwmiB0hefwPHfYnSVo/YIWnW45d9.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new m({
            collation: g,
            collectionSchema: n,
            fieldNames: W,
            range: { from: 10839, to: 12292 },
            url: new URL(
              "./YIWnW45d9-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/Rz2XBRokUigii15Sw6os/q7SwmiB0hefwPHfYnSVo/YIWnW45d9.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new m({
            collation: g,
            collectionSchema: n,
            fieldNames: S,
            range: { from: 12292, to: 14357 },
            url: new URL(
              "./YIWnW45d9-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/Rz2XBRokUigii15Sw6os/q7SwmiB0hefwPHfYnSVo/YIWnW45d9.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new m({
            collation: g,
            collectionSchema: n,
            fieldNames: N,
            range: { from: 14357, to: 16562 },
            url: new URL(
              "./YIWnW45d9-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/Rz2XBRokUigii15Sw6os/q7SwmiB0hefwPHfYnSVo/YIWnW45d9.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new m({
            collation: g,
            collectionSchema: n,
            fieldNames: x,
            range: { from: 16562, to: 20667 },
            url: new URL(
              "./YIWnW45d9-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/Rz2XBRokUigii15Sw6os/q7SwmiB0hefwPHfYnSVo/YIWnW45d9.js"
            ).href.replace("/modules/", "/cms/"),
          }),
          new m({
            collation: g,
            collectionSchema: n,
            fieldNames: R,
            range: { from: 20667, to: 20912 },
            url: new URL(
              "./YIWnW45d9-indexes-default-0.framercms",
              "https://framerusercontent.com/modules/Rz2XBRokUigii15Sw6os/q7SwmiB0hefwPHfYnSVo/YIWnW45d9.js"
            ).href.replace("/modules/", "/cms/"),
          }),
        ],
        resolveRichText: i,
        schema: n,
      }),
    },
    displayName: "Article",
  };
export default v;
e(v, {
  wxze6Ee9F: { defaultValue: "", title: "Title", type: l.String },
  VtVfjuqnn: { defaultValue: "", title: "Short description", type: l.String },
  g1I5MiAVj: { title: "Slug", type: l.String },
  l79ytPVv8: { defaultValue: "", title: "Date", type: l.Date },
  r01Ash4Ku: { title: "Image", type: l.ResponsiveImage },
  oQ8S_DTXv: { defaultValue: "", title: "Author", type: l.String },
  XfOMTUCoI: { defaultValue: "", title: "Author's occupation", type: l.String },
  L1yFlWdpt: { title: "Author's avatar", type: l.ResponsiveImage },
  jkwxRloLl: { defaultValue: "", title: "Intro huge", type: l.String },
  inRxvcKDG: { defaultValue: "", title: "Intro small", type: l.String },
  Y1qjiNgfF: { title: "Content image", type: l.ResponsiveImage },
  QLVm9luAJ: { defaultValue: "", title: "Content", type: l.RichText },
  previousItemId: {
    dataIdentifier: "local-module:collection/YIWnW45d9:default",
    title: "Previous",
    type: l.CollectionReference,
  },
  nextItemId: {
    dataIdentifier: "local-module:collection/YIWnW45d9:default",
    title: "Next",
    type: l.CollectionReference,
  },
});
export const enumToDisplayNameFunctions = {};
export const utils = {
  async getSlugByRecordId(e, l) {
    let [t] = await Y.get(
      {
        from: { data: v, type: "Collection" },
        limit: { type: "LiteralValue", value: 1 },
        select: [{ name: "g1I5MiAVj", type: "Identifier" }],
        where: {
          left: { name: "id", type: "Identifier" },
          operator: "==",
          right: { type: "LiteralValue", value: e },
          type: "BinaryOperation",
        },
      },
      l
    ).readAsync();
    return t?.g1I5MiAVj;
  },
  async getRecordIdBySlug(e, l) {
    let [t] = await Y.get(
      {
        from: { data: v, type: "Collection" },
        limit: { type: "LiteralValue", value: 1 },
        select: [{ name: "id", type: "Identifier" }],
        where: {
          left: { name: "g1I5MiAVj", type: "Identifier" },
          operator: "==",
          right: { type: "LiteralValue", value: e },
          type: "BinaryOperation",
        },
      },
      l
    ).readAsync();
    return t?.id;
  },
};
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "data",
      name: "data",
      annotations: {
        framerColorSyntax: "false",
        framerRecordIdKey: "id",
        framerData: "",
        framerSlug: "g1I5MiAVj",
        framerContractVersion: "1",
        framerAutoSizeImages: "true",
        framerCollectionUtils: "1",
        framerEnumToDisplayNameUtils: "2",
        framerCollectionId: "YIWnW45d9",
      },
    },
    utils: { type: "variable", annotations: { framerContractVersion: "1" } },
    enumToDisplayNameFunctions: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
