// Generated by Framer (6f76210)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  RichText,
  useActiveVariantCallback,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
const MotionDivWithFX = withFX(motion.div);
const cycleOrder = [
  "I5anvyWOt",
  "wNupTgeBX",
  "D_0PvXkKg",
  "sU_9MvVyf",
  "DY4InP0NL",
  "OM0T28LIR",
];
const serializationHash = "framer-80AfW";
const variantClassNames = {
  D_0PvXkKg: "framer-v-pz4gxq",
  DY4InP0NL: "framer-v-1wdw0ve",
  I5anvyWOt: "framer-v-1vftdq5",
  OM0T28LIR: "framer-v-16tri3p",
  sU_9MvVyf: "framer-v-1hgpdev",
  wNupTgeBX: "framer-v-10t5t6l",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) => variant && Object.assign(nextOverrides, overrides[variant])
      );
  return nextOverrides;
}
const animation = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 30,
  y: 0,
};
const transition1 = {
  delay: 0,
  duration: 1,
  ease: [0.22, 1, 0.36, 1],
  type: "tween",
};
const animation1 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: 30,
  y: 0,
};
const transition2 = {
  delay: 0,
  duration: 0.4,
  ease: [0.68, 0, 0.16, 0.97],
  type: "tween",
};
const animation2 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  x: 20,
  y: 0,
};
const animation3 = {
  opacity: 0,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition1,
  x: 20,
  y: 0,
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition =
    value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Desktop active": "I5anvyWOt",
  "Desktop inactive": "wNupTgeBX",
  "Phone active": "DY4InP0NL",
  "Phone inactive": "OM0T28LIR",
  "Tablet active": "D_0PvXkKg",
  "Tablet inative": "sU_9MvVyf",
};
const getProps = ({
  height,
  id,
  mouseEnter,
  number,
  title,
  width,
  ...props
}) => {
  var _ref, _humanReadableVariantMap_props_variant, _ref1, _ref2;
  return {
    ...props,
    fErYKCICq:
      (_ref = title !== null && title !== void 0 ? title : props.fErYKCICq) !==
        null && _ref !== void 0
        ? _ref
        : "Title",
    KrXbsPILD:
      mouseEnter !== null && mouseEnter !== void 0
        ? mouseEnter
        : props.KrXbsPILD,
    variant:
      (_ref1 =
        (_humanReadableVariantMap_props_variant =
          humanReadableVariantMap[props.variant]) !== null &&
        _humanReadableVariantMap_props_variant !== void 0
          ? _humanReadableVariantMap_props_variant
          : props.variant) !== null && _ref1 !== void 0
        ? _ref1
        : "I5anvyWOt",
    yB44CUche:
      (_ref2 =
        number !== null && number !== void 0 ? number : props.yB44CUche) !==
        null && _ref2 !== void 0
        ? _ref2
        : "00",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const {
    style,
    className,
    layoutId,
    variant,
    fErYKCICq,
    yB44CUche,
    KrXbsPILD,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "I5anvyWOt",
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onMouseEnter10pbwk0 = activeVariantCallback(async (...args) => {
    setGestureState({ isHovered: true });
    if (KrXbsPILD) {
      const res = await KrXbsPILD(...args);
      if (res === false) return false;
    }
  });
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition2,
        children: /*#__PURE__*/ _jsx(MotionDivWithFX, {
          ...restProps,
          ...gestureHandlers,
          __framer__animate: { transition: transition1 },
          __framer__animateOnce: true,
          __framer__enter: animation,
          __framer__exit: animation1,
          __framer__styleAppearEffectEnabled: true,
          __framer__threshold: 0.5,
          __perspectiveFX: false,
          __smartComponentFX: true,
          __targetOpacity: 1,
          className: cx(
            serializationHash,
            ...sharedStyleClassNames,
            "framer-1vftdq5",
            className,
            classNames
          ),
          "data-border": true,
          "data-framer-name": "Desktop active",
          "data-highlight": true,
          layoutDependency: layoutDependency,
          layoutId: "I5anvyWOt",
          onMouseEnter: onMouseEnter10pbwk0,
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: {
            "--border-bottom-width": "1px",
            "--border-color": "rgb(50, 50, 50)",
            "--border-left-width": "0px",
            "--border-right-width": "0px",
            "--border-style": "solid",
            "--border-top-width": "0px",
            ...style,
          },
          ...addPropertyOverrides(
            {
              D_0PvXkKg: { "data-framer-name": "Tablet active" },
              DY4InP0NL: {
                __framer__enter: animation2,
                __framer__exit: animation3,
                "data-framer-name": "Phone active",
              },
              OM0T28LIR: {
                __framer__enter: animation2,
                __framer__exit: animation3,
                "data-framer-name": "Phone inactive",
              },
              sU_9MvVyf: { "data-framer-name": "Tablet inative" },
              wNupTgeBX: { "data-framer-name": "Desktop inactive" },
            },
            baseVariant,
            gestureVariant
          ),
          children: /*#__PURE__*/ _jsxs(motion.div, {
            className: "framer-1i8uvxx",
            "data-framer-name": "Container",
            layoutDependency: layoutDependency,
            layoutId: "AibRWKCID",
            children: [
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    style: {
                      "--font-selector": "SW50ZXItTWVkaXVt",
                      "--framer-font-family":
                        '"Inter", "Inter Placeholder", sans-serif',
                      "--framer-font-size": "102px",
                      "--framer-font-weight": "500",
                      "--framer-letter-spacing": "-0.07em",
                      "--framer-line-height": "110%",
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                    },
                    children: "Title",
                  }),
                }),
                className: "framer-t8hhz4",
                "data-framer-name": "Websites",
                fonts: ["Inter-Medium"],
                layoutDependency: layoutDependency,
                layoutId: "ElqYy4OYu",
                style: {
                  "--extracted-r6o4lv": "rgb(255, 255, 255)",
                  "--framer-paragraph-spacing": "0px",
                  opacity: 1,
                },
                text: fErYKCICq,
                variants: {
                  OM0T28LIR: { opacity: 0.2 },
                  sU_9MvVyf: { opacity: 0.15 },
                  wNupTgeBX: { opacity: 0.15 },
                },
                verticalAlignment: "top",
                withExternalLayout: true,
                ...addPropertyOverrides(
                  {
                    D_0PvXkKg: {
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector": "SW50ZXItTWVkaXVt",
                            "--framer-font-family":
                              '"Inter", "Inter Placeholder", sans-serif',
                            "--framer-font-size": "72px",
                            "--framer-font-weight": "500",
                            "--framer-letter-spacing": "-0.07em",
                            "--framer-line-height": "110%",
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                          },
                          children: "Title",
                        }),
                      }),
                    },
                    DY4InP0NL: {
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector": "SW50ZXItTWVkaXVt",
                            "--framer-font-family":
                              '"Inter", "Inter Placeholder", sans-serif',
                            "--framer-font-size": "35px",
                            "--framer-font-weight": "500",
                            "--framer-letter-spacing": "-0.07em",
                            "--framer-line-height": "110%",
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                          },
                          children: "Title",
                        }),
                      }),
                    },
                    OM0T28LIR: {
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector": "SW50ZXItTWVkaXVt",
                            "--framer-font-family":
                              '"Inter", "Inter Placeholder", sans-serif',
                            "--framer-font-size": "35px",
                            "--framer-font-weight": "500",
                            "--framer-letter-spacing": "-0.07em",
                            "--framer-line-height": "110%",
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                          },
                          children: "Title",
                        }),
                      }),
                    },
                    sU_9MvVyf: {
                      children: /*#__PURE__*/ _jsx(React.Fragment, {
                        children: /*#__PURE__*/ _jsx(motion.p, {
                          style: {
                            "--font-selector": "SW50ZXItTWVkaXVt",
                            "--framer-font-family":
                              '"Inter", "Inter Placeholder", sans-serif',
                            "--framer-font-size": "72px",
                            "--framer-font-weight": "500",
                            "--framer-letter-spacing": "-0.07em",
                            "--framer-line-height": "110%",
                            "--framer-text-color":
                              "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                          },
                          children: "Title",
                        }),
                      }),
                    },
                  },
                  baseVariant,
                  gestureVariant
                ),
              }),
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-1ttgg32",
                "data-framer-name": "5",
                layoutDependency: layoutDependency,
                layoutId: "IAPdu_olr",
                children: [
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "SW50ZXItQm9sZA==",
                          "--framer-font-family":
                            '"Inter", "Inter Placeholder", sans-serif',
                          "--framer-font-size": "20px",
                          "--framer-font-weight": "700",
                          "--framer-letter-spacing": "-0.05em",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-1662617d-fd18-4319-b3da-aa36e5415705, rgb(249, 69, 45)))",
                          "--framer-text-transform": "uppercase",
                        },
                        children: "{",
                      }),
                    }),
                    className: "framer-nibo9d",
                    "data-framer-name": "{",
                    fonts: ["Inter-Bold"],
                    layoutDependency: layoutDependency,
                    layoutId: "bcvYWJGOA",
                    style: {
                      "--extracted-r6o4lv":
                        "var(--token-1662617d-fd18-4319-b3da-aa36e5415705, rgb(249, 69, 45))",
                      "--framer-paragraph-spacing": "0px",
                    },
                    variants: {
                      OM0T28LIR: {
                        "--extracted-r6o4lv": "rgba(255, 255, 255, 0.2)",
                      },
                      sU_9MvVyf: {
                        "--extracted-r6o4lv": "rgba(255, 255, 255, 0.2)",
                      },
                      wNupTgeBX: {
                        "--extracted-r6o4lv": "rgba(255, 255, 255, 0.2)",
                      },
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        D_0PvXkKg: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector": "SW50ZXItQm9sZA==",
                                "--framer-font-family":
                                  '"Inter", "Inter Placeholder", sans-serif',
                                "--framer-font-size": "14px",
                                "--framer-font-weight": "700",
                                "--framer-letter-spacing": "-0.05em",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-1662617d-fd18-4319-b3da-aa36e5415705, rgb(249, 69, 45)))",
                                "--framer-text-transform": "uppercase",
                              },
                              children: "{",
                            }),
                          }),
                        },
                        DY4InP0NL: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector": "SW50ZXItQm9sZA==",
                                "--framer-font-family":
                                  '"Inter", "Inter Placeholder", sans-serif',
                                "--framer-font-size": "14px",
                                "--framer-font-weight": "700",
                                "--framer-letter-spacing": "-0.05em",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-1662617d-fd18-4319-b3da-aa36e5415705, rgb(249, 69, 45)))",
                                "--framer-text-transform": "uppercase",
                              },
                              children: "{",
                            }),
                          }),
                        },
                        OM0T28LIR: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector": "SW50ZXItQm9sZA==",
                                "--framer-font-family":
                                  '"Inter", "Inter Placeholder", sans-serif',
                                "--framer-font-size": "14px",
                                "--framer-font-weight": "700",
                                "--framer-letter-spacing": "-0.05em",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, rgba(255, 255, 255, 0.2))",
                                "--framer-text-transform": "uppercase",
                              },
                              children: "{",
                            }),
                          }),
                        },
                        sU_9MvVyf: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector": "SW50ZXItQm9sZA==",
                                "--framer-font-family":
                                  '"Inter", "Inter Placeholder", sans-serif',
                                "--framer-font-size": "14px",
                                "--framer-font-weight": "700",
                                "--framer-letter-spacing": "-0.05em",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, rgba(255, 255, 255, 0.2))",
                                "--framer-text-transform": "uppercase",
                              },
                              children: "{",
                            }),
                          }),
                        },
                        wNupTgeBX: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector": "SW50ZXItQm9sZA==",
                                "--framer-font-family":
                                  '"Inter", "Inter Placeholder", sans-serif',
                                "--framer-font-weight": "700",
                                "--framer-letter-spacing": "-0.05em",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, rgba(255, 255, 255, 0.2))",
                                "--framer-text-transform": "uppercase",
                              },
                              children: "{",
                            }),
                          }),
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "SW50ZXItQm9sZA==",
                          "--framer-font-family":
                            '"Inter", "Inter Placeholder", sans-serif',
                          "--framer-font-size": "20px",
                          "--framer-font-weight": "700",
                          "--framer-letter-spacing": "-0.05em",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                          "--framer-text-transform": "uppercase",
                        },
                        children: "00",
                      }),
                    }),
                    className: "framer-z1qhe3",
                    "data-framer-name": "01",
                    fonts: ["Inter-Bold"],
                    layoutDependency: layoutDependency,
                    layoutId: "wjwcJ_06U",
                    style: {
                      "--extracted-r6o4lv": "rgb(255, 255, 255)",
                      "--framer-paragraph-spacing": "0px",
                    },
                    text: yB44CUche,
                    variants: {
                      OM0T28LIR: {
                        "--extracted-r6o4lv": "rgba(255, 255, 255, 0.4)",
                      },
                      sU_9MvVyf: {
                        "--extracted-r6o4lv": "rgba(255, 255, 255, 0.4)",
                      },
                      wNupTgeBX: {
                        "--extracted-r6o4lv": "rgba(255, 255, 255, 0.4)",
                      },
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        D_0PvXkKg: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector": "SW50ZXItQm9sZA==",
                                "--framer-font-family":
                                  '"Inter", "Inter Placeholder", sans-serif',
                                "--framer-font-size": "14px",
                                "--framer-font-weight": "700",
                                "--framer-letter-spacing": "-0.05em",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                                "--framer-text-transform": "uppercase",
                              },
                              children: "00",
                            }),
                          }),
                        },
                        DY4InP0NL: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector": "SW50ZXItQm9sZA==",
                                "--framer-font-family":
                                  '"Inter", "Inter Placeholder", sans-serif',
                                "--framer-font-size": "14px",
                                "--framer-font-weight": "700",
                                "--framer-letter-spacing": "-0.05em",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, rgb(255, 255, 255))",
                                "--framer-text-transform": "uppercase",
                              },
                              children: "00",
                            }),
                          }),
                        },
                        OM0T28LIR: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector": "SW50ZXItQm9sZA==",
                                "--framer-font-family":
                                  '"Inter", "Inter Placeholder", sans-serif',
                                "--framer-font-size": "14px",
                                "--framer-font-weight": "700",
                                "--framer-letter-spacing": "-0.05em",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, rgba(255, 255, 255, 0.4))",
                                "--framer-text-transform": "uppercase",
                              },
                              children: "00",
                            }),
                          }),
                        },
                        sU_9MvVyf: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector": "SW50ZXItQm9sZA==",
                                "--framer-font-family":
                                  '"Inter", "Inter Placeholder", sans-serif',
                                "--framer-font-size": "14px",
                                "--framer-font-weight": "700",
                                "--framer-letter-spacing": "-0.05em",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, rgba(255, 255, 255, 0.4))",
                                "--framer-text-transform": "uppercase",
                              },
                              children: "00",
                            }),
                          }),
                        },
                        wNupTgeBX: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector": "SW50ZXItQm9sZA==",
                                "--framer-font-family":
                                  '"Inter", "Inter Placeholder", sans-serif',
                                "--framer-font-weight": "700",
                                "--framer-letter-spacing": "-0.05em",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, rgba(255, 255, 255, 0.4))",
                                "--framer-text-transform": "uppercase",
                              },
                              children: "00",
                            }),
                          }),
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                  /*#__PURE__*/ _jsx(RichText, {
                    __fromCanvasComponent: true,
                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                      children: /*#__PURE__*/ _jsx(motion.p, {
                        style: {
                          "--font-selector": "SW50ZXItQm9sZA==",
                          "--framer-font-family":
                            '"Inter", "Inter Placeholder", sans-serif',
                          "--framer-font-size": "20px",
                          "--framer-font-weight": "700",
                          "--framer-letter-spacing": "-0.05em",
                          "--framer-text-color":
                            "var(--extracted-r6o4lv, var(--token-1662617d-fd18-4319-b3da-aa36e5415705, rgb(249, 69, 45)))",
                          "--framer-text-transform": "uppercase",
                        },
                        children: "}",
                      }),
                    }),
                    className: "framer-9reabl",
                    "data-framer-name": "}",
                    fonts: ["Inter-Bold"],
                    layoutDependency: layoutDependency,
                    layoutId: "hDBKsFpVP",
                    style: {
                      "--extracted-r6o4lv":
                        "var(--token-1662617d-fd18-4319-b3da-aa36e5415705, rgb(249, 69, 45))",
                      "--framer-paragraph-spacing": "0px",
                    },
                    variants: {
                      OM0T28LIR: {
                        "--extracted-r6o4lv": "rgba(255, 255, 255, 0.2)",
                      },
                      sU_9MvVyf: {
                        "--extracted-r6o4lv": "rgba(255, 255, 255, 0.2)",
                      },
                      wNupTgeBX: {
                        "--extracted-r6o4lv": "rgba(255, 255, 255, 0.2)",
                      },
                    },
                    verticalAlignment: "top",
                    withExternalLayout: true,
                    ...addPropertyOverrides(
                      {
                        D_0PvXkKg: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector": "SW50ZXItQm9sZA==",
                                "--framer-font-family":
                                  '"Inter", "Inter Placeholder", sans-serif',
                                "--framer-font-size": "14px",
                                "--framer-font-weight": "700",
                                "--framer-letter-spacing": "-0.05em",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-1662617d-fd18-4319-b3da-aa36e5415705, rgb(249, 69, 45)))",
                                "--framer-text-transform": "uppercase",
                              },
                              children: "}",
                            }),
                          }),
                        },
                        DY4InP0NL: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector": "SW50ZXItQm9sZA==",
                                "--framer-font-family":
                                  '"Inter", "Inter Placeholder", sans-serif',
                                "--framer-font-size": "14px",
                                "--framer-font-weight": "700",
                                "--framer-letter-spacing": "-0.05em",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, var(--token-1662617d-fd18-4319-b3da-aa36e5415705, rgb(249, 69, 45)))",
                                "--framer-text-transform": "uppercase",
                              },
                              children: "}",
                            }),
                          }),
                        },
                        OM0T28LIR: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector": "SW50ZXItQm9sZA==",
                                "--framer-font-family":
                                  '"Inter", "Inter Placeholder", sans-serif',
                                "--framer-font-size": "14px",
                                "--framer-font-weight": "700",
                                "--framer-letter-spacing": "-0.05em",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, rgba(255, 255, 255, 0.2))",
                                "--framer-text-transform": "uppercase",
                              },
                              children: "}",
                            }),
                          }),
                        },
                        sU_9MvVyf: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector": "SW50ZXItQm9sZA==",
                                "--framer-font-family":
                                  '"Inter", "Inter Placeholder", sans-serif',
                                "--framer-font-size": "14px",
                                "--framer-font-weight": "700",
                                "--framer-letter-spacing": "-0.05em",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, rgba(255, 255, 255, 0.2))",
                                "--framer-text-transform": "uppercase",
                              },
                              children: "}",
                            }),
                          }),
                        },
                        wNupTgeBX: {
                          children: /*#__PURE__*/ _jsx(React.Fragment, {
                            children: /*#__PURE__*/ _jsx(motion.p, {
                              style: {
                                "--font-selector": "SW50ZXItQm9sZA==",
                                "--framer-font-family":
                                  '"Inter", "Inter Placeholder", sans-serif',
                                "--framer-font-weight": "700",
                                "--framer-letter-spacing": "-0.05em",
                                "--framer-text-color":
                                  "var(--extracted-r6o4lv, rgba(255, 255, 255, 0.2))",
                                "--framer-text-transform": "uppercase",
                              },
                              children: "}",
                            }),
                          }),
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                ],
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-80AfW.framer-1g1xgga, .framer-80AfW .framer-1g1xgga { display: block; }",
  ".framer-80AfW.framer-1vftdq5 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 26px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 10px 0px 20px 16px; position: relative; width: 725px; }",
  ".framer-80AfW .framer-1i8uvxx { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
  ".framer-80AfW .framer-t8hhz4, .framer-80AfW .framer-nibo9d, .framer-80AfW .framer-z1qhe3, .framer-80AfW .framer-9reabl { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
  ".framer-80AfW .framer-1ttgg32 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-80AfW.framer-1vftdq5, .framer-80AfW .framer-1i8uvxx, .framer-80AfW .framer-1ttgg32 { gap: 0px; } .framer-80AfW.framer-1vftdq5 > * { margin: 0px; margin-bottom: calc(26px / 2); margin-top: calc(26px / 2); } .framer-80AfW.framer-1vftdq5 > :first-child { margin-top: 0px; } .framer-80AfW.framer-1vftdq5 > :last-child { margin-bottom: 0px; } .framer-80AfW .framer-1i8uvxx > * { margin: 0px; margin-left: calc(24px / 2); margin-right: calc(24px / 2); } .framer-80AfW .framer-1i8uvxx > :first-child, .framer-80AfW .framer-1ttgg32 > :first-child { margin-left: 0px; } .framer-80AfW .framer-1i8uvxx > :last-child, .framer-80AfW .framer-1ttgg32 > :last-child { margin-right: 0px; } .framer-80AfW .framer-1ttgg32 > * { margin: 0px; margin-left: calc(4px / 2); margin-right: calc(4px / 2); } }",
  ".framer-80AfW.framer-v-10t5t6l.framer-1vftdq5 { padding: 10px 0px 20px 0px; }",
  ".framer-80AfW.framer-v-10t5t6l .framer-1i8uvxx, .framer-80AfW.framer-v-pz4gxq .framer-1i8uvxx { gap: 20px; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-80AfW.framer-v-10t5t6l .framer-1i8uvxx { gap: 0px; } .framer-80AfW.framer-v-10t5t6l .framer-1i8uvxx > * { margin: 0px; margin-left: calc(20px / 2); margin-right: calc(20px / 2); } .framer-80AfW.framer-v-10t5t6l .framer-1i8uvxx > :first-child { margin-left: 0px; } .framer-80AfW.framer-v-10t5t6l .framer-1i8uvxx > :last-child { margin-right: 0px; } }",
  ".framer-80AfW.framer-v-pz4gxq.framer-1vftdq5, .framer-80AfW.framer-v-1hgpdev.framer-1vftdq5 { gap: 14px; padding: 12px 0px 26px 0px; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-80AfW.framer-v-pz4gxq.framer-1vftdq5, .framer-80AfW.framer-v-pz4gxq .framer-1i8uvxx { gap: 0px; } .framer-80AfW.framer-v-pz4gxq.framer-1vftdq5 > * { margin: 0px; margin-bottom: calc(14px / 2); margin-top: calc(14px / 2); } .framer-80AfW.framer-v-pz4gxq.framer-1vftdq5 > :first-child { margin-top: 0px; } .framer-80AfW.framer-v-pz4gxq.framer-1vftdq5 > :last-child { margin-bottom: 0px; } .framer-80AfW.framer-v-pz4gxq .framer-1i8uvxx > * { margin: 0px; margin-left: calc(20px / 2); margin-right: calc(20px / 2); } .framer-80AfW.framer-v-pz4gxq .framer-1i8uvxx > :first-child { margin-left: 0px; } .framer-80AfW.framer-v-pz4gxq .framer-1i8uvxx > :last-child { margin-right: 0px; } }",
  ".framer-80AfW.framer-v-1hgpdev .framer-1i8uvxx { gap: 16px; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-80AfW.framer-v-1hgpdev.framer-1vftdq5, .framer-80AfW.framer-v-1hgpdev .framer-1i8uvxx { gap: 0px; } .framer-80AfW.framer-v-1hgpdev.framer-1vftdq5 > * { margin: 0px; margin-bottom: calc(14px / 2); margin-top: calc(14px / 2); } .framer-80AfW.framer-v-1hgpdev.framer-1vftdq5 > :first-child { margin-top: 0px; } .framer-80AfW.framer-v-1hgpdev.framer-1vftdq5 > :last-child { margin-bottom: 0px; } .framer-80AfW.framer-v-1hgpdev .framer-1i8uvxx > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } .framer-80AfW.framer-v-1hgpdev .framer-1i8uvxx > :first-child { margin-left: 0px; } .framer-80AfW.framer-v-1hgpdev .framer-1i8uvxx > :last-child { margin-right: 0px; } }",
  ".framer-80AfW.framer-v-1wdw0ve.framer-1vftdq5 { gap: 14px; padding: 0px 0px 16px 0px; width: 320px; }",
  ".framer-80AfW.framer-v-1wdw0ve .framer-1i8uvxx, .framer-80AfW.framer-v-16tri3p .framer-1i8uvxx { gap: 12px; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-80AfW.framer-v-1wdw0ve.framer-1vftdq5, .framer-80AfW.framer-v-1wdw0ve .framer-1i8uvxx { gap: 0px; } .framer-80AfW.framer-v-1wdw0ve.framer-1vftdq5 > * { margin: 0px; margin-bottom: calc(14px / 2); margin-top: calc(14px / 2); } .framer-80AfW.framer-v-1wdw0ve.framer-1vftdq5 > :first-child { margin-top: 0px; } .framer-80AfW.framer-v-1wdw0ve.framer-1vftdq5 > :last-child { margin-bottom: 0px; } .framer-80AfW.framer-v-1wdw0ve .framer-1i8uvxx > * { margin: 0px; margin-left: calc(12px / 2); margin-right: calc(12px / 2); } .framer-80AfW.framer-v-1wdw0ve .framer-1i8uvxx > :first-child { margin-left: 0px; } .framer-80AfW.framer-v-1wdw0ve .framer-1i8uvxx > :last-child { margin-right: 0px; } }",
  ".framer-80AfW.framer-v-16tri3p.framer-1vftdq5 { gap: 10px; padding: 0px 0px 16px 0px; width: 320px; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-80AfW.framer-v-16tri3p.framer-1vftdq5, .framer-80AfW.framer-v-16tri3p .framer-1i8uvxx { gap: 0px; } .framer-80AfW.framer-v-16tri3p.framer-1vftdq5 > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-80AfW.framer-v-16tri3p.framer-1vftdq5 > :first-child { margin-top: 0px; } .framer-80AfW.framer-v-16tri3p.framer-1vftdq5 > :last-child { margin-bottom: 0px; } .framer-80AfW.framer-v-16tri3p .framer-1i8uvxx > * { margin: 0px; margin-left: calc(12px / 2); margin-right: calc(12px / 2); } .framer-80AfW.framer-v-16tri3p .framer-1i8uvxx > :first-child { margin-left: 0px; } .framer-80AfW.framer-v-16tri3p .framer-1i8uvxx > :last-child { margin-right: 0px; } }",
  '.framer-80AfW[data-border="true"]::after, .framer-80AfW [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 142
 * @framerIntrinsicWidth 725
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"wNupTgeBX":{"layout":["fixed","auto"]},"D_0PvXkKg":{"layout":["fixed","auto"]},"sU_9MvVyf":{"layout":["fixed","auto"]},"DY4InP0NL":{"layout":["fixed","auto"]},"OM0T28LIR":{"layout":["fixed","auto"]}}}
 * @framerVariables {"fErYKCICq":"title","yB44CUche":"number","KrXbsPILD":"mouseEnter"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerZkokeclFd = withCSS(Component, css, "framer-80AfW");
export default FramerZkokeclFd;
FramerZkokeclFd.displayName = "Services / Items / Item";
FramerZkokeclFd.defaultProps = { height: 142, width: 725 };
addPropertyControls(FramerZkokeclFd, {
  variant: {
    options: [
      "I5anvyWOt",
      "wNupTgeBX",
      "D_0PvXkKg",
      "sU_9MvVyf",
      "DY4InP0NL",
      "OM0T28LIR",
    ],
    optionTitles: [
      "Desktop active",
      "Desktop inactive",
      "Tablet active",
      "Tablet inative",
      "Phone active",
      "Phone inactive",
    ],
    title: "Variant",
    type: ControlType.Enum,
  },
  fErYKCICq: {
    defaultValue: "Title",
    displayTextArea: false,
    title: "Title",
    type: ControlType.String,
  },
  yB44CUche: {
    defaultValue: "00",
    displayTextArea: false,
    title: "Number",
    type: ControlType.String,
  },
  KrXbsPILD: { title: "Mouse Enter", type: ControlType.EventHandler },
});
addFonts(
  FramerZkokeclFd,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/d3tHnaQIAeqiE5hGcRw4mmgWYU.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
          weight: "500",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
          weight: "700",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
          weight: "700",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
          weight: "700",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
          weight: "700",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
          weight: "700",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
          weight: "700",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
          weight: "700",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerZkokeclFd",
      slots: [],
      annotations: {
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"wNupTgeBX":{"layout":["fixed","auto"]},"D_0PvXkKg":{"layout":["fixed","auto"]},"sU_9MvVyf":{"layout":["fixed","auto"]},"DY4InP0NL":{"layout":["fixed","auto"]},"OM0T28LIR":{"layout":["fixed","auto"]}}}',
        framerDisplayContentsDiv: "false",
        framerVariables:
          '{"fErYKCICq":"title","yB44CUche":"number","KrXbsPILD":"mouseEnter"}',
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "725",
        framerComponentViewportWidth: "true",
        framerIntrinsicHeight: "142",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./ZkokeclFd.map
