// Generated by Framer (a72a541)
export default function metadata(params, activeLocale) {
  return {
    description:
      "Transform your brand with Thebrandle's expert digital design, UX/UI, and development services. We create stunning websites that drive results with 24/7 priority support.",
    favicon:
      "https://framerusercontent.com/assets/0qZrfBuw0vpXfqa4iQEyDlGqjU.png",
    robots: "max-image-preview:large",
    socialImage:
      "https://framerusercontent.com/assets/YNmypiM868x4WUMKO25HF3tDPN4.jpg",
    title: "Thebrandle Studio | Digital Design & Brand Development Agency",
  };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
  exports: {
    metadataVersion: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    default: { type: "function", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
