// Generated by Framer (aabb2d2)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getLoadingLazyAtYPosition,
  Image,
  Link,
  RichText,
  SVG,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
const enabledGestures = { i6E_yBPqF: { hover: true } };
const cycleOrder = ["i6E_yBPqF", "YI21lfe1A"];
const serializationHash = "framer-jmWos";
const variantClassNames = {
  i6E_yBPqF: "framer-v-y71qlm",
  YI21lfe1A: "framer-v-1qzfmag",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const KPKntq0BL = undefined;
const qEnLTWHb7 = undefined;
const HXK9GfHoc = undefined;
const d7bblw14I = undefined;
const transition1 = {
  delay: 0,
  duration: 0.25,
  ease: [0.96, -0.02, 0.38, 1.01],
  type: "tween",
};
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Desktop: "i6E_yBPqF", Phone: "YI21lfe1A" };
const getProps = ({
  height,
  id,
  image,
  link,
  text1,
  text2,
  width,
  ...props
}) => {
  return {
    ...props,
    d7bblw14I: text2 ?? props.d7bblw14I ?? "Anatolii Dmitrienko",
    HXK9GfHoc: image ??
      props.HXK9GfHoc ?? {
        alt: "Profile portrait of a man in a grey shirt",
        pixelHeight: 73,
        pixelWidth: 73,
        src: "https://framerusercontent.com/images/nr593SABZlC19HZOrgnV0sWc8A.jpg?width=73&height=73",
      },
    KPKntq0BL: link ?? props.KPKntq0BL,
    qEnLTWHb7: text1 ?? props.qEnLTWHb7 ?? "Created by",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "i6E_yBPqF",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const {
    style,
    className,
    layoutId,
    variant,
    qEnLTWHb7,
    HXK9GfHoc,
    d7bblw14I,
    KPKntq0BL,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "i6E_yBPqF",
    enabledGestures,
    ref: refBinding,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: KPKntq0BL,
          motionChild: true,
          nodeId: "i6E_yBPqF",
          openInNewTab: true,
          scopeId: "l7eS7aCY2",
          children: /*#__PURE__*/ _jsxs(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(
              scopingClassNames,
              "framer-y71qlm",
              className,
              classNames
            )} framer-zlu9l5`,
            "data-framer-name": "Desktop",
            layoutDependency: layoutDependency,
            layoutId: "i6E_yBPqF",
            ref: refBinding,
            style: { ...style },
            ...addPropertyOverrides(
              {
                "i6E_yBPqF-hover": { "data-framer-name": undefined },
                YI21lfe1A: { "data-framer-name": "Phone" },
              },
              baseVariant,
              gestureVariant
            ),
            children: [
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    style: {
                      "--font-selector": "SW50ZXItTWVkaXVt",
                      "--framer-font-size": "13px",
                      "--framer-font-weight": "500",
                      "--framer-letter-spacing": "-0.04em",
                      "--framer-line-height": "1.4em",
                      "--framer-text-alignment": "center",
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12)))",
                    },
                    children: "Created by",
                  }),
                }),
                className: "framer-1cv3ncn",
                "data-framer-name": "Created by",
                fonts: ["Inter-Medium"],
                layoutDependency: layoutDependency,
                layoutId: "FscR0gOQD",
                style: {
                  "--extracted-r6o4lv":
                    "var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12))",
                  "--framer-paragraph-spacing": "0px",
                  opacity: 0.6,
                },
                text: qEnLTWHb7,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-5st1fw",
                "data-framer-name": "Image",
                layoutDependency: layoutDependency,
                layoutId: "VcEuIwCjo",
                children: [
                  /*#__PURE__*/ _jsx(Image, {
                    background: {
                      alt: "Profile portrait of a man in a grey shirt",
                      fit: "fill",
                      loading: getLoadingLazyAtYPosition(
                        (componentViewport?.y || 0) +
                          (0 +
                            ((componentViewport?.height || 28) - 0 - 28) / 2) +
                          0
                      ),
                      pixelHeight: 73,
                      pixelWidth: 73,
                      sizes: "28px",
                      ...toResponsiveImage(HXK9GfHoc),
                    },
                    className: "framer-1jk6h7y",
                    "data-framer-name": "Avatar",
                    layoutDependency: layoutDependency,
                    layoutId: "vTlLXTRlP",
                    style: {
                      borderBottomLeftRadius: "100%",
                      borderBottomRightRadius: "100%",
                      borderTopLeftRadius: "100%",
                      borderTopRightRadius: "100%",
                      scale: 1,
                    },
                    variants: { "i6E_yBPqF-hover": { scale: 0.4 } },
                    ...addPropertyOverrides(
                      {
                        "i6E_yBPqF-hover": {
                          background: {
                            alt: "Profile portrait of a man in a grey shirt",
                            fit: "fill",
                            loading: getLoadingLazyAtYPosition(
                              (componentViewport?.y || 0) +
                                (0 +
                                  ((componentViewport?.height || 28) - 0 - 28) /
                                    2) +
                                -28
                            ),
                            pixelHeight: 73,
                            pixelWidth: 73,
                            sizes: "28px",
                            ...toResponsiveImage(HXK9GfHoc),
                          },
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }),
                  /*#__PURE__*/ _jsx(motion.div, {
                    className: "framer-te1ie4",
                    "data-framer-name": "Logo",
                    layoutDependency: layoutDependency,
                    layoutId: "sqC5IXFa6",
                    style: {
                      backgroundColor: "rgb(210, 255, 55)",
                      borderBottomLeftRadius: "100%",
                      borderBottomRightRadius: "100%",
                      borderTopLeftRadius: "100%",
                      borderTopRightRadius: "100%",
                      scale: 0.5,
                    },
                    variants: { "i6E_yBPqF-hover": { scale: 1 } },
                    children: /*#__PURE__*/ _jsx(SVG, {
                      className: "framer-mqj7pr",
                      "data-framer-name": "logo",
                      fill: "black",
                      intrinsicHeight: 47,
                      intrinsicWidth: 33,
                      layoutDependency: layoutDependency,
                      layoutId: "JJrO74VVF",
                      svg: '<svg width="33" height="47" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M16.244 47a1.828 1.828 0 0 1-1.27-.515 1.73 1.73 0 0 1-.526-1.244V30.348l-12.653-.005c-.311 0-.617-.08-.888-.23a1.779 1.779 0 0 1-.655-.63 1.733 1.733 0 0 1-.034-1.74L15.101.92c.19-.344.492-.615.858-.772A1.83 1.83 0 0 1 17.12.054c.387.097.73.317.975.625.245.31.378.689.378 1.08v14.92h12.732c.311 0 .618.08.888.231.271.151.497.369.656.632a1.733 1.733 0 0 1 .03 1.741L17.82 46.085a1.776 1.776 0 0 1-.66.669 1.824 1.824 0 0 1-.915.246Z" fill="#222"/></svg>',
                      withExternalLayout: true,
                    }),
                  }),
                ],
              }),
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    style: {
                      "--font-selector": "SW50ZXItTWVkaXVt",
                      "--framer-font-size": "13px",
                      "--framer-font-weight": "500",
                      "--framer-letter-spacing": "-0.04em",
                      "--framer-line-height": "1.4em",
                      "--framer-text-alignment": "center",
                      "--framer-text-color":
                        "var(--extracted-r6o4lv, var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12)))",
                    },
                    children: "Anatolii Dmitrienko",
                  }),
                }),
                className: "framer-mhpk80",
                "data-framer-name": "Anatolii Dmitrienko",
                fonts: ["Inter-Medium"],
                layoutDependency: layoutDependency,
                layoutId: "GD1PW2_l1",
                style: {
                  "--extracted-r6o4lv":
                    "var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12))",
                  "--framer-paragraph-spacing": "0px",
                  opacity: 0.6,
                },
                text: d7bblw14I,
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-jmWos.framer-zlu9l5, .framer-jmWos .framer-zlu9l5 { display: block; }",
  ".framer-jmWos.framer-y71qlm { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
  ".framer-jmWos .framer-1cv3ncn, .framer-jmWos .framer-mhpk80 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-jmWos .framer-5st1fw { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
  ".framer-jmWos .framer-1jk6h7y { aspect-ratio: 1 / 1; flex: none; gap: 4px; height: var(--framer-aspect-ratio-supported, 28px); position: relative; width: 28px; }",
  ".framer-jmWos .framer-te1ie4 { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: var(--framer-aspect-ratio-supported, 28px); justify-content: center; left: 0px; padding: 0px; position: absolute; top: 28px; width: 28px; z-index: 1; }",
  ".framer-jmWos .framer-mqj7pr { aspect-ratio: 0.7021276595744681 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 14px); position: relative; width: 10px; }",
  ".framer-jmWos.framer-v-1qzfmag.framer-y71qlm { cursor: unset; }",
  ".framer-jmWos.framer-v-y71qlm.hover .framer-1jk6h7y { left: 0px; position: absolute; top: -28px; z-index: 1; }",
  ".framer-jmWos.framer-v-y71qlm.hover .framer-te1ie4 { left: unset; position: relative; top: unset; }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 28
 * @framerIntrinsicWidth 210.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"YI21lfe1A":{"layout":["auto","auto"]},"KVEZZ2k2k":{"layout":["auto","auto"]}}}
 * @framerVariables {"qEnLTWHb7":"text1","HXK9GfHoc":"image","d7bblw14I":"text2","KPKntq0BL":"link"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */ const Framerl7eS7aCY2 = withCSS(Component, css, "framer-jmWos");
export default Framerl7eS7aCY2;
Framerl7eS7aCY2.displayName = "Created by 2";
Framerl7eS7aCY2.defaultProps = { height: 28, width: 210.5 };
addPropertyControls(Framerl7eS7aCY2, {
  variant: {
    options: ["i6E_yBPqF", "YI21lfe1A"],
    optionTitles: ["Desktop", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  qEnLTWHb7: {
    defaultValue: "Created by",
    displayTextArea: false,
    title: "Text 1",
    type: ControlType.String,
  },
  HXK9GfHoc: {
    __defaultAssetReference:
      "data:framer/asset-reference,nr593SABZlC19HZOrgnV0sWc8A.jpg?originalFilename=image+61.jpg&preferredSize=auto",
    __vekterDefault: {
      alt: "Profile portrait of a man in a grey shirt",
      assetReference:
        "data:framer/asset-reference,nr593SABZlC19HZOrgnV0sWc8A.jpg?originalFilename=image+61.jpg&preferredSize=auto",
    },
    title: "Image",
    type: ControlType.ResponsiveImage,
  },
  d7bblw14I: {
    defaultValue: "Anatolii Dmitrienko",
    displayTextArea: false,
    title: "Text 2",
    type: ControlType.String,
  },
  KPKntq0BL: { title: "Link", type: ControlType.Link },
});
addFonts(
  Framerl7eS7aCY2,
  [
    {
      explicitInter: true,
      fonts: [
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
          weight: "500",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
          weight: "500",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
          weight: "500",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
          weight: "500",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
          weight: "500",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/UjlFhCnUjxhNfep4oYBPqnEssyo.woff2",
          weight: "500",
        },
        {
          cssFamilyName: "Inter",
          source: "framer",
          style: "normal",
          uiFamilyName: "Inter",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
          weight: "500",
        },
      ],
    },
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "Framerl7eS7aCY2",
      slots: [],
      annotations: {
        framerImmutableVariables: "true",
        framerVariables:
          '{"qEnLTWHb7":"text1","HXK9GfHoc":"image","d7bblw14I":"text2","KPKntq0BL":"link"}',
        framerAutoSizeImages: "true",
        framerComponentViewportWidth: "true",
        framerIntrinsicHeight: "28",
        framerIntrinsicWidth: "210.5",
        framerContractVersion: "1",
        framerColorSyntax: "true",
        framerDisplayContentsDiv: "false",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"YI21lfe1A":{"layout":["auto","auto"]},"KVEZZ2k2k":{"layout":["auto","auto"]}}}',
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./l7eS7aCY2.map
