// Generated by Framer (915daba)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/oMgXPBeR6YdHTzKPyOpl/EoE1kmmGpZHB3Wts7nST/xNIXLfFSf.js";
const serializationHash = "framer-tGV17";
const variantClassNames = { YKTaoeiNj: "framer-v-10csmg6" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const getProps = ({ height, id, text, width, ...props }) => {
  return { ...props, TVsgllYiM: text ?? props.TVsgllYiM ?? "Text" };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, TVsgllYiM, ...restProps } =
    getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    defaultVariant: "YKTaoeiNj",
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            scopingClassNames,
            "framer-10csmg6",
            className,
            classNames
          ),
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "YKTaoeiNj",
          ref: ref ?? ref1,
          style: { ...style },
          children: [
            /*#__PURE__*/ _jsx(motion.div, {
              className: "framer-87eyzz",
              "data-framer-name": "Container",
              layoutDependency: layoutDependency,
              layoutId: "CHeTmIHeK",
              children: /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-1cq5117",
                "data-border": true,
                "data-framer-name": "Rectangle",
                layoutDependency: layoutDependency,
                layoutId: "mxaepEFAQ",
                style: {
                  "--border-bottom-width": "2px",
                  "--border-color":
                    "var(--token-1662617d-fd18-4319-b3da-aa36e5415705, rgb(249, 69, 45))",
                  "--border-left-width": "0px",
                  "--border-right-width": "2px",
                  "--border-style": "solid",
                  "--border-top-width": "0px",
                  rotate: -90,
                },
              }),
            }),
            /*#__PURE__*/ _jsx(RichText, {
              __fromCanvasComponent: true,
              children: /*#__PURE__*/ _jsx(React.Fragment, {
                children: /*#__PURE__*/ _jsx(motion.p, {
                  className: "framer-styles-preset-jnye1g",
                  "data-styles-preset": "xNIXLfFSf",
                  style: {
                    "--framer-text-color":
                      "var(--extracted-r6o4lv, var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12)))",
                  },
                  children: "Everything in the Basic Plan",
                }),
              }),
              className: "framer-8wk301",
              "data-framer-name": "Everything in the Basic Plan",
              fonts: ["Inter"],
              layoutDependency: layoutDependency,
              layoutId: "oHGJn7z0l",
              style: {
                "--extracted-r6o4lv":
                  "var(--token-09fd1980-8076-4f0b-8bb4-7ba5919ad6b8, rgb(12, 12, 12))",
                "--framer-paragraph-spacing": "0px",
                opacity: 0.6,
              },
              text: TVsgllYiM,
              verticalAlignment: "top",
              withExternalLayout: true,
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-tGV17.framer-potnvo, .framer-tGV17 .framer-potnvo { display: block; }",
  ".framer-tGV17.framer-10csmg6 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 230px; }",
  ".framer-tGV17 .framer-87eyzz { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 5px 0px 0px 0px; position: relative; width: min-content; }",
  ".framer-tGV17 .framer-1cq5117 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 9px); position: relative; width: 9px; }",
  ".framer-tGV17 .framer-8wk301 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-tGV17.framer-10csmg6, .framer-tGV17 .framer-87eyzz { gap: 0px; } .framer-tGV17.framer-10csmg6 > * { margin: 0px; margin-left: calc(12px / 2); margin-right: calc(12px / 2); } .framer-tGV17.framer-10csmg6 > :first-child, .framer-tGV17 .framer-87eyzz > :first-child { margin-left: 0px; } .framer-tGV17.framer-10csmg6 > :last-child, .framer-tGV17 .framer-87eyzz > :last-child { margin-right: 0px; } .framer-tGV17 .framer-87eyzz > * { margin: 0px; margin-left: calc(20px / 2); margin-right: calc(20px / 2); } }",
  ...sharedStyle.css,
  '.framer-tGV17[data-border="true"]::after, .framer-tGV17 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 21
 * @framerIntrinsicWidth 230
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}
 * @framerVariables {"TVsgllYiM":"text"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerCE7zNdgHX = withCSS(Component, css, "framer-tGV17");
export default FramerCE7zNdgHX;
FramerCE7zNdgHX.displayName = "Pricing / Included item";
FramerCE7zNdgHX.defaultProps = { height: 21, width: 230 };
addPropertyControls(FramerCE7zNdgHX, {
  TVsgllYiM: {
    defaultValue: "Text",
    displayTextArea: false,
    title: "Text",
    type: ControlType.String,
  },
});
addFonts(
  FramerCE7zNdgHX,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerCE7zNdgHX",
      slots: [],
      annotations: {
        framerVariables: '{"TVsgllYiM":"text"}',
        framerIntrinsicHeight: "21",
        framerDisplayContentsDiv: "false",
        framerComponentViewportWidth: "true",
        framerImmutableVariables: "true",
        framerIntrinsicWidth: "230",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}',
        framerContractVersion: "1",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./CE7zNdgHX.map
