// Generated by Framer (915daba)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ComponentViewportProvider,
  ControlType,
  cx,
  getFonts,
  getFontsFromSharedStyle,
  Image,
  Link,
  RichText,
  SmartComponentScopedContainer,
  useComponentViewport,
  useLocaleCode,
  useLocaleInfo,
  useVariantState,
  withCSS,
  withFX,
  withOptimizedAppearEffect,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import * as sharedStyle from "https://framerusercontent.com/modules/0JLPmaxZxenFQzSWFxwu/qJpZiXfAIi1MBZmmNkaC/sw01V2bJD.js";
import * as sharedStyle1 from "https://framerusercontent.com/modules/1HoGQ6QwD2LyK0GEQDFa/dIKwJomSAtcf6KAJzpfk/uQRBhygQf.js";
import UIOutlineButton from "https://framerusercontent.com/modules/UBYkjxQRvSKJ23rZWpRu/jTyeTX4bUlUQqkvP4sTu/dWDvsM_2w.js";
const ImageWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
  withFX(Image)
);
const UIOutlineButtonFonts = getFonts(UIOutlineButton);
const enabledGestures = {
  ImsbINfaA: { hover: true },
  PXfeYnR9u: { hover: true },
};
const cycleOrder = ["PXfeYnR9u", "ImsbINfaA", "roaxSULFZ", "kJtfSsDGp"];
const serializationHash = "framer-oJhUn";
const variantClassNames = {
  ImsbINfaA: "framer-v-54y6jq",
  kJtfSsDGp: "framer-v-1qtewz0",
  PXfeYnR9u: "framer-v-1nqdhuf",
  roaxSULFZ: "framer-v-q7cnb3",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach(
    (variant) => variant && Object.assign(nextOverrides, overrides[variant])
  );
  return nextOverrides;
}
const transition1 = {
  delay: 0,
  duration: 0.5,
  ease: [0.68, 0, 0.16, 0.97],
  type: "tween",
};
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const transition2 = {
  delay: 0,
  duration: 1.5,
  ease: [0.68, 0, 0.16, 0.97],
  type: "tween",
};
const animation = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1,
  skewX: 0,
  skewY: 0,
  transition: transition2,
  x: 0,
  y: 0,
};
const animation1 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1.2,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const animation2 = {
  opacity: 1,
  rotate: 0,
  rotateX: 0,
  rotateY: 0,
  scale: 1.15,
  skewX: 0,
  skewY: 0,
  x: 0,
  y: 0,
};
const numberToPixelString = (value) => {
  if (typeof value !== "number") return value;
  if (!Number.isFinite(value)) return undefined;
  return Math.max(0, value) + "px";
};
const toDateString = (value, options = {}, activeLocale) => {
  if (typeof value !== "string") return "";
  const date = new Date(value);
  if (isNaN(date.getTime())) return "";
  const display = options.display ? options.display : "date";
  const dateOptions = {
    dateStyle: display !== "time" ? options.dateStyle : undefined,
    timeStyle: display === "date" ? undefined : "short",
    timeZone: "UTC",
  };
  const fallbackLocale = "en-US";
  const locale = options.locale || activeLocale || fallbackLocale; // We add a try block because an invalid language code results in a crash
  try {
    return date.toLocaleString(locale, dateOptions);
  } catch {
    return date.toLocaleString(fallbackLocale, dateOptions);
  }
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
  "Desktop narrow": "ImsbINfaA",
  Desktop: "PXfeYnR9u",
  Phone: "kJtfSsDGp",
  Tablet: "roaxSULFZ",
};
const getProps = ({
  date,
  height,
  id,
  image,
  link,
  padding,
  title,
  width,
  ...props
}) => {
  return {
    ...props,
    DVHVfGqy9: image ?? props.DVHVfGqy9,
    edqf_I0NI: padding ?? props.edqf_I0NI ?? "0px 0px 0px 16px",
    LlAOGF3rl:
      title ?? props.LlAOGF3rl ?? "Top Web Design Trends to Watch in 2024",
    variant:
      humanReadableVariantMap[props.variant] ?? props.variant ?? "PXfeYnR9u",
    WI12JNuXh: link ?? props.WI12JNuXh,
    ZGefvI4BF: date ?? props.ZGefvI4BF ?? "2024-10-31T20:00:00.000Z",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const {
    style,
    className,
    layoutId,
    variant,
    WI12JNuXh,
    DVHVfGqy9,
    ZGefvI4BF,
    LlAOGF3rl,
    edqf_I0NI,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "PXfeYnR9u",
    enabledGestures,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  const ref1 = React.useRef(null);
  const activeLocaleCode = useLocaleCode();
  const textContent = toDateString(
    ZGefvI4BF,
    { dateStyle: "medium", display: "date", locale: "" },
    activeLocaleCode
  );
  const defaultLayoutId = React.useId();
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId ?? defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsx(Link, {
          href: WI12JNuXh,
          motionChild: true,
          nodeId: "PXfeYnR9u",
          children: /*#__PURE__*/ _jsxs(motion.a, {
            ...restProps,
            ...gestureHandlers,
            className: `${cx(
              scopingClassNames,
              "framer-1nqdhuf",
              className,
              classNames
            )} framer-1u2oer7`,
            "data-framer-name": "Desktop",
            layoutDependency: layoutDependency,
            layoutId: "PXfeYnR9u",
            ref: ref ?? ref1,
            style: { ...style },
            ...addPropertyOverrides(
              {
                "ImsbINfaA-hover": { "data-framer-name": undefined },
                "PXfeYnR9u-hover": { "data-framer-name": undefined },
                ImsbINfaA: { "data-framer-name": "Desktop narrow" },
                kJtfSsDGp: { "data-framer-name": "Phone" },
                roaxSULFZ: { "data-framer-name": "Tablet" },
              },
              baseVariant,
              gestureVariant
            ),
            children: [
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-1y7voto",
                "data-border": true,
                "data-framer-name": "Corner",
                layoutDependency: layoutDependency,
                layoutId: "KHWiQkpBq",
                style: {
                  "--border-bottom-width": "2px",
                  "--border-color":
                    "var(--token-1662617d-fd18-4319-b3da-aa36e5415705, rgb(249, 69, 45))",
                  "--border-left-width": "0px",
                  "--border-right-width": "2px",
                  "--border-style": "solid",
                  "--border-top-width": "0px",
                  rotate: -90,
                },
              }),
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-djcvpt",
                "data-framer-name": "Image",
                layoutDependency: layoutDependency,
                layoutId: "FicBOAxzl",
                children: /*#__PURE__*/ _jsx(
                  ImageWithFXWithOptimizedAppearEffect,
                  {
                    __perspectiveFX: false,
                    __smartComponentFX: true,
                    __targetOpacity: 1,
                    animate: animation,
                    background: {
                      alt: "",
                      fit: "fill",
                      sizes: `max(${componentViewport?.width || "100vw"}, 1px)`,
                      ...toResponsiveImage(DVHVfGqy9),
                    },
                    className: "framer-50czeo",
                    "data-framer-appear-id": "50czeo",
                    initial: animation1,
                    layoutDependency: layoutDependency,
                    layoutId: "Bhs8qFZCp",
                    optimized: true,
                    style: { scale: 1 },
                    variants: {
                      "ImsbINfaA-hover": { scale: 1.1 },
                      "PXfeYnR9u-hover": { scale: 1.1 },
                    },
                    ...addPropertyOverrides(
                      {
                        "ImsbINfaA-hover": {
                          animate: undefined,
                          initial: undefined,
                          optimized: undefined,
                        },
                        "PXfeYnR9u-hover": {
                          animate: undefined,
                          initial: undefined,
                          optimized: undefined,
                        },
                        kJtfSsDGp: { initial: animation2 },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                  }
                ),
              }),
              /*#__PURE__*/ _jsxs(motion.div, {
                className: "framer-1jmg8jo",
                "data-framer-name": "Text",
                layoutDependency: layoutDependency,
                layoutId: "yL3t9A7pk",
                style: { "--15rhhwa": numberToPixelString(edqf_I0NI) },
                children: [
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-euzhrp",
                    "data-framer-name": "Top",
                    layoutDependency: layoutDependency,
                    layoutId: "SwJk28Dks",
                    children: [
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.p, {
                            className: "framer-styles-preset-1hahlh8",
                            "data-styles-preset": "sw01V2bJD",
                            style: {
                              "--framer-text-color":
                                "var(--extracted-r6o4lv, rgba(12, 12, 12, 0.6))",
                            },
                            children: "Content",
                          }),
                        }),
                        className: "framer-1n14g2g",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "HUyIJQCwa",
                        style: {
                          "--extracted-r6o4lv": "rgba(12, 12, 12, 0.6)",
                        },
                        text: textContent,
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                      /*#__PURE__*/ _jsx(RichText, {
                        __fromCanvasComponent: true,
                        children: /*#__PURE__*/ _jsx(React.Fragment, {
                          children: /*#__PURE__*/ _jsx(motion.h3, {
                            className: "framer-styles-preset-ddjjzx",
                            "data-styles-preset": "uQRBhygQf",
                            children:
                              "How fast is fast enough? Website speed in 2024",
                          }),
                        }),
                        className: "framer-1yk98ga",
                        fonts: ["Inter"],
                        layoutDependency: layoutDependency,
                        layoutId: "oEr5SmGMb",
                        text: LlAOGF3rl,
                        verticalAlignment: "top",
                        withExternalLayout: true,
                      }),
                    ],
                  }),
                  /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 29,
                    children: /*#__PURE__*/ _jsx(
                      SmartComponentScopedContainer,
                      {
                        className: "framer-1edcre2-container",
                        layoutDependency: layoutDependency,
                        layoutId: "MJp3SMGrL-container",
                        nodeId: "MJp3SMGrL",
                        rendersWithMotion: true,
                        scopeId: "DyECzRfVJ",
                        children: /*#__PURE__*/ _jsx(UIOutlineButton, {
                          height: "100%",
                          id: "MJp3SMGrL",
                          layoutId: "MJp3SMGrL",
                          width: "100%",
                        }),
                      }
                    ),
                  }),
                ],
              }),
            ],
          }),
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-oJhUn.framer-1u2oer7, .framer-oJhUn .framer-1u2oer7 { display: block; }",
  ".framer-oJhUn.framer-1nqdhuf { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; text-decoration: none; width: 277px; }",
  ".framer-oJhUn .framer-1y7voto { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 9px); position: absolute; right: 30px; top: 30px; width: 9px; z-index: 1; }",
  ".framer-oJhUn .framer-djcvpt { align-content: center; align-items: center; aspect-ratio: 1.385 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: var(--framer-aspect-ratio-supported, 144px); justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
  ".framer-oJhUn .framer-50czeo { flex: 1 0 0px; height: 100%; position: relative; width: 1px; }",
  ".framer-oJhUn .framer-1jmg8jo { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: flex-start; overflow: hidden; padding: var(--15rhhwa); position: relative; width: 100%; }",
  ".framer-oJhUn .framer-euzhrp { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
  ".framer-oJhUn .framer-1n14g2g { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  ".framer-oJhUn .framer-1yk98ga { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
  ".framer-oJhUn .framer-1edcre2-container { flex: none; height: auto; position: relative; width: auto; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-oJhUn.framer-1nqdhuf, .framer-oJhUn .framer-djcvpt, .framer-oJhUn .framer-1jmg8jo, .framer-oJhUn .framer-euzhrp { gap: 0px; } .framer-oJhUn.framer-1nqdhuf > * { margin: 0px; margin-bottom: calc(36px / 2); margin-top: calc(36px / 2); } .framer-oJhUn.framer-1nqdhuf > :first-child, .framer-oJhUn .framer-1jmg8jo > :first-child, .framer-oJhUn .framer-euzhrp > :first-child { margin-top: 0px; } .framer-oJhUn.framer-1nqdhuf > :last-child, .framer-oJhUn .framer-1jmg8jo > :last-child, .framer-oJhUn .framer-euzhrp > :last-child { margin-bottom: 0px; } .framer-oJhUn .framer-djcvpt > * { margin: 0px; margin-left: calc(20px / 2); margin-right: calc(20px / 2); } .framer-oJhUn .framer-djcvpt > :first-child { margin-left: 0px; } .framer-oJhUn .framer-djcvpt > :last-child { margin-right: 0px; } .framer-oJhUn .framer-1jmg8jo > * { margin: 0px; margin-bottom: calc(30px / 2); margin-top: calc(30px / 2); } .framer-oJhUn .framer-euzhrp > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } }",
  ".framer-oJhUn.framer-v-54y6jq .framer-djcvpt { aspect-ratio: 1.73125 / 1; height: var(--framer-aspect-ratio-supported, 116px); }",
  ".framer-oJhUn.framer-v-q7cnb3.framer-1nqdhuf { cursor: unset; gap: 32px; }",
  ".framer-oJhUn.framer-v-q7cnb3 .framer-1y7voto, .framer-oJhUn.framer-v-1qtewz0 .framer-1y7voto { right: 26px; top: 26px; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-oJhUn.framer-v-q7cnb3.framer-1nqdhuf { gap: 0px; } .framer-oJhUn.framer-v-q7cnb3.framer-1nqdhuf > * { margin: 0px; margin-bottom: calc(32px / 2); margin-top: calc(32px / 2); } .framer-oJhUn.framer-v-q7cnb3.framer-1nqdhuf > :first-child { margin-top: 0px; } .framer-oJhUn.framer-v-q7cnb3.framer-1nqdhuf > :last-child { margin-bottom: 0px; } }",
  ".framer-oJhUn.framer-v-1qtewz0.framer-1nqdhuf { cursor: unset; gap: 30px; }",
  ".framer-oJhUn.framer-v-1qtewz0 .framer-1jmg8jo { gap: 22px; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-oJhUn.framer-v-1qtewz0.framer-1nqdhuf, .framer-oJhUn.framer-v-1qtewz0 .framer-1jmg8jo { gap: 0px; } .framer-oJhUn.framer-v-1qtewz0.framer-1nqdhuf > * { margin: 0px; margin-bottom: calc(30px / 2); margin-top: calc(30px / 2); } .framer-oJhUn.framer-v-1qtewz0.framer-1nqdhuf > :first-child, .framer-oJhUn.framer-v-1qtewz0 .framer-1jmg8jo > :first-child { margin-top: 0px; } .framer-oJhUn.framer-v-1qtewz0.framer-1nqdhuf > :last-child, .framer-oJhUn.framer-v-1qtewz0 .framer-1jmg8jo > :last-child { margin-bottom: 0px; } .framer-oJhUn.framer-v-1qtewz0 .framer-1jmg8jo > * { margin: 0px; margin-bottom: calc(22px / 2); margin-top: calc(22px / 2); } }",
  ".framer-oJhUn.framer-v-1nqdhuf.hover .framer-1y7voto, .framer-oJhUn.framer-v-54y6jq.hover .framer-1y7voto { right: 36px; top: 36px; }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
  '.framer-oJhUn[data-border="true"]::after, .framer-oJhUn [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 426
 * @framerIntrinsicWidth 277
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"ImsbINfaA":{"layout":["fixed","auto"]},"roaxSULFZ":{"layout":["fixed","auto"]},"kJtfSsDGp":{"layout":["fixed","auto"]},"GzsnhAjvn":{"layout":["fixed","auto"]},"OQpOKTC0H":{"layout":["fixed","auto"]}}}
 * @framerVariables {"WI12JNuXh":"link","DVHVfGqy9":"image","ZGefvI4BF":"date","LlAOGF3rl":"title","edqf_I0NI":"padding"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerDyECzRfVJ = withCSS(Component, css, "framer-oJhUn");
export default FramerDyECzRfVJ;
FramerDyECzRfVJ.displayName = "Blog / Article";
FramerDyECzRfVJ.defaultProps = { height: 426, width: 277 };
addPropertyControls(FramerDyECzRfVJ, {
  variant: {
    options: ["PXfeYnR9u", "ImsbINfaA", "roaxSULFZ", "kJtfSsDGp"],
    optionTitles: ["Desktop", "Desktop narrow", "Tablet", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  WI12JNuXh: { title: "Link", type: ControlType.Link },
  DVHVfGqy9: { title: "Image", type: ControlType.ResponsiveImage },
  ZGefvI4BF: {
    defaultValue: "2024-10-31T20:00:00.000Z",
    title: "Date",
    type: ControlType.Date,
  },
  LlAOGF3rl: {
    defaultValue: "Top Web Design Trends to Watch in 2024",
    title: "Title",
    type: ControlType.String,
  },
  edqf_I0NI: {
    defaultValue: "0px 0px 0px 16px",
    title: "Padding",
    type: ControlType.Padding,
  },
});
addFonts(
  FramerDyECzRfVJ,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...UIOutlineButtonFonts,
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerDyECzRfVJ",
      slots: [],
      annotations: {
        framerComponentViewportWidth: "true",
        framerContractVersion: "1",
        framerImmutableVariables: "true",
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"ImsbINfaA":{"layout":["fixed","auto"]},"roaxSULFZ":{"layout":["fixed","auto"]},"kJtfSsDGp":{"layout":["fixed","auto"]},"GzsnhAjvn":{"layout":["fixed","auto"]},"OQpOKTC0H":{"layout":["fixed","auto"]}}}',
        framerDisplayContentsDiv: "false",
        framerIntrinsicWidth: "277",
        framerIntrinsicHeight: "426",
        framerVariables:
          '{"WI12JNuXh":"link","DVHVfGqy9":"image","ZGefvI4BF":"date","LlAOGF3rl":"title","edqf_I0NI":"padding"}',
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./DyECzRfVJ.map
