// Generated by Framer (0847096)
import {
  addPropertyControls as e,
  ControlType as t,
  QueryEngine as l,
} from "framer";
import { DatabaseCollection as i } from "./rXPb48_DN-0.js";
import { resolveRichText as r } from "./rXPb48_DN-1.js";
let n = {
    E9FnOb4ni: { isNullable: !0, type: t.String },
    id: { isNullable: !1, type: t.String },
    JRY3_qGYV: { isNullable: !0, type: t.String },
    nextItemId: { isNullable: !0, type: t.String },
    previousItemId: { isNullable: !0, type: t.String },
  },
  a = new l(),
  o = {
    collectionByLocaleId: {
      default: new i({
        chunks: [
          new URL(
            "./rXPb48_DN-chunk-default-0.framercms",
            "https://framerusercontent.com/modules/jovE7hxUbx46hxdMER2G/3SigILoUobfEtgpIVbyV/rXPb48_DN.js"
          ).href,
        ],
        compressionDictionary: new URL(
          "./rXPb48_DN-chunk-default-dict.framercms",
          "https://framerusercontent.com/modules/jovE7hxUbx46hxdMER2G/3SigILoUobfEtgpIVbyV/rXPb48_DN.js"
        ).href,
        indexes: [],
        resolveRichText: r,
        schema: n,
      }),
    },
    displayName: "Category",
  };
export default o;
e(o, {
  JRY3_qGYV: { defaultValue: "", title: "Title", type: t.String },
  E9FnOb4ni: { title: "Slug", type: t.String },
  previousItemId: {
    dataIdentifier: "local-module:collection/rXPb48_DN:default",
    title: "Previous",
    type: t.CollectionReference,
  },
  nextItemId: {
    dataIdentifier: "local-module:collection/rXPb48_DN:default",
    title: "Next",
    type: t.CollectionReference,
  },
});
export const enumToDisplayNameFunctions = {};
export const utils = {
  async getSlugByRecordId(e, t) {
    let [l] = await a.query(
      {
        from: { data: o, type: "Collection" },
        limit: { type: "LiteralValue", value: 1 },
        select: [{ name: "E9FnOb4ni", type: "Identifier" }],
        where: {
          left: { name: "id", type: "Identifier" },
          operator: "==",
          right: { type: "LiteralValue", value: e },
          type: "BinaryOperation",
        },
      },
      t
    );
    return null == l ? void 0 : l.E9FnOb4ni;
  },
  async getRecordIdBySlug(e, t) {
    let [l] = await a.query(
      {
        from: { data: o, type: "Collection" },
        limit: { type: "LiteralValue", value: 1 },
        select: [{ name: "id", type: "Identifier" }],
        where: {
          left: { name: "E9FnOb4ni", type: "Identifier" },
          operator: "==",
          right: { type: "LiteralValue", value: e },
          type: "BinaryOperation",
        },
      },
      t
    );
    return null == l ? void 0 : l.id;
  },
};
export const __FramerMetadata__ = {
  exports: {
    enumToDisplayNameFunctions: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    utils: { type: "variable", annotations: { framerContractVersion: "1" } },
    default: {
      type: "data",
      name: "data",
      annotations: {
        framerCollectionId: "rXPb48_DN",
        framerContractVersion: "1",
        framerData: "",
        framerEnumToDisplayNameUtils: "2",
        framerRecordIdKey: "id",
        framerSlug: "E9FnOb4ni",
        framerCollectionUtils: "1",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
