// Generated by Framer (915daba)
import { fontStore } from "framer";
fontStore.loadFonts([]);
export const fonts = [{ explicitInter: true, fonts: [] }];
export const css = [
  ".framer-vBwZu .framer-styles-preset-1nr60og:not(.rich-text-wrapper), .framer-vBwZu .framer-styles-preset-1nr60og.rich-text-wrapper a { --framer-link-current-text-color: var(--token-d74d16c5-23aa-4649-a2ad-0da8c936dade, #ffffff); --framer-link-current-text-decoration: none; --framer-link-hover-text-color: rgba(255, 255, 255, 0.8); --framer-link-hover-text-decoration: none; --framer-link-text-color: #ffffff; --framer-link-text-decoration: none; transition: color 0.4s cubic-bezier(0.44, 0, 0.56, 1) 0s; }",
];
export const className = "framer-vBwZu";
export const __FramerMetadata__ = {
  exports: {
    fonts: { type: "variable", annotations: { framerContractVersion: "1" } },
    css: { type: "variable", annotations: { framerContractVersion: "1" } },
    className: {
      type: "variable",
      annotations: { framerContractVersion: "1" },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
