// Generated by Framer (6f76210)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  getFontsFromSharedStyle,
  getLoadingLazyAtYPosition,
  Image,
  RichText,
  useComponentViewport,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import * as sharedStyle1 from "https://framerusercontent.com/modules/99CfbQ0g2aHd3wkMunJ6/y1C7t0UV7hgBOIy2DUxd/q35quwzCc.js";
import * as sharedStyle from "https://framerusercontent.com/modules/oMgXPBeR6YdHTzKPyOpl/EoE1kmmGpZHB3Wts7nST/xNIXLfFSf.js";
const cycleOrder = ["hDbCvcxst", "KVvKXtHq9"];
const serializationHash = "framer-eBwJi";
const variantClassNames = {
  hDbCvcxst: "framer-v-145ktc9",
  KVvKXtHq9: "framer-v-yd3s1d",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) => variant && Object.assign(nextOverrides, overrides[variant])
      );
  return nextOverrides;
}
const transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
const toResponsiveImage = (value) => {
  if (
    typeof value === "object" &&
    value !== null &&
    typeof value.src === "string"
  ) {
    return value;
  }
  return typeof value === "string" ? { src: value } : undefined;
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition =
    value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = { Phone: "KVvKXtHq9", Primary: "hDbCvcxst" };
const getProps = ({
  description,
  height,
  id,
  image,
  title,
  width,
  ...props
}) => {
  var _ref, _ref1, _humanReadableVariantMap_props_variant, _ref2;
  return {
    ...props,
    iU68ScBCY:
      (_ref =
        description !== null && description !== void 0
          ? description
          : props.iU68ScBCY) !== null && _ref !== void 0
        ? _ref
        : "Description",
    M6makQZJz:
      (_ref1 = title !== null && title !== void 0 ? title : props.M6makQZJz) !==
        null && _ref1 !== void 0
        ? _ref1
        : "Title",
    OtapoObdF: image !== null && image !== void 0 ? image : props.OtapoObdF,
    variant:
      (_ref2 =
        (_humanReadableVariantMap_props_variant =
          humanReadableVariantMap[props.variant]) !== null &&
        _humanReadableVariantMap_props_variant !== void 0
          ? _humanReadableVariantMap_props_variant
          : props.variant) !== null && _ref2 !== void 0
        ? _ref2
        : "hDbCvcxst",
  };
};
const createLayoutDependency = (props, variants) => {
  if (props.layoutDependency)
    return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const {
    style,
    className,
    layoutId,
    variant,
    OtapoObdF,
    M6makQZJz,
    iU68ScBCY,
    ...restProps
  } = getProps(props);
  const {
    baseVariant,
    classNames,
    clearLoadingGesture,
    gestureHandlers,
    gestureVariant,
    isLoading,
    setGestureState,
    setVariant,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "hDbCvcxst",
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className];
  const componentViewport = useComponentViewport();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(Variants, {
      animate: variants,
      initial: false,
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition1,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          ...gestureHandlers,
          className: cx(
            serializationHash,
            ...sharedStyleClassNames,
            "framer-145ktc9",
            className,
            classNames
          ),
          "data-framer-name": "Primary",
          layoutDependency: layoutDependency,
          layoutId: "hDbCvcxst",
          ref: ref !== null && ref !== void 0 ? ref : ref1,
          style: { ...style },
          ...addPropertyOverrides(
            { KVvKXtHq9: { "data-framer-name": "Phone" } },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsx(Image, {
              background: {
                alt: "",
                fit: "fill",
                loading: getLoadingLazyAtYPosition(
                  ((componentViewport === null || componentViewport === void 0
                    ? void 0
                    : componentViewport.y) || 0) +
                    0 +
                    ((((componentViewport === null ||
                    componentViewport === void 0
                      ? void 0
                      : componentViewport.height) || 245.5) -
                      0 -
                      359.8) /
                      2 +
                      0 +
                      0)
                ),
                pixelHeight: 315,
                pixelWidth: 437,
                sizes:
                  (componentViewport === null || componentViewport === void 0
                    ? void 0
                    : componentViewport.width) || "100vw",
                ...toResponsiveImage(OtapoObdF),
                ...{ positionX: "center", positionY: "center" },
              },
              className: "framer-1ieoc4f",
              "data-framer-name": "BG",
              layoutDependency: layoutDependency,
              layoutId: "Y9Cx1EXp6",
              ...addPropertyOverrides(
                {
                  KVvKXtHq9: {
                    background: {
                      alt: "",
                      fit: "fill",
                      loading: getLoadingLazyAtYPosition(
                        ((componentViewport === null ||
                        componentViewport === void 0
                          ? void 0
                          : componentViewport.y) || 0) +
                          0 +
                          ((((componentViewport === null ||
                          componentViewport === void 0
                            ? void 0
                            : componentViewport.height) || 191.5) -
                            0 -
                            305.8) /
                            2 +
                            0 +
                            0)
                      ),
                      pixelHeight: 315,
                      pixelWidth: 437,
                      sizes:
                        (componentViewport === null ||
                        componentViewport === void 0
                          ? void 0
                          : componentViewport.width) || "100vw",
                      ...toResponsiveImage(OtapoObdF),
                      ...{ positionX: "center", positionY: "center" },
                    },
                  },
                },
                baseVariant,
                gestureVariant
              ),
            }),
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-11zx5yf",
              "data-framer-name": "Text",
              layoutDependency: layoutDependency,
              layoutId: "XGsulj8pd",
              children: [
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      className: "framer-styles-preset-jnye1g",
                      "data-styles-preset": "xNIXLfFSf",
                      style: {
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-d74d16c5-23aa-4649-a2ad-0da8c936dade, rgb(255, 255, 255)))",
                      },
                      children: "Title",
                    }),
                  }),
                  className: "framer-1qxv4mt",
                  "data-framer-name": "Branding",
                  fonts: ["Inter"],
                  layoutDependency: layoutDependency,
                  layoutId: "b2S116wtB",
                  style: {
                    "--extracted-r6o4lv":
                      "var(--token-d74d16c5-23aa-4649-a2ad-0da8c936dade, rgb(255, 255, 255))",
                    "--framer-paragraph-spacing": "0px",
                    opacity: 0.6,
                  },
                  text: M6makQZJz,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                }),
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      className: "framer-styles-preset-1dmjd5e",
                      "data-styles-preset": "q35quwzCc",
                      style: {
                        "--framer-text-color":
                          "var(--extracted-r6o4lv, var(--token-d74d16c5-23aa-4649-a2ad-0da8c936dade, rgb(255, 255, 255)))",
                      },
                      children: "Description",
                    }),
                  }),
                  className: "framer-1q2ai5c",
                  "data-framer-name":
                    "We create impactful brand identities that differentiate your business and connect with your audience.",
                  fonts: ["Inter"],
                  layoutDependency: layoutDependency,
                  layoutId: "lEPU50rVm",
                  style: {
                    "--extracted-r6o4lv":
                      "var(--token-d74d16c5-23aa-4649-a2ad-0da8c936dade, rgb(255, 255, 255))",
                    "--framer-paragraph-spacing": "0px",
                  },
                  text: iU68ScBCY,
                  verticalAlignment: "top",
                  withExternalLayout: true,
                }),
              ],
            }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-eBwJi.framer-g71a2p, .framer-eBwJi .framer-g71a2p { display: block; }",
  ".framer-eBwJi.framer-145ktc9 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 50px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 180px; }",
  ".framer-eBwJi .framer-1ieoc4f { aspect-ratio: 1.3846153846153846 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 130px); position: relative; width: 100%; }",
  ".framer-eBwJi .framer-11zx5yf { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
  ".framer-eBwJi .framer-1qxv4mt { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  ".framer-eBwJi .framer-1q2ai5c { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-eBwJi.framer-145ktc9, .framer-eBwJi .framer-11zx5yf { gap: 0px; } .framer-eBwJi.framer-145ktc9 > * { margin: 0px; margin-bottom: calc(50px / 2); margin-top: calc(50px / 2); } .framer-eBwJi.framer-145ktc9 > :first-child, .framer-eBwJi .framer-11zx5yf > :first-child { margin-top: 0px; } .framer-eBwJi.framer-145ktc9 > :last-child, .framer-eBwJi .framer-11zx5yf > :last-child { margin-bottom: 0px; } .framer-eBwJi .framer-11zx5yf > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } }",
  ".framer-eBwJi.framer-v-yd3s1d.framer-145ktc9 { gap: 32px; }",
  ".framer-eBwJi.framer-v-yd3s1d .framer-1ieoc4f { aspect-ratio: 1.8 / 1; height: var(--framer-aspect-ratio-supported, 100px); }",
  ".framer-eBwJi.framer-v-yd3s1d .framer-11zx5yf { gap: 10px; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-eBwJi.framer-v-yd3s1d.framer-145ktc9, .framer-eBwJi.framer-v-yd3s1d .framer-11zx5yf { gap: 0px; } .framer-eBwJi.framer-v-yd3s1d.framer-145ktc9 > * { margin: 0px; margin-bottom: calc(32px / 2); margin-top: calc(32px / 2); } .framer-eBwJi.framer-v-yd3s1d.framer-145ktc9 > :first-child, .framer-eBwJi.framer-v-yd3s1d .framer-11zx5yf > :first-child { margin-top: 0px; } .framer-eBwJi.framer-v-yd3s1d.framer-145ktc9 > :last-child, .framer-eBwJi.framer-v-yd3s1d .framer-11zx5yf > :last-child { margin-bottom: 0px; } .framer-eBwJi.framer-v-yd3s1d .framer-11zx5yf > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } }",
  ...sharedStyle.css,
  ...sharedStyle1.css,
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 245.5
 * @framerIntrinsicWidth 180
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"KVvKXtHq9":{"layout":["fixed","auto"]}}}
 * @framerVariables {"OtapoObdF":"image","M6makQZJz":"title","iU68ScBCY":"description"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */ const FramerJDguMTCRG = withCSS(Component, css, "framer-eBwJi");
export default FramerJDguMTCRG;
FramerJDguMTCRG.displayName = "Services / Items / Description";
FramerJDguMTCRG.defaultProps = { height: 245.5, width: 180 };
addPropertyControls(FramerJDguMTCRG, {
  variant: {
    options: ["hDbCvcxst", "KVvKXtHq9"],
    optionTitles: ["Primary", "Phone"],
    title: "Variant",
    type: ControlType.Enum,
  },
  OtapoObdF: { title: "Image", type: ControlType.ResponsiveImage },
  M6makQZJz: {
    defaultValue: "Title",
    displayTextArea: false,
    placeholder: "",
    title: "Title",
    type: ControlType.String,
  },
  iU68ScBCY: {
    defaultValue: "Description",
    displayTextArea: false,
    title: "Description",
    type: ControlType.String,
  },
});
addFonts(
  FramerJDguMTCRG,
  [
    {
      explicitInter: true,
      fonts: [
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
          url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
          url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+1F00-1FFF",
          url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange: "U+0370-03FF",
          url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
          url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
          url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
          weight: "400",
        },
        {
          family: "Inter",
          source: "framer",
          style: "normal",
          unicodeRange:
            "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
          url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
          weight: "400",
        },
      ],
    },
    ...getFontsFromSharedStyle(sharedStyle.fonts),
    ...getFontsFromSharedStyle(sharedStyle1.fonts),
  ],
  { supportsExplicitInterCodegen: true }
);
export const __FramerMetadata__ = {
  exports: {
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    default: {
      type: "reactComponent",
      name: "FramerJDguMTCRG",
      slots: [],
      annotations: {
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"KVvKXtHq9":{"layout":["fixed","auto"]}}}',
        framerDisplayContentsDiv: "false",
        framerComponentViewportWidth: "true",
        framerImmutableVariables: "true",
        framerVariables:
          '{"OtapoObdF":"image","M6makQZJz":"title","iU68ScBCY":"description"}',
        framerIntrinsicWidth: "180",
        framerContractVersion: "1",
        framerIntrinsicHeight: "245.5",
      },
    },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./JDguMTCRG.map
